#
# Copyright (c) 2002, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#  
#


all:
	cd dbx; $(MAKE) all
	cd proc; $(MAKE) all

clean:
	cd dbx; $(MAKE) clean
	cd proc; $(MAKE) clean
