/*
* "@(#)Resources_sv.java	1.11 04/02/27
*
* Copyright 2004 Sun Microsystems, Inc. All rights reserved.
* SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
*/

package sun.security.util;

/**
* <p> This class represents the <code>ResourceBundle</code>
* for javax.security.auth and sun.security.
*
* @version 1.18, 09/30/03
*/
public class Resources_sv extends java.util.ListResourceBundle {

    private static final Object[][] contents = {

	// shared (from jarsigner)
	{" ", " "},
	{"  ", "  "},
	{"      ", "      "},
	{", ", ", "},
	// shared (from keytool)
	{"\n", "\n"},
	{"*******************************************",
		"*******************************************"},
	{"*******************************************\n\n",
		"*******************************************\n\n"},
      
	// keytool
	{"keytool error: ", "nyckelverktygsfel: "},
	{"Illegal option:  ", "Ogiltigt alternativ:  "},
	{"-keystore must be NONE if -storetype is PKCS11",
		"-keystore m\u00e5ste vara NONE om -storetype \u00e4r PKCS11"},
	{"-storepasswd and -keypasswd commands not supported if -storetype is PKCS11",
		"kommandona -storepasswd och -keypasswd st\u00f6ds inte om -storetype \u00e4r PKCS11"},
	{"-keypass and -new can not be specified if -storetype is PKCS11",
		"det g\u00e5r inte att ange -keypass och -new om -storetype \u00e4r PKCS11"},
	{"if -protected is specified, then -storepass, -keypass, and -new must not be specified",
		"om -protected har angetts f\u00e5r inte -storepass, -keypass och -new anges"},
	{"Validity must be greater than zero",
		"Giltigheten m\u00e5ste vara st\u00f6rre \u00e4n noll"},
	{"provName not a provider", "{0} inte en leverant\u00f6r"},
	{"Must not specify both -v and -rfc with 'list' command",
		"Det g\u00e5r inte att specificera b\u00e5de -v och -rfc med 'list'-kommandot"},
	{"Key password must be at least 6 characters",
		"Nyckell\u00f6senordet m\u00e5ste inneh\u00e5lla minst 6 tecken"},
	{"New password must be at least 6 characters",
		"Det nya l\u00f6senordet m\u00e5ste inneh\u00e5lla minst 6 tecken"},
	{"Keystore file exists, but is empty: ",
		"Keystore-filen finns, men \u00e4r tom: "},
	{"Keystore file does not exist: ",
		"Keystore-filen finns inte: "},
	{"Must specify destination alias", "Du m\u00e5ste ange destinations-alias"},
	{"Must specify alias", "Du m\u00e5ste ange alias"},
	{"Keystore password must be at least 6 characters",
		"Keystore-l\u00f6senordet m\u00e5ste inneh\u00e5lla minst 6 tecken"},
	{"Enter keystore password:  ", "Ange keystore-l\u00f6senord:  "},
	{"Keystore password is too short - must be at least 6 characters",
	 "Keystore-l\u00f6senordet \u00e4r f\u00f6r kort - det m\u00e5ste inneh\u00e5lla minst 6 tecken"},
	{"Too many failures - try later", "F\u00f6r m\u00e5nga fel - f\u00f6rs\u00f6k igen senare"},
	{"Certification request stored in file <filename>",
		"Certifikat-f\u00f6rfr\u00e5gan har lagrats i filen <{0}>"},
	{"Submit this to your CA", "Skicka detta till din CA"},
	{"Certificate stored in file <filename>",
		"Certifikatet har lagrats i filen <{0}>"},
	{"Certificate reply was installed in keystore",
		"Certifikatsvaret har installerats i keystore-filen"},
	{"Certificate reply was not installed in keystore",
		"Certifikatsvaret har inte installerats i keystore-filen"},
	{"Certificate was added to keystore",
		"Certifikatet har lagts till i keystore-filen"},
	{"Certificate was not added to keystore",
		"Certifikatet har inte lagts till i keystore-filen"},
	{"[Storing ksfname]", "[Lagrar {0}]"},
	{"alias has no public key (certificate)",
		"{0} saknar offentlig nyckel (certifikat)"},
	{"Cannot derive signature algorithm",
		"Det g\u00e5r inte att h\u00e4mta n\u00e5gon signatur-algoritm"},
	{"Alias <alias> does not exist",
		"Aliaset <{0}> finns inte"},
	{"Alias <alias> has no certificate",
		"Aliaset <{0}> saknar certifikat"},
	{"Key pair not generated, alias <alias> already exists",
		"Nyckelparet genererades inte. Aliaset <{0}> finns redan"},
	{"Cannot derive signature algorithm",
		"Det g\u00e5r inte att h\u00e4mta n\u00e5gon signatur-algoritm"},
	{"Generating keysize bit keyAlgName key pair and self-signed certificate (sigAlgName)\n\tfor: x500Name",
		"Genererar {0}-bitars {1}-nyckelpar och det sj\u00e4lvsignerade certifikatet ({2})\n\tf\u00f6r: {3}"},
	{"Enter key password for <alias>", "Ange nyckell\u00f6senord f\u00f6r <{0}>"},
	{"\t(RETURN if same as keystore password):  ",
		"\t(RETURN om det \u00e4r identiskt med keystore-l\u00f6senordet):  "},
	{"Key password is too short - must be at least 6 characters",
		"Nyckell\u00f6senordet \u00e4r f\u00f6r kort - det m\u00e5ste inneh\u00e5lla minst 6 tecken"},
	{"Too many failures - key not added to keystore",
		"F\u00f6r m\u00e5nga fel - nyckeln lades inte till i keystore-filen"},
	{"Destination alias <dest> already exists",
		"Destinationsaliaset <{0}> finns redan"},
	{"Password is too short - must be at least 6 characters",
		"L\u00f6senordet \u00e4r f\u00f6r kort - det m\u00e5ste inneh\u00e5lla minst 6 tecken"},
	{"Too many failures. Key entry not cloned",
		"F\u00f6r m\u00e5nga fel. Nyckelposten har inte klonats"},
	{"key password for <alias>", "nyckell\u00f6senord f\u00f6r <{0}>"},
	{"Keystore entry for <id.getName()> already exists",
		"Keystore-post f\u00f6r <{0}> finns redan"},
	{"Creating keystore entry for <id.getName()> ...",
		"Skapar keystore-post f\u00f6r <{0}> ..."},
	{"No entries from identity database added",
		"Inga poster fr\u00e5n identitetsdatabasen har lagts till"},
	{"Alias name: alias", "Aliasnamn: {0}"},
	{"Creation date: keyStore.getCreationDate(alias)",
		"Skapat den: {0,date}"},
	{"alias, keyStore.getCreationDate(alias), ",
		"{0}, {1,date}, "},
	{"alias, ", "{0}, "},
	{"Entry type: keyEntry", "Posttyp: keyEntry"},
	{"keyEntry,", "keyEntry,"},
	{"Certificate chain length: ", "L\u00e4ngd p\u00e5 certifikatskedja: "},
	{"Certificate[(i + 1)]:", "Certifikat[{0,number,integer}]:"},
	{"Certificate fingerprint (MD5): ", "Certifikatsfingeravtryck (MD5): "},
	{"Entry type: trustedCertEntry\n", "Posttyp: trustedCertEntry\n"},
	{"trustedCertEntry,", "trustedCertEntry,"},
	{"Keystore type: ", "Keystore-typ: "},
	{"Keystore provider: ", "Keystore-leverant\u00f6r: "},
	{"Your keystore contains keyStore.size() entry",
		"Din keystore inneh\u00e5ller en {0,number,integer} post"},
	{"Your keystore contains keyStore.size() entries",
		"Din keystore inneh\u00e5ller {0,number,integer} poster"},
	{"Failed to parse input", "Det g\u00e5r inte att analysera indata"},
	{"Empty input", "Inga indata"},
	{"Not X.509 certificate", "Inte ett X.509-certifikat"},
	{"Cannot derive signature algorithm",
		"Det g\u00e5r inte att h\u00e4mta n\u00e5gon signatur-algoritm"},
	{"alias has no public key", "{0} saknar offentlig nyckel"},
	{"alias has no X.509 certificate", "{0} saknar X.509-certifikat"},
	{"New certificate (self-signed):", "Nytt certifikat (sj\u00e4lvsignerat):"},
	{"Reply has no certificates", "Svaret saknar certifikat"},
	{"Certificate not imported, alias <alias> already exists",
		"Certifikatet importerades inte. Aliaset <{0}> finns redan"},
	{"Input not an X.509 certificate", "Indata \u00e4r inte ett X.509-certifikat"},
	{"Certificate already exists in keystore under alias <trustalias>",
		"Certifikatet finns redan i keystore-filen under aliaset <{0}>"},
	{"Do you still want to add it? [no]:  ",
		"Vill du fortfarande l\u00e4gga till det? [nej]:  "},
	{"Certificate already exists in system-wide CA keystore under alias <trustalias>",
		"Certifikatet finns redan i systemkeystore-filen under aliaset <{0}>"},
	{"Do you still want to add it to your own keystore? [no]:  ",
		"Vill du fortfarande l\u00e4gga till det i din egen keystore-fil? [nej]:  "},
	{"Trust this certificate? [no]:  ", "Betror du det h\u00e4r certifikatet? [nej]:  "},
	{"YES", "JA"},
	{"New prompt: ", "Nytt {0}: "},
	{"Passwords must differ", "L\u00f6senorden m\u00e5ste vara olika"},
	{"Re-enter new prompt: ", "Ange nytt {0} igen: "},
	{"They don't match; try again", "De matchar inte. F\u00f6rs\u00f6k p\u00e5 nytt"},
	{"Enter prompt alias name:  ", "Ange {0}-aliasnamn:  "},
	{"Enter alias name:  ", "Ange aliasnamn:  "},
	{"\t(RETURN if same as for <otherAlias>)",
		"\t(RETURN om det \u00e4r det samma som f\u00f6r <{0}>)"},
	{"*PATTERN* printX509Cert",
		"\u00c4gare: {0}\nUtf\u00e4rdare: {1}\nSerienummer: {2}\nGiltigt fr\u00e5n: {3} till: {4}\nCertifikatsfingeravtryck:\n\t MD5:  {5}\n\t SHA1: {6}"},
	{"What is your first and last name?",
		"Vad heter du i f\u00f6r- och efternamn?"},
	{"What is the name of your organizational unit?",
		"Vad heter din avdelning inom organisationen?"},
	{"What is the name of your organization?",
		"Vad heter din organisation?"},
	{"What is the name of your City or Locality?",
		"Vad heter din ort eller plats?"},
	{"What is the name of your State or Province?",
		"Vad heter ditt land eller din provins?"},
	{"What is the two-letter country code for this unit?",
		"Vilken \u00e4r den tv\u00e5st\u00e4lliga landskoden?"},
	{"Is <name> correct?", "\u00c4r {0} korrekt?"},
	{"no", "nej"},
	{"yes", "ja"},
	{"y", "j"},
	{"  [defaultValue]:  ", "  [{0}]:  "},
	{"Alias <alias> has no (private) key",
		"Aliaset <{0}> saknar (privat) nyckel"},
	{"Recovered key is not a private key",
		"Den \u00e5terst\u00e4llda nyckeln \u00e4r inte n\u00e5gon privat nyckel"},
	{"*****************  WARNING WARNING WARNING  *****************",
	    "*****************  VARNING VARNING VARNING  *****************"},
	{"* The integrity of the information stored in your keystore  *",
	    "* Integriteten betr\u00e4ffande den information som lagras i keystore-filen  *"},
	{"* has NOT been verified!  In order to verify its integrity, *",
	    "* har INTE verifierats!  Om du vill verifiera dess integritet, *"},
	{"* you must provide your keystore password.                  *",
	    "* m\u00e5ste du tillhandah\u00e5lla ditt keystore-l\u00f6senord.                  *"},
	{"Certificate reply does not contain public key for <alias>",
		"Certifikatsvaret inneh\u00e5ller inte n\u00e5gon offentlig nyckel f\u00f6r <{0}>"},
	{"Incomplete certificate chain in reply",
		"Ofullst\u00e4ndig certifikatskedja i svaret"},
	{"Certificate chain in reply does not verify: ",
		"Certifikatskedjan i svaret g\u00e5r inte att verifiera: "},
	{"Top-level certificate in reply:\n",
		"Toppniv\u00e5certifikatet i svaret:\n"},
	{"... is not trusted. ", "... \u00e4r inte betrott. "},
	{"Install reply anyway? [no]:  ", "Vill du installera svaret \u00e4nd\u00e5? [nej]:  "},
	{"NO", "NEJ"},
	{"Public keys in reply and keystore don't match",
		"De offentliga nycklarna i svaret och keystore-filen matchar inte varandra"},
	{"Certificate reply and certificate in keystore are identical",
		"Certifikatssvaret och certifikatet i keystore-filen \u00e4r identiska"},
	{"Failed to establish chain from reply",
		"Det gick inte att uppr\u00e4tta n\u00e5gon kedja ur svaret"},
	{"n", "n"},
	{"Wrong answer, try again", "Fel svar. F\u00f6rs\u00f6k p\u00e5 nytt."},
	{"keytool usage:\n", "nyckelverktyg:\n"},
	{"-certreq     [-v] [-protected]",
		"-certreq     [-v] [-protected]"},
	{"\t     [-alias <alias>] [-sigalg <sigalg>]",
		"\t     [-alias <alias>] [-sigalg <signaturalgoritm>]"},
	{"\t     [-file <csr_file>] [-keypass <keypass>]",
		"\t     [-file <csr_fil>] [-keypass <nyckell\u00f6senord>]"},
	{"\t     [-keystore <keystore>] [-storepass <storepass>]",
		"\t     [-keystore <keystore>] [-storepass <lagringsl\u00f6senord>]"},
	{"\t     [-storetype <storetype>] [-providerName <name>]",
		"\t     [-storetype <lagringstyp>] [-providerName <namn>]"},
	{"\t     [-providerClass <provider_class_name> [-providerArg <arg>]] ...",
		"\t     [-providerClass <leverant\u00f6rsklassnamn> [-providerArg <argument>]] ..."},
	{"-delete      [-v] [-protected] -alias <alias>",
		"-delete      [-v] [-protected] -alias <alias>"},
	{"-export      [-v] [-rfc] [-protected]",
		"-export      [-v] [-rfc] [-protected]"},
	{"\t     [-alias <alias>] [-file <cert_file>]",
		"\t     [-alias <alias>] [-file <certifikatsfil>]"},
	{"-genkey      [-v] [-protected]",
		"-genkey      [-v] [-protected]"},
	{"\t     [-alias <alias>]", "\t     [-alias <alias>]"},
	{"\t     [-keyalg <keyalg>] [-keysize <keysize>]",
		"\t     [-keyalg <nyckelalgoritm>] [-keysize <nyckelstorlek>]"},
	{"\t     [-sigalg <sigalg>] [-dname <dname>]",
		"\t     [-sigalg <signaturalgoritm>] [-dname <dnamn>]"},
	{"\t     [-validity <valDays>] [-keypass <keypass>]",
		"\t     [-validity <dagar>] [-keypass <nyckell\u00f6senord>]"},
	{"-help", "-help"},
	{"-identitydb  [-v] [-protected]",
		"-identitydb  [-v] [-protected]"},
	{"\t     [-file <idb_file>]",
		"\t     [-file <idb_file>]"},
	{"-import      [-v] [-noprompt] [-trustcacerts] [-protected]",
		"-import      [-v] [-noprompt] [-trustcacerts] [-protected]"},
	{"\t     [-file <cert_file>] [-keypass <keypass>]",
		"\t     [-file <certifikatsfil>] [-keypass <nyckell\u00f6senord>]"},
	{"-keyclone    [-v] [-protected]",
		"-keyclone    [-v] [-protected]"},
	{"\t     [-alias <alias>] -dest <dest_alias>",
		"\t     [-alias <alias>] -dest <dest_alias>"},
	{"\t     [-keypass <keypass>] [-new <new_keypass>]",
		"\t     [-keypass <nyckell\u00f6senord>] [-new <nytt_nyckell\u00f6senord>]"},
	{"-keypasswd   [-v] [-alias <alias>]",
		"-keypasswd   [-v] [-alias <alias>]"},
	{"\t     [-keypass <old_keypass>] [-new <new_keypass>]",
		"\t     [-keypass <gammalt_nyckell\u00f6senord>] [-new <nytt_nyckell\u00f6senord>]"},
	{"-list        [-v | -rfc] [-protected]",
		"-list        [-v | -rfc] [-protected]"},
	{"\t     [-alias <alias>]", "\t     [-alias <alias>]"},
	{"-printcert   [-v] [-file <cert_file>]",
		"-printcert   [-v] [-file <certifikatsfil>]"},
	{"-selfcert    [-v] [-protected]",
		"-selfcert    [-v] [-protected]"},
	{"\t     [-dname <dname>] [-validity <valDays>]",
		"\t     [-dname <dnamn>] [-validity <dagar>]"},
	{"\t     [-keypass <keypass>] [-sigalg <sigalg>]",
		"\t     [-keypass <nyckell\u00f6senord>] [-sigalg <signaturalgoritm>]"},
	{"-storepasswd [-v] [-new <new_storepass>]",
		"-storepasswd [-v] [-new <nytt_lagringsl\u00f6senord>]"},

	// policytool
	{"Warning: A public key for alias 'signers[i]' does not exist.",
		"Varning: Det finns inte n\u00e5gon offentlig nyckel f\u00f6r aliaset {0}."},
	{"Warning: Class not found: ",
		"Varning: Det g\u00e5r inte att hitta klassen: "},
	{"Policy File opened successfully",
		"Policyfilen har \u00f6ppnats"},
	{"null Keystore name", "nullkeystore-namn"},
	{"Warning: Unable to open Keystore: ",
		"Varning: Det g\u00e5r inte att \u00f6ppna keystore-filen: "},
	{"Illegal option: ", "Ogiltigt alternativ: "},
	{"Usage: policytool [options]", "G\u00f6r s\u00e5 h\u00e4r: policytool [alternativ]"},
	{"  [-file <file>]    policy file location",
		"  [-file <fil>]    policyfilens plats"},
	{"New", "Nytt"},
	{"Open", "\u00d6ppna"},
	{"Save", "Spara"},
	{"Save As", "Spara som"},
	{"View Warning Log", "Visa varningslogg"},
	{"Exit", "Avsluta"},
	{"Add Policy Entry", "L\u00e4gg till policypost"},
	{"Edit Policy Entry", "Redigera policypost"},
	{"Remove Policy Entry", "Ta bort policypost"},
	{"Change KeyStore", "\u00c4ndra KeyStore"},
	{"Add Public Key Alias", "L\u00e4gg till offentligt nyckelalias"},
	{"Remove Public Key Alias", "Ta bort offentligt nyckelalias"},
	{"File", "Arkiv"},
	{"Edit", "Redigera"},
	{"Policy File:", "Policyfil:"},
	{"Keystore:", "Keystore-fil:"},
	{"Error parsing policy file policyFile: pppe.getMessage()",
		"Det uppstod ett fel vid analys av policyfilen {0}: {1}"},
	{"Could not find Policy File: ", "Det g\u00e5r inte att hitta policyfilen: "},
	{"Policy Tool", "Policyverktyg"},
	{"Errors have occurred while opening the policy configuration.  View the Warning Log for more information.",
		"Det uppstod ett fel n\u00e4r policykonfigurationen skulle \u00f6ppnas.  Visa varningsloggen med ytterligare information."},
	{"Error", "Fel"},
	{"OK", "OK"},
	{"Status", "Status"},
	{"Warning", "Varning"},
	{"Permission:                                                       ",
		"Beh\u00f6righet:                                                       "},
	{"Target Name:                                                    ",
		"M\u00e5lets namn:                                                    "},
	{"library name", "biblioteksnamn"},
	{"package name", "paketnamn"},
	{"property name", "egenskapsnamn"},
	{"provider name", "leverant\u00f6rsnamn"},
	{"Actions:                                                             ",
		"Funktioner:                                                             "},
	{"OK to overwrite existing file filename?",
		"Ska den befintliga filen {0} skrivas \u00f6ver?"},
	{"Cancel", "Avbryt"},
	{"CodeBase:", "CodeBase:"},
	{"SignedBy:", "SignedBy:"},
	{"  Add Permission", "  L\u00e4gg till beh\u00f6righet"},
	{"  Edit Permission", "  Redigera beh\u00f6righet"},
	{"Remove Permission", "Ta bort beh\u00f6righet"},
	{"Done", "Klar"},
	{"New KeyStore URL:", "Ny KeyStore-adress:"},
	{"New KeyStore Type:", "Ny KeyStore-typ:"},
	{"Permissions", "Beh\u00f6righet"},
	{"  Edit Permission:", "  Redigera beh\u00f6righet:"},
	{"  Add New Permission:", "  L\u00e4gg till ny beh\u00f6righet:"},
	{"Signed By:", "Signerad av:"},
	{"Permission and Target Name must have a value",
		"Beh\u00f6righet och m\u00e5lnamn m\u00e5ste ha ett v\u00e4rde"},
	{"Remove this Policy Entry?", "Vill du ta bort den h\u00e4r policyposten?"},
	{"Overwrite File", "Skriva \u00f6ver fil"},
	{"Policy successfully written to filename",
		"Policy har skrivits till {0}"},
	{"null filename", "nullfilnamn"},
	{"filename not found", "{0} finns inte"},
	{"     Save changes?", "     Vill du spara \u00e4ndringarna?"},
	{"Yes", "Ja"},
	{"No", "Nej"},
	{"Error: Could not open policy file, filename, because of parsing error: pppe.getMessage()",
		"Fel: Det gick inte att \u00f6ppna policyfilen {0} p\u00e5 grund av analysfel: {1}"},
	{"Permission could not be mapped to an appropriate class",
		"Beh\u00f6righeten kunde inte h\u00e4nf\u00f6ras till n\u00e5gon l\u00e4mplig klass"},
	{"Policy Entry", "Policyfel"},
	{"Save Changes", "Vill du spara \u00e4ndringarna?"},
	{"No Policy Entry selected", "N\u00e5gon policypost har inte markerats"},
	{"Keystore", "Keystore"},
	{"KeyStore URL must have a valid value",
		"KeyStore-adressen m\u00e5ste ha ett giltigt v\u00e4rde"},
	{"Invalid value for Actions", "Ogiltigt v\u00e4rde f\u00f6r Actions"},
	{"No permission selected", "N\u00e5gon beh\u00f6righet har inte markerats"},
	{"Warning: Invalid argument(s) for constructor: ",
		"Varning: Ogiltigt/ogiltiga argument f\u00f6r konstruktion: "},
	{"Add Principal", "L\u00e4gg till principal"},
	{"Edit Principal", "Redigera principal"},
	{"Remove Principal", "Ta bort principal"},
	{"Principal Type:", "Principaltyp:"},
        {"Principal Name:", "Principalnamn:"},
	{"Illegal Principal Type", "Ogiltig principaltyp"},
	{"No principal selected", "Ingen principal har markerats"},
	{"Principals:", "Principaler:"},
	{"Principals", "Principaler"},
	{"  Add New Principal:", "  L\u00e4gg till ny principal:"},
	{"  Edit Principal:", "  Redigera principal:"},
	{"name", "namn"},
	{"Cannot Specify Principal with a Wildcard Class without a Wildcard Name",
	    "Det g\u00e5r inte att specificera principal med wildcard-klass utan wildcard-namn"},
	{"Cannot Specify Principal without a Class",
	    "Det g\u00e5r inte att specificera principal utan klass"},

        {"Cannot Specify Principal without a Name",
            "Det g\u00e5r inte att specificera principal utan namn"},

	// javax.security.auth.PrivateCredentialPermission
	{"invalid null input(s)", "ogiltiga null-indata"},
	{"actions can only be 'read'", "funktioner kan endast 'l\u00e4sas'"},
	{"permission name [name] syntax invalid: ",
		"syntaxen f\u00f6r beh\u00f6righetsnamnet [{0}] \u00e4r ogiltig: "},
	{"Credential Class not followed by a Principal Class and Name",
		"Kreditivklassen f\u00f6ljs inte av principalklass eller principalnamn"},
	{"Principal Class not followed by a Principal Name",
		"Principalklassen f\u00f6ljs inte av n\u00e5got principalnamn"},
	{"Principal Name must be surrounded by quotes",
		"Principalnamnet m\u00e5ste anges inom citattecken"},
	{"Principal Name missing end quote",
		"Principalnamnet saknar avslutande citattecken"},
	{"PrivateCredentialPermission Principal Class can not be a wildcard (*) value if Principal Name is not a wildcard (*) value",
		"V\u00e4rdet f\u00f6r principalklassen PrivateCredentialPermission kan inte ha n\u00e5got jokertecken (*) om principalnamnet inte anges med jokertecken (*)"},
	{"CredOwner:\n\tPrincipal Class = class\n\tPrincipal Name = name",
		"CredOwner:\n\tPrincipalklass = {0}\n\tPrincipalnamn = {1}"},

	// javax.security.auth.x500
	{"provided null name", "gav null-namn"},

	// javax.security.auth.Subject
	{"invalid null AccessControlContext provided",
		"ogiltigt null-AccessControlContext"},
	{"invalid null action provided", "ogiltig null-funktion"},
	{"invalid null Class provided", "ogiltig null-klass"},
	{"Subject:\n", "\u00c4rende:\n"},
	{"\tPrincipal: ", "\tPrincipal: "},
	{"\tPublic Credential: ", "\tOffentligt kreditiv: "},
	{"\tPrivate Credentials inaccessible\n",
		"\tPrivata kreditiv \u00e4r otillg\u00e4ngliga\n"},
	{"\tPrivate Credential: ", "\tPrivata kreditiv: "},
	{"\tPrivate Credential inaccessible\n",
		"\tPrivata kreditiv \u00e4r otillg\u00e4ngliga\n"},
	{"Subject is read-only", "\u00c4mnet \u00e4r skrivskyddat"},
	{"attempting to add an object which is not an instance of java.security.Principal to a Subject's Principal Set",
		"f\u00f6rs\u00f6k att l\u00e4gga till ett objekt som inte \u00e4r en f\u00f6rekomst av java.security.Principal till en principalupps\u00e4ttning"},
	{"attempting to add an object which is not an instance of class",
		"f\u00f6rs\u00f6ker l\u00e4gga till ett objekt som inte \u00e4r en f\u00f6rekomst av {0}"},

	// javax.security.auth.login.AppConfigurationEntry
	{"LoginModuleControlFlag: ", "LoginModuleControlFlag: "},

	// javax.security.auth.login.LoginContext
	{"Invalid null input: name", "Ogiltiga null-indata: namn"},
	{"No LoginModules configured for name",
	 "Inga inloggningsmoduler har konfigurerats f\u00f6r {0}"},
	{"invalid null Subject provided", "ogiltigt null-Subject"},
	{"invalid null CallbackHandler provided",
		"ogiltig null-CallbackHandler"},
	{"null subject - logout called before login",
		"null-subject - utloggning anropades f\u00f6re inloggning"},
	{"unable to instantiate LoginModule, module, because it does not provide a no-argument constructor",
		"det g\u00e5r inta att representera LoginModule, {0}, eftersom den inte tillhandah\u00e5ller n\u00e5gon argumentfri konstruktion"},
	{"unable to instantiate LoginModule",
		"det g\u00e5r inte att representera LoginModule"},
	{"unable to find LoginModule class: ",
		"det g\u00e5r inte att hitta LoginModule-klassen: "},
	{"unable to access LoginModule: ",
		"det g\u00e5r inte att komma \u00e5t LoginModule: "},
	{"Login Failure: all modules ignored",
		"Inloggningsfel: alla moduler ignoreras"},

	// sun.security.provider.PolicyFile

	{"java.security.policy: error parsing policy:\n\tmessage",
		"java.security.policy: fel vid analys av {0}:\n\t{1}"},
	{"java.security.policy: error adding Permission, perm:\n\tmessage",
		"java.security.policy: fel vid till\u00e4gg av beh\u00f6righet, {0}:\n\t{1}"},
	{"java.security.policy: error adding Entry:\n\tmessage",
		"java.security.policy: fel vid till\u00e4gg av post:\n\t{0}"},
	{"alias name not provided (pe.name)", "aliasnamn ej angivet ({0})"},
	{"unable to perform substitution on alias, suffix",
		"kan ej ers\u00e4tta aliasnamn, {0}"},
	{"substitution value, prefix, unsupported",
		"ers\u00e4ttningsv\u00e4rde, {0}, st\u00f6ds ej"},
	{"(", "("},
	{")", ")"},
	{"type can't be null","typen kan inte vara null"},

	// sun.security.provider.PolicyParser
	{"keystorePasswordURL can not be specified without also specifying keystore",
		"det g\u00e5r inte att ange keystorePasswordURL utan att ange keystore"},
	{"expected keystore type", "f\u00f6rv\u00e4ntad keystore-typ"},
	{"expected keystore provider", "keystore-leverant\u00f6r f\u00f6rv\u00e4ntades"},
	{"multiple Codebase expressions",
	        "flera Codebase-uttryck"},
        {"multiple SignedBy expressions","flera SignedBy-uttryck"},
	{"SignedBy has empty alias","SignedBy har ett tomt alias"},
	{"can not specify Principal with a wildcard class without a wildcard name",
		"Det g\u00e5r inte att specificera principal genom att ange jokertecken f\u00f6r klass utan att samtidigt ange jokertecken f\u00f6r namn"},
	{"expected codeBase or SignedBy or Principal",
		"f\u00f6rv\u00e4ntad codeBase eller SignedBy eller Principal"},
	{"expected permission entry", "f\u00f6rv\u00e4ntade beh\u00f6righetspost"},
	{"number ", "antal "},
	{"expected [expect], read [end of file]",
		"f\u00f6rv\u00e4ntade [{0}], l\u00e4ste [end of file]"},
	{"expected [;], read [end of file]",
		"f\u00f6rv\u00e4ntade [;], l\u00e4ste [end of file]"},
	{"line number: msg", "rad {0}: {1}"},
	{"line number: expected [expect], found [actual]",
		"rad {0}: f\u00f6rv\u00e4ntade [{1}], hittade [{2}]"},
	{"null principalClass or principalName",
		"null-principalClass eller -principalName"},

	// sun.security.pkcs11.SunPKCS11
	{"PKCS11 Token [providerName] Password: ",
		"PKCS11-pollett [{0}] L\u00f6senord: "},

	/* --- DEPRECATED --- */
	// javax.security.auth.Policy
	{"unable to instantiate Subject-based policy",
		"det g\u00e5r inte att representera Subject-baserad policy"}
    };


    /**
     * Returns the contents of this <code>ResourceBundle</code>.
     *
     * <p>
     *
     * @return the contents of this <code>ResourceBundle</code>.
     */
    public Object[][] getContents() {
	return contents;
    }
}
