#
# @(#)Makefile	1.8 10/04/01
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building SNMP runtime support for
# implementation specific J2SE out of the box management support.
#

BUILDDIR = ../../../..
PACKAGE = com.sun.jmx.snmp
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/jmx/snmp

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

