#
# @(#)Makefile	1.19 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the SwingApplet demo.
#

BUILDDIR = ../../..
DEMONAME = SwingApplet
include ../DemoSwing.gmk
