/*
 * @(#)dcPRException.c	1.13 10/03/23
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPRException.c	Tue Nov 18 16:16:16 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

char*	dcPRException[] = {
	"sun/dc/pr/PRException",
	"setOutputArea: alpha coordinate out of bounds",
	"writeAlpha: alpha destination array too short",
	""};
