#   @(#)Makefile	1.4 08/13/05
#
# Build the logging files
#

BUILDDIR = ../../../../../..
PACKAGE = com.sun.corba.se.spi.logging
PRODUCT = logging

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_spi_logging.jmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
