#
# @(#)Makefile	1.11 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build Java2D demos/Colors sources
#

BUILDDIR = ../../../../..
DEMONAME = demos/Colors
PKGPATH = $(DEMODST)/$(DEMONAME)
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(PKGPATH)/BullsEye.java \
             $(PKGPATH)/ColorConvert.java \
             $(PKGPATH)/Rotator3D.java


DEMO_dirs  = $(DEMODST) \
             $(DEMODST)/java2d/demos \
             $(DEMODST)/java2d/demos/Colors

include ../../DemoJava2D.gmk
