#
# Copyright (c) 1998, 2008, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#  
#

Variant=compiler2
!include local.make
AdditionalTargets=incls/ad_$(Platform_arch_model).cpp incls/dfa_$(Platform_arch_model).cpp

!include $(HOTSPOTWORKSPACE)/make/windows/projectfiles/common/Makefile
