#
# @(#)Makefile	1.8 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../../../..

PACKAGE = com.sun.corba.se.connection
PRODUCT = sun

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#

include FILES_java.gmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
