#
# @(#)Makefile	1.11 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

# makefile for building JPEG classes

BUILDDIR = ../../..
PACKAGE = com.sun.image.codec.jpeg
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = com/sun/image/codec/jpeg

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

