#
# @(#)Makefile	1.25 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../../../../..
PACKAGE = com.sun.corba.se.spi.activation
PRODUCT = org

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_spi_activation.jmk

FILES_java=$(com_sun_corba_se_spi_activation_java)

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
