#
# @(#)Makefile	1.16 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
# Makefile for building JAAS  Framework and all 
# modules (common and platform specific)
#

BUILDDIR = ../../..
PACKAGE = javax.security.auth
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = javax/security/auth

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
