#!/bin/sh
#
# @(#)runnit	1.11 99/07/12

if [ -z "${JAVA_HOME}" ] ; then
    if [ -d /usr/local/java/jdk1.1.7/solaris ] ; then
        JAVA_HOME=/usr/local/java/jdk1.1.7/solaris
	CLASSPATH=.:/usr/local/java/jdk1.1.7/solaris/lib/classes.zip
	export CLASSPATH
    else
        echo "JAVA_HOME environment variable not set." 1>&2 
        exit 1
    fi
fi

# Compute an absolute pathname here because Class.getResource()
# fails if $CLASSPATH contains "../".
if [ -d ../../1.1_demo ] ; then
    SWING_HOME=`(cd ../../1.1_classes; pwd)`
    SWING_JARS=${SWING_HOME}
else
    SWING_HOME=`(cd ../../; pwd)`
    SWING_JARS=${SWING_HOME}/swing.jar:${SWING_HOME}/motif.jar:${SWING_HOME}/multi.jar:${SWING_HOME}/windows.jar
fi

if [  -z "${JDBCHOME}" ] ; then
    echo "JDBCHOME environment variable not set." 1>&2 
    exit 1
fi

SWING_CLASSES=.:classes:${SWING_JARS}:${BUILD_JARS}:TableExample.jar
if [ -z "$CLASSPATH" ] ; then
    CLASSPATH="${JDBCHOME}":"${SWING_CLASSES}":${JAVA_HOME}/lib/classes.zip
else
    CLASSPATH="${JDBCHOME}":"${SWING_CLASSES}:$CLASSPATH"
fi

CMD="${JAVA_HOME}/bin/java -classpath ${CLASSPATH} TableExample"

echo ${CMD}
${CMD}
