#
# @(#)Makefile	1.13 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building the Java 2D Demo subdirectories
#

BUILDDIR = ../../../..
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = Arcs_Curves Clipping Colors Composite Fonts Images Mix Lines Paint Paths Transforms
all build clean clobber::
	$(SUBDIRS-loop)

