/*
 * @(#)BackEnd.java	1.8 10/03/23
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package sun.tools.javazic;

/**
 * <code>BackEnd</code> is an abstract base class for a back-end of compiling
 * Olson's zoneinfo database and generating Java zoneinfo database.
 *
 * @since 1.4
 */          
abstract class BackEnd {

    /**
     * Receives each zone's TimeZone information which was created by 
     * {@link Zoneinfo#parse} in class <code>Zoneinfo</code>,
     * and processes it.
     *
     * @param tz Timezone object for each zone
     * @return 0 if no error occurred, otherwise 1.
     */
    abstract int processZoneinfo(Timezone tz);

    /**
     * Receives whole information which is generated by JavaZic's front-end
     * in the form of Mapping object and generates all Java zone information
     * files.
     *
     * @param m Mappings object which is generated by
     *          {@link Main#compile() Main.compile()}.
     * @return 0 if no error occurred, otherwise 1.
     */
    abstract int generateSrc(Mappings m);

    /**
     * Decides which backend class should be used and returns its instance.
     * @return an instance of backend class
     */
    static BackEnd getBackEnd() {
	if (Zoneinfo.isYearForTimeZoneDataSpecified) {
	    return new Simple();
	} else if (Main.outputSrc) {
	    return new GenSrc();
	} else if (Main.outputDoc) {
	    return new GenDoc();
	} else {
	    return new Gen();
	}
    }
}
