#
# @(#)Makefile	1.9 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build applet demo.
#

BUILDDIR = ../../..
DEMONAME = GraphLayout
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(DEMODST)/Graph.java

DEMO_dirs  = $(DEMODST) $(DEMODST)/audio

DEMO_other = $(DEMODST)/example1.html \
             $(DEMODST)/example2.html \
             $(DEMODST)/example3.html \
             $(DEMODST)/example4.html \
             $(DEMODST)/audio/computer.au \
             $(DEMODST)/audio/drip.au \
             $(DEMODST)/audio/gong.au

include ../DemoApplets.gmk

