#
# @(#)Makefile	1.20 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building the JDWP generator
#

BUILDDIR = ../..
PACKAGE = com.sun.tools.jdwpgen
PRODUCT = jpda
include $(BUILDDIR)/common/Defs.gmk

#
# Packages to find sources to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/tools/jdwpgen

#
# Rules.
#

include $(BUILDDIR)/common/Classes.gmk
