#
# @(#)Makefile	1.5 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building apache implementations
#

BUILDDIR = ../../..
PRODUCT = org
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS =  apache
all build clean clobber::
	$(SUBDIRS-loop)

