#
# @(#)Makefile	1.3 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building packages under org.jcp
#

BUILDDIR = ../..
PACKAGE = org.jcp
PRODUCT = jcp
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = org/jcp

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
