#
# @(#)Makefile	1.3 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../..
PACKAGE = com.sun.net.httpserver
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/net/httpserver sun/net/httpserver

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
