#
# @(#)Makefile	1.3 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=minst
USES_AGENT_UTIL=true
USES_CRW=true

# Source files
FILES_c = $(CTARGDIR)minst.c

# Class files needed 
FILES_classes = Minst.class

# Include basic demo template makefile
include ../Demo.gmk

