#
# @(#)Makefile	1.8 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building SNMP MIB instrumentation
#

BUILDDIR = ../../..
PACKAGE = sun.management.snmp
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = sun/management/snmp

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

