# @(#)Makefile	1.3 05/08/13
#
# Build the copyobject files
#

BUILDDIR = ../../../../../..
PACKAGE = com.sun.corba.se.spi.copyobject
PRODUCT = copyobject

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_spi_copyobject.jmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
