/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Tue Sep 18 00:16:54 PDT 2007 ----! */


package sun.plugin2.os.windows;

import java.nio.*;

import sun.plugin2.gluegen.runtime.*;

import java.nio.*;

class FLASHWINFO32 extends FLASHWINFO {
  public static int size() {
    return 20;
  }

  FLASHWINFO32(ByteBuffer buf) {
    super(buf);
  }


  public FLASHWINFO cbSize(int val) {
    accessor.setIntAt(0, val);
    return this;
  }

  public int cbSize() {
    return accessor.getIntAt(0);
  }

  public FLASHWINFO hwnd(long val) {
    accessor.setIntAt(1, (int) val);
    return this;
  }

  public long hwnd() {
    return (long) accessor.getIntAt(1);
  }

  public FLASHWINFO dwFlags(int val) {
    accessor.setIntAt(2, val);
    return this;
  }

  public int dwFlags() {
    return accessor.getIntAt(2);
  }

  public FLASHWINFO uCount(int val) {
    accessor.setIntAt(3, val);
    return this;
  }

  public int uCount() {
    return accessor.getIntAt(3);
  }

  public FLASHWINFO dwTimeout(int val) {
    accessor.setIntAt(4, val);
    return this;
  }

  public int dwTimeout() {
    return accessor.getIntAt(4);
  }
}
