/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Tue Sep 18 00:16:54 PDT 2007 ----! */


package sun.plugin2.os.windows;

import java.nio.*;

import sun.plugin2.gluegen.runtime.*;

import java.nio.*;

public abstract class FLASHWINFO {
  StructAccessor accessor;

  public static int size() {
    if (CPU.is32Bit()) {
      return FLASHWINFO32.size();
    } else {
      return FLASHWINFO64.size();
    }
  }

  public static FLASHWINFO create() {
    return create(BufferFactory.newDirectByteBuffer(size()));
  }

  public static FLASHWINFO create(ByteBuffer buf) {
    if (CPU.is32Bit()) {
      return new FLASHWINFO32(buf);
    } else {
      return new FLASHWINFO64(buf);
    }
  }

  FLASHWINFO(ByteBuffer buf) {
    accessor = new StructAccessor(buf);
  }

  public ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  public abstract FLASHWINFO cbSize(int val);

  public abstract int cbSize();

  public abstract FLASHWINFO hwnd(long val);

  public abstract long hwnd();

  public abstract FLASHWINFO dwFlags(int val);

  public abstract int dwFlags();

  public abstract FLASHWINFO uCount(int val);

  public abstract int uCount();

  public abstract FLASHWINFO dwTimeout(int val);

  public abstract int dwTimeout();
}
