/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Sat Sep 29 08:12:13 PDT 2007 ----! */


package sun.plugin2.os.windows;

import java.nio.*;

import sun.plugin2.gluegen.runtime.*;

import java.nio.*;

class OSVERSIONINFOA64 extends OSVERSIONINFOA {
  public static int size() {
    return 148;
  }

  OSVERSIONINFOA64(ByteBuffer buf) {
    super(buf);
  }


  public OSVERSIONINFOA dwOSVersionInfoSize(int val) {
    accessor.setIntAt(0, val);
    return this;
  }

  public int dwOSVersionInfoSize() {
    return accessor.getIntAt(0);
  }

  public OSVERSIONINFOA dwMajorVersion(int val) {
    accessor.setIntAt(1, val);
    return this;
  }

  public int dwMajorVersion() {
    return accessor.getIntAt(1);
  }

  public OSVERSIONINFOA dwMinorVersion(int val) {
    accessor.setIntAt(2, val);
    return this;
  }

  public int dwMinorVersion() {
    return accessor.getIntAt(2);
  }

  public OSVERSIONINFOA dwBuildNumber(int val) {
    accessor.setIntAt(3, val);
    return this;
  }

  public int dwBuildNumber() {
    return accessor.getIntAt(3);
  }

  public OSVERSIONINFOA dwPlatformId(int val) {
    accessor.setIntAt(4, val);
    return this;
  }

  public int dwPlatformId() {
    return accessor.getIntAt(4);
  }
}
