/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Sun Feb 03 07:50:40 PST 2008 ----! */


package sun.plugin2.os.windows;

import java.nio.*;

import sun.plugin2.gluegen.runtime.*;

import java.nio.*;

class OVERLAPPED32 extends OVERLAPPED {
  public static int size() {
    return 0;
  }

  OVERLAPPED32(ByteBuffer buf) {
    super(buf);
  }

}
