/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Sun Jun 17 23:51:10 PDT 2007 ----! */


package sun.plugin2.os.windows;

import java.nio.*;

import sun.plugin2.gluegen.runtime.*;

import java.nio.*;

public abstract class SECURITY_ATTRIBUTES {
  StructAccessor accessor;

  public static int size() {
    if (CPU.is32Bit()) {
      return SECURITY_ATTRIBUTES32.size();
    } else {
      return SECURITY_ATTRIBUTES64.size();
    }
  }

  public static SECURITY_ATTRIBUTES create() {
    return create(BufferFactory.newDirectByteBuffer(size()));
  }

  public static SECURITY_ATTRIBUTES create(ByteBuffer buf) {
    if (CPU.is32Bit()) {
      return new SECURITY_ATTRIBUTES32(buf);
    } else {
      return new SECURITY_ATTRIBUTES64(buf);
    }
  }

  SECURITY_ATTRIBUTES(ByteBuffer buf) {
    accessor = new StructAccessor(buf);
  }

  public ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  public abstract SECURITY_ATTRIBUTES nLength(int val);

  public abstract int nLength();

  public abstract SECURITY_ATTRIBUTES bInheritHandle(int val);

  public abstract int bInheritHandle();
}
