/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Sun Jun 17 23:51:10 PDT 2007 ----! */


package sun.plugin2.os.windows;

import java.nio.*;

import sun.plugin2.gluegen.runtime.*;

import java.nio.*;

class SECURITY_ATTRIBUTES32 extends SECURITY_ATTRIBUTES {
  public static int size() {
    return 12;
  }

  SECURITY_ATTRIBUTES32(ByteBuffer buf) {
    super(buf);
  }


  public SECURITY_ATTRIBUTES nLength(int val) {
    accessor.setIntAt(0, val);
    return this;
  }

  public int nLength() {
    return accessor.getIntAt(0);
  }

  public SECURITY_ATTRIBUTES bInheritHandle(int val) {
    accessor.setIntAt(2, val);
    return this;
  }

  public int bInheritHandle() {
    return accessor.getIntAt(2);
  }
}
