#
# @(#)Makefile	1.2 10/03/23 16:59:10
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=jconsole-plugin

# Class files needed 
FILES_classes = com/sun/demo/scripting/jconsole/ScriptJConsolePlugin.class \
       com/sun/demo/scripting/jconsole/ScriptJConsolePlugin.class \
       com/sun/demo/scripting/jconsole/ScriptShellPanel.class \
       com/sun/demo/scripting/jconsole/EditableAtEndDocument.class \


# Include basic demo template makefile
include ../Demo.gmk

