#
# @(#)Makefile	1.15 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building the GUI debugger 
#

BUILDDIR = ../..
PACKAGE = com.sun.tools.example.debug.gui
PRODUCT = jpda
include $(BUILDDIR)/common/Defs.gmk

#
# Java Files to compile are found automatically.
#
AUTO_FILES_JAVA_DIRS = com/sun/tools/example/debug/gui

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk
