/* !---- DO NOT EDIT: This file autogenerated by com\sun\gluegen\JavaEmitter.java on Sat Sep 29 08:12:13 PDT 2007 ----! */


package sun.plugin2.os.windows;

import java.nio.*;

import sun.plugin2.gluegen.runtime.*;

import java.nio.*;

public abstract class OSVERSIONINFOA {
  StructAccessor accessor;

  public static int size() {
    if (CPU.is32Bit()) {
      return OSVERSIONINFOA32.size();
    } else {
      return OSVERSIONINFOA64.size();
    }
  }

  public static OSVERSIONINFOA create() {
    return create(BufferFactory.newDirectByteBuffer(size()));
  }

  public static OSVERSIONINFOA create(ByteBuffer buf) {
    if (CPU.is32Bit()) {
      return new OSVERSIONINFOA32(buf);
    } else {
      return new OSVERSIONINFOA64(buf);
    }
  }

  OSVERSIONINFOA(ByteBuffer buf) {
    accessor = new StructAccessor(buf);
  }

  public ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  public abstract OSVERSIONINFOA dwOSVersionInfoSize(int val);

  public abstract int dwOSVersionInfoSize();

  public abstract OSVERSIONINFOA dwMajorVersion(int val);

  public abstract int dwMajorVersion();

  public abstract OSVERSIONINFOA dwMinorVersion(int val);

  public abstract int dwMinorVersion();

  public abstract OSVERSIONINFOA dwBuildNumber(int val);

  public abstract int dwBuildNumber();

  public abstract OSVERSIONINFOA dwPlatformId(int val);

  public abstract int dwPlatformId();
}
