#
# @(#)Makefile	1.9 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the SwingSet2 demo.
#

BUILDDIR = ../../..
DEMONAME = SwingSet2
SPLASH = resources/images/splash.png
include ../DemoSwing.gmk
