#
# @(#)Makefile	1.3 03/08/13
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building RMI SSL socket factories 
#

BUILDDIR = ../../..
PACKAGE = javax.rmi.ssl
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = javax/rmi/ssl

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

