#
# @(#)Makefile	1.10 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build applet demo.
#

BUILDDIR = ../../..
DEMONAME = Animator
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(DEMODST)/Animator.java

DEMO_dirs  = $(DEMODST) \
             $(DEMODST)/audio \
             $(DEMODST)/images \
             $(DEMODST)/images/SimpleAnimation \
             $(DEMODST)/images/Beans

DEMO_other = $(DEMODST)/example1.html \
             $(DEMODST)/example2.html \
             $(DEMODST)/example3.html \
             $(DEMODST)/example4.html \
             $(DEMODST)/index.html \
             $(DEMODST)/audio/0.au \
             $(DEMODST)/audio/1.au \
             $(DEMODST)/audio/2.au \
             $(DEMODST)/audio/3.au \
             $(DEMODST)/audio/4.au \
             $(DEMODST)/audio/5.au \
             $(DEMODST)/audio/6.au \
             $(DEMODST)/audio/7.au \
             $(DEMODST)/audio/8.au \
             $(DEMODST)/audio/9.au \
             $(DEMODST)/audio/spacemusic.au \
             $(DEMODST)/images/SimpleAnimation/T1.gif \
             $(DEMODST)/images/SimpleAnimation/T2.gif \
             $(DEMODST)/images/Beans/T10.gif \
             $(DEMODST)/images/Beans/T9.gif \
             $(DEMODST)/images/Beans/T7.gif \
             $(DEMODST)/images/Beans/T3.gif \
             $(DEMODST)/images/Beans/T8.gif \
             $(DEMODST)/images/Beans/T6.gif \
             $(DEMODST)/images/Beans/T2.gif \
             $(DEMODST)/images/Beans/T1.gif \
             $(DEMODST)/images/Beans/T5.gif \
             $(DEMODST)/images/Beans/T4.gif \
             $(DEMODST)/images/loading-msg.gif

include ../DemoApplets.gmk

