#
# @(#)Makefile	1.51 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building sun.audio
#

BUILDDIR = ../..
PACKAGE = sun.audio
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = sun/audio

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

