#
# @(#)Makefile	1.23 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the Stylepad demo.
#

BUILDDIR = ../../..
DEMONAME = Stylepad
include ../DemoSwing.gmk
