# @(#)Makefile	1.2 05/08/13
                                                                                
BUILDDIR = ../../..
PACKAGE = com.sun.corba.se.impl.logging
PRODUCT = sun
                                                                                
include $(BUILDDIR)/common/Defs.gmk
                                                                                
#
# Files
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_impl_logging.jmk
FILES_java=$(com_sun_corba_se_impl_logging_java)
#
# Include
#
include $(BUILDDIR)/common/Classes.gmk

