// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !

package sun.awt.X11;

import sun.misc.Unsafe;

class XQueryTree {
	private static Unsafe unsafe = XlibWrapper.unsafe;
	private boolean __executed = false;
	private boolean __disposed = false;
	long _w;
	long root_ptr = unsafe.allocateMemory(Native.getLongSize());
	long parent_ptr = unsafe.allocateMemory(Native.getLongSize());
	long children_ptr = unsafe.allocateMemory(Native.getLongSize());
	long nchildren_ptr = unsafe.allocateMemory(Native.getIntSize());
	public XQueryTree(
		long w	)
	{
		set_w(w);
	}
	public int execute() {
		return execute(null);
	}
	public int execute(XToolkit.XErrorHandler errorHandler) {
		if (__disposed) {
		    throw new IllegalStateException("Disposed");
		}
		try {
			XToolkit.awtLock();
			if (__executed) {
			    throw new IllegalStateException("Already executed");
			}
			__executed = true;
			if (errorHandler != null) {
			    XToolkit.WITH_XERROR_HANDLER(errorHandler);
			}
			Native.putLong(children_ptr, 0);
			int status = 
			XlibWrapper.XQueryTree(XToolkit.getDisplay(), 
				get_w(),
				root_ptr,
				parent_ptr,
				children_ptr,
				nchildren_ptr			);
			if (errorHandler != null) {
			    XToolkit.RESTORE_XERROR_HANDLER();
			}
			return status;
		} finally {
		    XToolkit.awtUnlock();
		}
	}
	public boolean isExecuted() {
	    return __executed;
	}
	
	public boolean isDisposed() {
	    return __disposed;
	}
	public void finalize() {
            if (XlibWrapper.isBuildInternal && !__disposed) {
                System.err.println("WARNING: sun.awt.X11.XQueryTree not disposed till finalization!");
            }
	}
	public void dispose() {
		synchronized(XToolkit.getAWTLock()) {
		if (__disposed) {
		    return;
		}
		unsafe.freeMemory(root_ptr);
		unsafe.freeMemory(parent_ptr);
		if (__executed && get_children()!= 0) {
			XlibWrapper.XFree(get_children());
		}
		unsafe.freeMemory(children_ptr);
		unsafe.freeMemory(nchildren_ptr);
		__disposed = true;
		}
	}
	public long get_w() {
		if (__disposed) {
		    throw new IllegalStateException("Disposed");
		}
		if (!__executed) {
		    throw new IllegalStateException("Not executed");
		}
		return _w;
	}
	public void set_w(long data) {
		_w = data;
	}
	public long get_root() {
		if (__disposed) {
		    throw new IllegalStateException("Disposed");
		}
		if (!__executed) {
		    throw new IllegalStateException("Not executed");
		}
		return Native.getLong(root_ptr);
	}
	public void set_root(long data) {
		Native.putLong(root_ptr, data);
	}
	public long get_parent() {
		if (__disposed) {
		    throw new IllegalStateException("Disposed");
		}
		if (!__executed) {
		    throw new IllegalStateException("Not executed");
		}
		return Native.getLong(parent_ptr);
	}
	public void set_parent(long data) {
		Native.putLong(parent_ptr, data);
	}
	public long get_children() {
		if (__disposed) {
		    throw new IllegalStateException("Disposed");
		}
		if (!__executed) {
		    throw new IllegalStateException("Not executed");
		}
		return Native.getLong(children_ptr);
	}
	public void set_children(long data) {
		Native.putLong(children_ptr, data);
	}
	public int get_nchildren() {
		if (__disposed) {
		    throw new IllegalStateException("Disposed");
		}
		if (!__executed) {
		    throw new IllegalStateException("Not executed");
		}
		return Native.getInt(nchildren_ptr);
	}
	public void set_nchildren(int data) {
		Native.putInt(nchildren_ptr, data);
	}
}
