#
# @(#)Makefile	1.10 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building JNDI service provider toolkit
#

BUILDDIR = ../../../..
PACKAGE = com.sun.jndi.toolkit
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/jndi/toolkit

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
