#
#  @(#)Makefile	1.5 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
#  ORACLE PROPRIETARY/CONFIDENTIAL.  Use is subject to license terms.
#

BUILDDIR = ../../../..
PACKAGE = com.sun.security.sasl
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = com/sun/security/sasl

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
