#
# @(#)Makefile	1.3 10/03/23 16:59:35
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building Mozilla modules
#

BUILDDIR = ../..
PRODUCT = org
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS =  mozilla
all build clean clobber::
	$(SUBDIRS-loop)

