#
# @(#)Makefile	1.13 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building all of java
#

BUILDDIR = ..
PRODUCT = com
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = sun
all build clean clobber::
	$(SUBDIRS-loop)

