package org.omg.PortableServer;


/**
* org/omg/PortableServer/THREAD_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Friday, June 20, 2003 8:34:37 AM GMT
*/

public interface THREAD_POLICY_ID
{

  /**
	 * The value representing THREAD_POLICY_ID.
	 */
  public static final int value = (int)(16);
}
