#
# @(#)Makefile	1.4 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building demo jvmti classes
#

BUILDDIR = ../../../..
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = hprof
all build clean clobber::
	$(SUBDIRS-loop)

