#
# @(#)Makefile	1.19 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building the BDI interface
#

BUILDDIR = ../..
PACKAGE = com.sun.tools.example.debug.bdi
PRODUCT = jpda
include $(BUILDDIR)/common/Defs.gmk

# Where to look for sources
AUTO_FILES_JAVA_DIRS = \
    com/sun/tools/example/debug/bdi \
    com/sun/tools/example/debug/event

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk
