#
# @(#)Makefile	1.4 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=JTop
MAIN_CLASS_NAME=JTop

# Class files needed 
FILES_classes = JTop.class JTopPlugin.class

# Resource files
RESOURCE_files = META-INF/services/com.sun.tools.jconsole.JConsolePlugin

# Include basic demo template makefile
include ../Demo.gmk

