#
# @(#)Makefile	1.4 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=agent_util

# Just used to create demo directory, not a demo, just shared source

# Include basic demo template makefile
include ../Demo.gmk

