/*
 * @(#)dcPRError.h	1.11 03/12/19
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPRError.h	Tue Nov 18 16:16:12 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

#define	dcPRError_UNEX_setUsage	1
#define	dcPRError_UNEX_setFillMode	2
#define	dcPRError_UNEX_setPenDiameter	3
#define	dcPRError_UNEX_setPenT4	4
#define	dcPRError_UNEX_setPenDisplacement	5
#define	dcPRError_UNEX_setPenFitting	6
#define	dcPRError_UNEX_setCaps	7
#define	dcPRError_UNEX_setCorners	8
#define	dcPRError_UNEX_setDash	9
#define	dcPRError_UNEX_setDashT4	10
#define	dcPRError_UNEX_beginPath	11
#define	dcPRError_UNEX_beginSubpath	12
#define	dcPRError_UNEX_appendCubic	13
#define	dcPRError_UNEX_appendLine	14
#define	dcPRError_UNEX_appendQuadratic	15
#define	dcPRError_UNEX_closedSubpath	16
#define	dcPRError_UNEX_endPath	17
#define	dcPRError_UNEX_useProxy	18
#define	dcPRError_UNEX_setOutputConsumer	19
#define	dcPRError_UNEX_setOutputT6	20
#define	dcPRError_UNEX_getAlphaBox	21
#define	dcPRError_UNEX_setOutputArea	22
#define	dcPRError_UNEX_getTileState	23
#define	dcPRError_UNEX_writeAlpha	24
#define	dcPRError_UNEX_nextTile	25
#define	dcPRError_UNK_usage	26
#define	dcPRError_UNK_fillmode	27
#define	dcPRError_BAD_pendiam	28
#define	dcPRError_BAD_pent4	29
#define	dcPRError_BAD_pent4_singular	30
#define	dcPRError_BAD_penfit	31
#define	dcPRError_UNK_caps	32
#define	dcPRError_UNK_corners	33
#define	dcPRError_BAD_miterlimit	34
#define	dcPRError_BAD_dashpattern	35
#define	dcPRError_BAD_dasht4	36
#define	dcPRError_BAD_dasht4_singular	37
#define	dcPRError_BAD_pathbox	38
#define	dcPRError_BAD_outputt6	39
#define	dcPRError_BAD_outputt6_singular	40
#define	dcPRError_BAD_boxdest	41
#define	dcPRError_BAD_outputarea	42
#define	dcPRError_BAD_alphadest	43
extern char*   dcPRError[];
