/*
 * @(#)dcPRException.c	1.11 03/12/19
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPRException.c	Tue Nov 18 16:16:16 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

char*	dcPRException[] = {
	"sun/dc/pr/PRException",
	"setOutputArea: alpha coordinate out of bounds",
	"writeAlpha: alpha destination array too short",
	""};
