/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_deploy_association_utility_DesktopEntryFile */

#ifndef _Included_com_sun_deploy_association_utility_DesktopEntryFile
#define _Included_com_sun_deploy_association_utility_DesktopEntryFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_deploy_association_utility_DesktopEntryFile
 * Method:    gnome_vfs_read_file
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_deploy_association_utility_DesktopEntryFile_gnome_1vfs_1read_1file
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sun_deploy_association_utility_DesktopEntryFile
 * Method:    gnome_vfs_mkdir
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_deploy_association_utility_DesktopEntryFile_gnome_1vfs_1mkdir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sun_deploy_association_utility_DesktopEntryFile
 * Method:    gnome_vfs_file_exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_deploy_association_utility_DesktopEntryFile_gnome_1vfs_1file_1exists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sun_deploy_association_utility_DesktopEntryFile
 * Method:    gnome_vfs_write_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_com_sun_deploy_association_utility_DesktopEntryFile_gnome_1vfs_1write_1file
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_sun_deploy_association_utility_DesktopEntryFile
 * Method:    gnome_vfs_delete_file
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_deploy_association_utility_DesktopEntryFile_gnome_1vfs_1delete_1file
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sun_deploy_association_utility_DesktopEntryFile
 * Method:    ensure_load_gnome_vfs_lib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_deploy_association_utility_DesktopEntryFile_ensure_1load_1gnome_1vfs_1lib
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
