/*
 * @(#)config.h	1.6 10/03/24
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_deploy_config_UnixConfig */

#ifndef _Included_com_sun_deploy_config_UnixConfig
#define _Included_com_sun_deploy_config_UnixConfig
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_sun_deploy_config_UnixConfig
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_deploy_config_UnixConfig_getEnv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
