/*
 * @(#)dcPathException.c	1.8 03/12/19
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPathException.c	Tue Nov 18 16:16:02 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

char*	dcPathException[] = {
	"sun/dc/path/PathException",
	"endPath: bad path",
	"useProxy: bad path",
	""};
