#
# @(#)Makefile	1.11 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build Java2D demos/Lines sources
#

BUILDDIR = ../../../../..
DEMONAME = demos/Lines
PKGPATH = $(DEMODST)/$(DEMONAME)
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(PKGPATH)/Caps.java \
             $(PKGPATH)/Dash.java \
             $(PKGPATH)/Joins.java \
             $(PKGPATH)/LineAnim.java

DEMO_dirs  = $(DEMODST) \
             $(DEMODST)/java2d/demos \
             $(DEMODST)/java2d/demos/Lines

include ../../DemoJava2D.gmk

