/*
 * @(#)IRObjectOperations.java	1.10 03/12/19
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
package com.sun.org.omg.CORBA;


/**
* com/sun/org/omg/CORBA/IRObjectOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
* Thursday, May 6, 1999 1:51:43 AM PDT
*/

// This file has been manually _CHANGED_

public interface IRObjectOperations 
{

    // read interface

    // _CHANGED_
    //com.sun.org.omg.CORBA.DefinitionKind def_kind ();
    org.omg.CORBA.DefinitionKind def_kind ();

    // write interface
    void destroy ();
} // interface IRObjectOperations
