#
# @(#)Makefile	1.18 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# An alias for sun/javac/GNUmakefile
#

BUILDDIR=../..
PRODUCT=java
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS=../../sun/javac
all build clean clobber::
	$(SUBDIRS-loop)

