#
# @(#)Makefile	1.14 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR     = ../../..
PACKAGE      = dtbuilder
PRODUCT      = javax/swing/html
CLASSDESTDIR = $(TEMPDIR)/dtdgenclasses
include $(BUILDDIR)/common/Defs.gmk

html32dtd: swing-html32dtd

include SwingHTML32DTD.gmk
