#
# @(#)Makefile	1.6 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building hprof support classes
#

BUILDDIR = ../..
PACKAGE = sun.tools.hprof
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = sun/tools/hprof

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
