# @(#)Makefile	1.5 05/08/13

BUILDDIR = ../../../../../../..
PACKAGE = com.sun.corba.se.impl.namingutil
PRODUCT = sun

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_impl_naming_namingutil.jmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
