# @(#)Makefile	1.1 00/12/01

BUILDDIR = ../../../../..
PACKAGE = com.sun.corba.se.PortableActivation
PRODUCT = org

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#

include $(MINCLUDES)com_sun_corba_se_PortableActivationIDL.jmk

FILES_java=$(com_sun_corba_se_PortableActivationIDL_java)

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
