#
# Copyright (c) 2003, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#  
#

all:
	javac LibprocTest.java
	javac -classpath ../../build/classes LibprocClient.java

clean:
	rm -rf *.class
