#
# @(#)Makefile	1.9 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build applet demo.
#

BUILDDIR = ../../..
DEMONAME = SortDemo
include $(BUILDDIR)/common/Defs.gmk

DEMO_java  = $(DEMODST)/BidirBubbleSortAlgorithm.java \
             $(DEMODST)/BubbleSortAlgorithm.java \
             $(DEMODST)/QSortAlgorithm.java \
             $(DEMODST)/SortAlgorithm.java \
             $(DEMODST)/SortItem.java

DEMO_dirs  = $(DEMODST)

DEMO_other = $(DEMODST)/example1.html

include ../DemoApplets.gmk

