#
# @(#)Makefile	1.4 05/01/26
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building com.sun.org.apache code
#

BUILDDIR = ../../../..
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = xerces xml regexp bcel xalan xpath
all build clean clobber::
	$(SUBDIRS-loop)

