#
# @(#)Makefile	1.30 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../../../../..
PACKAGE = com.sun.corba.se.impl.activation
PRODUCT = Activation
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = orbd servertool
all build clean clobber::
	$(SUBDIRS-loop)

