/*
 * @(#)dcPathError.c	1.10 10/03/23
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPathError.c	Tue Nov 18 16:15:59 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

char*	dcPathError[] = {
	"sun/dc/path/PathError",
	"beginPath: unexpected",
	"beginSubpath: unexpected",
	"appendLine: unexpected",
	"appendQuadratic: unexpected",
	"appendCubic: unexpected",
	"closedSubpath: unexpected",
	"endPath: unexpected",
	"useProxy: unexpected",
	"getBox: unexpected",
	"sendTo: unexpected",
	"getBox: invalid box destination array",
	"sendTo: invalid path consumer",
	"",
	""};
