/*
 * @(#)dcPathError.h	1.10 10/03/23
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPathError.h	Tue Nov 18 16:15:59 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

#define	dcPathError_UNEX_beginPath	1
#define	dcPathError_UNEX_beginSubpath	2
#define	dcPathError_UNEX_appendLine	3
#define	dcPathError_UNEX_appendQuadratic	4
#define	dcPathError_UNEX_appendCubic	5
#define	dcPathError_UNEX_closedSubpath	6
#define	dcPathError_UNEX_endPath	7
#define	dcPathError_UNEX_useProxy	8
#define	dcPathError_UNEX_getBox	9
#define	dcPathError_UNEX_sendTo	10
#define	dcPathError_BAD_boxdest	11
#define	dcPathError_BAD_pathconsumer	12
#define	dcPathError_INTERRUPTED	13
extern char*   dcPathError[];
