#
# @(#)Makefile	1.10 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building JDBC javax.sql
#

BUILDDIR = ../..
PACKAGE = javax.transaction.xa
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = javax/transaction/xa

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

