/*
 * @(#)dcPathException.h	1.10 10/03/23
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPathException.h	Tue Nov 18 16:16:02 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

#define	dcPathException_BAD_PATH_endPath	1
#define	dcPathException_BAD_PATH_useProxy	2
extern char*   dcPathException[];
