#
# @(#)Makefile	1.3 10/03/23 16:59:19
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building all of javax.script
#

BUILDDIR = ../..
PACKAGE = javax.script
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

AUTO_FILES_JAVA_DIRS = javax/script

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
