#
# @(#)Makefile	1.4 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=MemoryMonitor
MAIN_CLASS_NAME=MemoryMonitor

# Class files needed 
FILES_classes = MemoryMonitor.class 

# Include basic demo template makefile
include ../Demo.gmk

