#
# @(#)Makefile	1.2 10/03/23
#
# Copyright (c) 2008, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

BUILDDIR = ../../..
DEMONAME = Laffy
SPLASH = laffy.png
include ../DemoSwing.gmk
