#
# @(#)Makefile	1.27 05/05/16
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building packages under javax.annotation
#

BUILDDIR = ../..
PACKAGE = javax.annotation
PRODUCT = javax.annotation
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = javax/annotation



#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

