#
# @(#)Makefile	1.6 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=FullThreadDump
MAIN_CLASS_NAME=FullThreadDump

# Class files needed 
FILES_classes = Deadlock.class FullThreadDump.class ThreadMonitor.class

# Include basic demo template makefile
include ../Demo.gmk

