#
# @(#)Makefile	1.15 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Create 1.1 version of BeanInfo files needed by Swing.
#
# Note that this makefile gets visited only during release engineering
# time.
#

BUILDDIR = ../../..
include $(BUILDDIR)/common/Defs.gmk
include SwingBeans.gmk

all build: swing-1.2-beans

