/*
 * @(#)DeployPerf.h	1.2 10/03/24
 *
 * Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
#ifndef _DEPLOY_PERF_H_
#define _DEPLOY_PERF_H_

#include "jni.h"
#include "PerfLib.h"


class DeployPerf;

#ifdef __cplusplus
extern "C" {
#endif

extern PERFLIB_API DeployPerf * GetDeployPerf(void);

#ifdef __cplusplus
}
#endif


class PERFLIB_API DeployPerf {

public:
    ////////////////////////////////////////////////////////////////////////////
    // Gets the current system time in milliseconds.  The time is given as a
    // 64-bit signed integer that represents the number of milliseconds since
    // the start of the Java epoch (i.e. since Midnight, January 1st, 1970).
    //
    // Override this method to provide a platform specific implementation.  The
    // subclass should implement the method in a maner that is equivalent to the
    // functionality the JVM provides for the java.lang.System.currentTimeMillis
    // method.
    //
    // @return the current system time in milliseconds.
    //
    virtual jlong getCurrentTime(void) const = 0;


    ////////////////////////////////////////////////////////////////////////////
    // Writes a time stamped label entry in the local storage buffer.  The time
    // stamp is automatically generated by this call.
    //
    // @param  label  the label to write.
    //
    virtual void put(const char * label) = 0;


    ////////////////////////////////////////////////////////////////////////////
    // Initializes the local storage.  This initialization can't be done during
    // the constructor since it isn't know at that time if local storage is
    // required or not.
    //
    virtual bool initStore(void) = 0;


    ////////////////////////////////////////////////////////////////////////////
    // Abstract class should always have virtual destructor defined.
    //
    virtual ~DeployPerf() {};
};

#endif    // _DEPLOY_PERF_H_
