#
# @(#)Makefile	1.18 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building java.beans.*
#

BUILDDIR = ../..
PACKAGE = java.beans
PRODUCT = java
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
AUTO_FILES_JAVA_DIRS = java/beans com/sun/beans

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk
