#
# Copyright (c) 1998, 2008, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#  
#

Variant=core
!include local.make

!include $(HOTSPOTWORKSPACE)/make/windows/projectfiles/common/Makefile
