############################################################
#                                                          #
# This command file has been generated by the RTPatch      #
# Professional Wizard. If this file is edited, then the    #
# corresponding patch file must be rebuilt via the command #
# line program "patchbld.exe"                              #
#                                                          #
# syntax: patchbld @<command file name>                    #
#                                                          #
############################################################

# Directory of previous version of JRE/SDK for patch generation
OLDDIR "BASE_IMAGE_DIR"/f

# Directory of newer version of JRE/SDK for patch generation
NEWDIR "NEW_IMAGE_DIR"/f

# All files are processed
FILE *.*, *

# Ignore all debug images
IGNORE *_g.*
IGNORE *.pdb
IGNORE *.map

# Ignore RegUtils.dll.  We do this because we need to call the new
# regutils installed-with-the-product from the installer before we 
# patch the regutils.  For that reason we will not be patching 
# RegUtils.dll anymore.  We save roughly 100KB by not having the
# full RegUtils.dll uncompressed in the msi binary table.
IGNORE RegUtils.dll

# Ignore special font files
#IGNORE LucidaBright*.ttf
#IGNORE LucidaTypewriter*.ttf
#IGNORE LucidaSansDemiBold.ttf

#These 2 files are created on the fly during the installation
#so there is no need to patch them
IGNORE classes.jsa
IGNORE badfonts.txt

# Patch for executable - better patch size
TYPE E

# No partial patch - file not exists in new directory is removed
NOPARTIAL

# Global undo on patch error
#UNDO

# Don't ask users for confirmation
NOCONFIRM

# Highest compression ratio
SPEED 0

# Any error encountered by patchbld should be written 
# to "patchbld.err"
LOGBLDERRS


OUTPUT "PATCH_OUTPUTDIR"

# Global Options

# Ignore if file is missing in original directory
IGNOREMISSING

# Create sub directories if not exists
CREATESUBDIR

# Generated patch file cannot be split across multiple disks
NOALLOWSPLIT 

# Patch should NOT search for files in PATH
NOPATHSEARCH

NOSELFREG
NOSHAREDFILE

# Patch should NOT search for files in current directory of patch.exe
NOSUBDIRSEARCH

# Patch should NOT use timestamp to determine if file has been 
# updated. This is to prevent problems with timezone conflicts
NOCHECKTIMEDATE

# Patch writes error to an error file
ERRORFILE

# Use long filenames
LONGNAMES

# Verbose mode
VERBOSE
