#
# @(#)Makefile	1.11 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Build Java2D gui sources
#

BUILDDIR = ../../../..
DEMONAME = gui
include $(BUILDDIR)/common/Defs.gmk
include FILES.gmk
include ../DemoJava2D.gmk
