#
# @(#)Makefile	1.15 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the FileChooser demo.
#

BUILDDIR = ../../..
DEMONAME = FileChooserDemo
include ../DemoSwing.gmk
