/*
 * @(#)JavaWebStart.idl	1.7 03/12/19
 * 
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

// JavaWebStart.idl : IDL source for JavaWebStart.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (JavaWebStart.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	typedef enum propertydispids
	{
		id_app = 1,
		id_dbg = 3,
		id_back = 4
	}
	PROPERTYDISPIDS;

	[
		object,
		uuid(5852F5EC-8BF4-11D4-A245-0080C6F74284),
		dual,
		helpstring("IisInstalled Interface"),
		pointer_default(unique)
	]
	interface IisInstalled : IDispatch
	{
		[propget, id(id_app), helpstring("property app")] HRESULT app([out, retval] BSTR *pVal);
		[propput, id(id_app), helpstring("property app")] HRESULT app([in] BSTR newVal);
		[propget, id(id_dbg), helpstring("property dbg")] HRESULT dbg([out, retval] BSTR *pVal);
		[propput, id(id_dbg), helpstring("property dbg")] HRESULT dbg([in] BSTR newVal);
		[propget, id(id_back), helpstring("property back")] HRESULT back([out, retval] BSTR *pVal);
		[propput, id(id_back), helpstring("property back")] HRESULT back([in] BSTR newVal);
	};

[
	uuid(5852F5E0-8BF4-11D4-A245-0080C6F74284),
	version(1.0),
	helpstring("JavaWebStart 1.0 Type Library")
]
library JAVAWEBSTARTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(5852F5ED-8BF4-11D4-A245-0080C6F74284),
		helpstring("isInstalled Class")
	]
	coclass isInstalled
	{
		[default] interface IisInstalled;
	};
};
