/*
 * @(#)dcPRError.c	1.11 03/12/19
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * DO NOT EDIT THIS FILE - it is automatically generated
 *
 * dcPRError.c	Tue Nov 18 16:16:12 PST 1997
 *
 * ---------------------------------------------------------------------
 *	Copyright (c) 1996-1997 by Ductus, Inc. All Rights Reserved.
 * ---------------------------------------------------------------------
 *
 */

char*	dcPRError[] = {
	"sun/dc/pr/PRError",
	"setUsage: unexpected",
	"setFillMode: unexpected",
	"setPenDiameter: unexpected",
	"setPenT4: unexpected",
	"setPenDisplacement: unexpected",
	"setPenFitting: unexpected",
	"setCaps: unexpected",
	"setCorners: unexpected",
	"setDash: unexpected",
	"setDashT4: unexpected",
	"beginPath: unexpected",
	"beginSubpath: unexpected",
	"appendCubic: unexpected",
	"appendLine: unexpected",
	"appendQuadratic: unexpected",
	"closedSubpath: unexpected",
	"endPath: unexpected",
	"useProxy: unexpected",
	"setOutputConsumer: unexpected",
	"setOutputT6: unexpected",
	"getAlphaBox: unexpected",
	"setOutputArea: unexpected",
	"getTileState: unexpected",
	"writeAlpha: unexpected",
	"nextTile: unexpected",
	"setUsage: unknown usage type",
	"setFillMode: unknown fill mode",
	"setPenDiameter: Invalid pen diameter",
	"setPenT4: invalid pen transformation",
	"setPenT4: invalid pen transformation (singular)",
	"setPenFitting: invalid pen fitting specification",
	"setCaps: unknown cap type",
	"setCorners: unknown corner type",
	"setCorners: invalid miter limit",
	"setDash: invalid dash pattern",
	"setDashT4: invalid dash transformation",
	"setDashT4: invalid dash transformation (singular)",
	"beginPath: invalid path box",
	"setOutputT6: invalid output transformation",
	"setOutputT6: invalid output transformation (singular)",
	"getAlphaBox: invalid box destination array",
	"setOutputArea: invalid output area",
	"writeAlpha: invalid alpha destination array and/or strides",
	""};
