#
# @(#)Makefile	1.4 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=hprof

# Just used to create demo directory, built in make/java/java_hprof_demo

# Include basic demo template makefile
include ../Demo.gmk

