#
# @(#)Makefile	1.21 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile to build the SampleTree demo.
#

BUILDDIR = ../../..
DEMONAME = SampleTree
include ../DemoSwing.gmk
