/*
 *  @(#)jbidi.h	1.4 03/12/19
 *
 * (C) Copyright IBM Corp. 2000 - 2003 - All Rights Reserved
 *
 * Portions Copyright 2004 by Sun Microsystems, Inc.,
 * 901 San Antonio Road, Palo Alto, California, 94303, U.S.A.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of Sun Microsystems, Inc. ("Confidential Information").  You
 * shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with Sun.
 *
 * The original version of this source code and documentation is
 * copyrighted and owned by IBM. These materials are provided
 * under terms of a License Agreement between IBM and Sun.
 * This technology is protected by multiple US and International
 * patents. This notice and attribution to IBM may not be removed.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Bidi */

#ifndef _Included_Bidi
#define _Included_Bidi
#ifdef __cplusplus
extern "C" {
#endif
#undef Bidi_DIR_LTR
#define Bidi_DIR_LTR 0L
#undef Bidi_DIR_RTL
#define Bidi_DIR_RTL 1L
#undef Bidi_DIR_DEFAULT_LTR
#define Bidi_DIR_DEFAULT_LTR -2L
#undef Bidi_DIR_DEFAULT_RTL
#define Bidi_DIR_DEFAULT_RTL -1L
#undef Bidi_DIR_MIXED
#define Bidi_DIR_MIXED -1L
#undef Bidi_DIR_MIN
#define Bidi_DIR_MIN -2L
#undef Bidi_DIR_MAX
#define Bidi_DIR_MAX 1L

JNIEXPORT jint JNICALL Java_java_text_Bidi_nativeGetDirectionCode
  (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_java_text_Bidi_nativeBidiChars
  (JNIEnv *, jclass, jobject, jcharArray, jint, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

