#
# @(#)Makefile	1.4 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
# Makefile for building hprof support classes
#

BUILDDIR = ../../../../..
PACKAGE = com.sun.demo.jvmti.hprof
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/demo/jvmti/hprof

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

all: classes
