/*
 * @(#)ParserException.java	1.1 04/02/23
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package sun.tools.jstat;

/**
 * A class for describing exceptions generated by the Parser class.
 *
 * @author Brian Doherty
 * @version 1.1, 02/23/04
 * @since 1.5
 */
public class ParserException extends Exception {

    public ParserException() {
        super();
    }

    public ParserException(String msg) {
        super(msg);
    }
}
