#
# @(#)Makefile	1.9 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

# makefile for building Common DOM classes

BUILDDIR = ../../../../..
PACKAGE = com.sun.java.browser.dom
PRODUCT = plugin
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = com/sun/java/browser/dom

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

