#   @(#)Makefile	1.3 05/08/13
#
# Build the Monitoring files
#

BUILDDIR = ../../../../../..
PACKAGE = com.sun.corba.se.spi.monitoring
PRODUCT = monitoring

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_spi_monitoring.jmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
