#
# @(#)Makefile	1.4 05/01/26
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building org.w3c.dom
#

BUILDDIR = ../../..
PACKAGE = org.w3c.dom
PRODUCT = xml
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#

AUTO_FILES_JAVA_DIRS = org/w3c/dom

#
# Resources (only if you have them)
#
# TODO: none known?
#LOCALE_SET_DEFINITION = j2sdk
#NEW_RESOURCE_BUNDLES_PROPERTIES = $(PROPERTY_FILES)
#RESOURCE_SRC_DIR = $(SHARE_SRC)/classes
#RESOURCE_DEST_DIR = $(CLASSBINDIR)
#include $(BUILDDIR)/common/Resources.gmk

#
# Rules
#

include $(BUILDDIR)/common/Classes.gmk
