/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_deploy_net_proxy_MSystemProxyHandler */

#ifndef _Included_com_sun_deploy_net_proxy_MSystemProxyHandler
#define _Included_com_sun_deploy_net_proxy_MSystemProxyHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_deploy_net_proxy_MSystemProxyHandler
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_deploy_net_proxy_MSystemProxyHandler_init
  (JNIEnv *, jclass);

/*
 * Class:     com_sun_deploy_net_proxy_MSystemProxyHandler
 * Method:    getSystemProxy
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_deploy_net_proxy_MSystemProxyHandler_getSystemProxy
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
