/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_sun_deploy_net_proxy_NetworkUtil */

#ifndef _Included_com_sun_deploy_net_proxy_NetworkUtil  
#define _Included_com_sun_deploy_net_proxy_NetworkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NetworkUtil
 * Method:    getFQHostName
 * Signature: ()Z
 */
JNIEXPORT jstring JNICALL Java_com_sun_deploy_net_proxy_WebProxyAutoDetection_getFQHostName
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
