#
# @(#)Makefile	1.3 05/03/25
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

#
# Makefile for building JDBC API and JDBC RowSet
#

BUILDDIR = ../../..
PACKAGE = com.sun.sql
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
AUTO_FILES_JAVA_DIRS = com/sun/sql

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk
