/*
 * @(#)Deployment_fr.java	1.32 04/07/16
 *
 * Copyright 2004 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package com.sun.deploy.resources;

import java.util.ListResourceBundle;
import java.awt.event.KeyEvent;


/**
 * French version of Deployment strings.
 *
 * @author Stanley Man-Kit Ho
 */

public final class Deployment_fr extends ListResourceBundle {

    public Object[][] getContents() {
	return contents;
    }

    static final Object[][] contents = {
        { "product.javapi.name", "Java Plug-in {0}" },
        { "product.javaws.name", "Java Web Start {0}" },
	{ "console.version", "Version" },
	{ "console.default_vm_version", "Version par d\u00e9faut de la machine virtuelle " },
	{ "console.using_jre_version", "Utilisation de la version JRE" },
	{ "console.user_home", "R\u00e9pertoire d'accueil de l'utilisateur" },
        { "console.caption", "Console Java" },
        { "console.clear", "Effacer" },
        { "console.clear.acceleratorKey", new Integer(KeyEvent.VK_E)},
        { "console.close", "Fermer" },
        { "console.close.acceleratorKey", new Integer(KeyEvent.VK_F) },
        { "console.copy", "Copier" },
        { "console.copy.acceleratorKey", new Integer(KeyEvent.VK_C) },
	{ "console.menu.text.top", "----------------------------------------------------\n" },
	{ "console.menu.text.c", "c:   effacer la fen\u00eatre de la console\n" },
	{ "console.menu.text.f", "f:   finaliser les objets de la file d'attente de finalisation\n" },
	{ "console.menu.text.g", "g:   lib\u00e9rer la m\u00e9moire\n" },
	{ "console.menu.text.h", "h:   afficher ce message d'aide\n" },
	{ "console.menu.text.j", "j:   vider les donn\u00e9es jcov\n"},
	{ "console.menu.text.l", "l:   vider la liste des chargeurs de classes\n" },
	{ "console.menu.text.m", "m:   imprimer le relev\u00e9 d'utilisation de la m\u00e9moire\n" },
	{ "console.menu.text.o", "o:   d\u00e9clencher la consignation\n" },
	{ "console.menu.text.p", "p:   recharger la configuration du proxy\n" },
	{ "console.menu.text.q", "q:   masquer la console\n" },
	{ "console.menu.text.r", "r:   recharger la configuration des politiques\n" },
	{ "console.menu.text.s", "s:   vider les propri\u00e9t\u00e9s syst\u00e8me et d\u00e9ploiement\n" },
	{ "console.menu.text.t", "t:   vider la liste des threads\n" },
	{ "console.menu.text.v", "v:   vider la pile des threads\n" },
	{ "console.menu.text.x", "x:   effacer le cache de chargeurs de classes\n" },
	{ "console.menu.text.0", "0-5: fixer le niveau de tra\u00e7age \u00e0 <n>\n" },
	{ "console.menu.text.tail", "----------------------------------------------------\n" },
	{ "console.done", "Termin\u00e9." },
	{ "console.trace.level.0", "Niveau de tra\u00e7age fix\u00e9 \u00e0 0 : aucun ... termin\u00e9." },
	{ "console.trace.level.1", "Niveau de tra\u00e7age fix\u00e9 \u00e0 1 : base ... termin\u00e9." },
	{ "console.trace.level.2", "Niveau de tra\u00e7age fix\u00e9 \u00e0 2 : base, r\u00e9seau ... termin\u00e9." },
	{ "console.trace.level.3", "Niveau de tra\u00e7age fix\u00e9 \u00e0 3 : base, r\u00e9seau, s\u00e9curit\u00e9 ... termin\u00e9." },
	{ "console.trace.level.4", "Niveau de tra\u00e7age fix\u00e9 \u00e0 4 : base, r\u00e9seau, s\u00e9curit\u00e9, ext ... termin\u00e9." },
	{ "console.trace.level.5", "Niveau de tra\u00e7age fix\u00e9 \u00e0 5 : tous ... termin\u00e9s." },
	{ "console.log", "Consignation : " },
	{ "console.completed", " ... termin\u00e9." },
	{ "console.dump.thread", "Vider la liste des threads ...\n" },
	{ "console.dump.stack", "Vider la pile des threads ...\n" },
	{ "console.dump.system.properties", "Vider les propri\u00e9t\u00e9s syst\u00e8me ...\n" },
        { "console.dump.deployment.properties", "Vider les propri\u00e9t\u00e9s de d\u00e9ploiement ...\n" },
	{ "console.clear.classloader", "Effacer le cache de chargeurs de classes ... termin\u00e9." },
	{ "console.reload.policy", "Recharger la configuration des r\u00e8gles" },
	{ "console.reload.proxy", "Recharger la configuration du proxy ..." },
	{ "console.gc", "Lib\u00e9rer la m\u00e9moire" },
	{ "console.finalize", "Finaliser les objets de la file d'attente de finalisation" },
	{ "console.memory", "M\u00e9moire : {0} Ko  Disponible : {1} Ko  ({2}%)" },
	{ "console.jcov.error", "Erreur d'ex\u00e9cution de Jcov : assurez-vous d'avoir indiqu\u00e9 l'option jcov correcte\n"},
	{ "console.jcov.info", "Les donn\u00e9es Jcov ont \u00e9t\u00e9 vid\u00e9es\n"},
	{ "https.dialog.caption", "Avertissement - HTTPS" },
        { "https.dialog.text" ,"<html><b>Discordance du nom d''h\u00f4te</b></html>Le nom d''h\u00f4te figurant dans le certificat de s\u00e9curit\u00e9 du serveur ne correspond pas au nom du serveur.\n\nNom d''h\u00f4te de l''URL : {0}\nNom d''h\u00f4te du certificat : {1}\n\nVoulez-vous continuer ?" },
	{ "https.dialog.unknown.host", "H\u00f4te inconnu" },
	{ "security.dialog.caption", "Avertissement - S\u00e9curit\u00e9" },
        { "security.dialog.text0" ,"Voulez-vous faire confiance au certificat {0} sign\u00e9 distribu\u00e9 par \"{1}\" ?\n\nAuthenticit\u00e9 de l''\u00e9diteur v\u00e9rifi\u00e9e par : \"{2}\"" },
        { "security.dialog.text0a" ,"Voulez-vous faire confiance au certificat {0} sign\u00e9 distribu\u00e9 par \"{1}\" ?\n\nL''authenticit\u00e9 de l''\u00e9diteur ne peut pas \u00eatre v\u00e9rifi\u00e9e." },
  	{ "security.dialog.timestamp.text1", "The {0} was signed on {1}." },
        { "security.dialog_https.text0" ,"Acceptez-vous le certificat du site Web \"{0}\" en vue d''un \u00e9change d''informations crypt\u00e9es?\n\nAuthenticit\u00e9 de l''\u00e9diteur v\u00e9rifi\u00e9e par : \"{1}\"" },
        { "security.dialog_https.text0a" ,"Acceptez-vous le certificat du site Web \"{0}\" en vue d''un \u00e9change d''informations crypt\u00e9es?\n\nL''authenticit\u00e9 de l''\u00e9diteur ne peut pas \u00eatre v\u00e9rifi\u00e9e." },
	{ "security.dialog.text1", "\nAttention : \"{0}\" atteste que ce contenu est s\u00fbr. Vous ne devez accepter ce contenu que si vous estimez que \"{1}\" est digne de confiance." },
	{ "security.dialog.unknown.issuer", "Emetteur inconnu" },
	{ "security.dialog.unknown.subject", "Sujet inconnu" },
	{ "security.dialog.certShowName", "{0} ({1})" },
	{ "security.dialog.rootCANotValid", "Le certificat de s\u00e9curit\u00e9 a \u00e9t\u00e9 \u00e9mis par une soci\u00e9t\u00e9 qui n'est pas digne de confiance." },
	{ "security.dialog.rootCAValid", "Le certificat de s\u00e9curit\u00e9 a \u00e9t\u00e9 \u00e9mis par une soci\u00e9t\u00e9 qui est digne de confiance." },
	{ "security.dialog.timeNotValid", "Le certificat de s\u00e9curit\u00e9 a expir\u00e9 ou n'est pas encore valide." },
	{ "security.dialog.timeValid", "Le certificat de s\u00e9curit\u00e9 n'a pas expir\u00e9 et est encore valide." },
	{ "security.dialog.timeValidTS", "The security certificate was valid when the {0} was signed." },
	{ "security.dialog.buttonAlways", "Toujours" },
        { "security.dialog.buttonAlways.acceleratorKey", new Integer(KeyEvent.VK_T)},
	{ "security.dialog.buttonYes", "Oui" },
	{ "security.dialog.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_O)},
        { "security.dialog.buttonNo", "Non" },
	{ "security.dialog.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "security.dialog.buttonViewCert", "Plus de d\u00e9tails" },
        { "security.dialog.buttonViewCert.acceleratorKey", new Integer(KeyEvent.VK_P)},
        { "security.badcert.caption", "Avertissement - S\u00e9curit\u00e9" },
        { "security.badcert.https.text", "Impossible de valider le certificat HTTPS.\n{0} ne sera pas ex\u00e9cut\u00e9." },
        { "security.badcert.config.text", "Votre configuration de s\u00e9curit\u00e9 actuelle ne vous permet pas de valider ce certificat. {0} ne sera pas ex\u00e9cut\u00e9." },
        { "security.badcert.text", "La validation du certificat a \u00e9chou\u00e9. {0} ne sera pas ex\u00e9cut\u00e9." },
        { "security.badcert.viewException", "Afficher l'exception" },
        { "security.badcert.viewException.acceleratorKey", new Integer(KeyEvent.VK_A)},
        { "security.badcert.viewCert", "Plus de d\u00e9tails" },
        { "security.badcert.viewCert.acceleratorKey", new Integer(KeyEvent.VK_P)},
	{ "cert.dialog.caption", "D\u00e9tails - Certificat" },
	{ "cert.dialog.certpath", "Chemin d'acc\u00e8s du certificat" },
	{ "cert.dialog.field.Version", "Version" },
	{ "cert.dialog.field.SerialNumber", "Num\u00e9ro de s\u00e9rie" },
	{ "cert.dialog.field.SignatureAlg", "Algorithme de signature" },
	{ "cert.dialog.field.Issuer", "Emetteur" },
	{ "cert.dialog.field.EffectiveDate", "Date effective" },
	{ "cert.dialog.field.ExpirationDate", "Date d'expiration" },
	{ "cert.dialog.field.Validity", "Validit\u00e9" },
	{ "cert.dialog.field.Subject", "Sujet" },
	{ "cert.dialog.field.Signature", "Signature" },
	{ "cert.dialog.field", "Champ" },
	{ "cert.dialog.value", "Valeur" },
        { "cert.dialog.close", "Fermer" },
	{ "cert.dialog.close.acceleratorKey", new Integer(KeyEvent.VK_F) },
	{ "clientauth.password.dialog.buttonOK", "OK" },
	{ "clientauth.password.dialog.buttonOK.acceleratorKey", new Integer(KeyEvent.VK_O)},
	{ "clientauth.password.dialog.buttonCancel", "Annuler" },
	{ "clientauth.password.dialog.buttonCancel.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "clientauth.password.dialog.caption", "Mot de passe - Stockage des cl\u00e9s" },
	{ "clientauth.password.dialog.text", "<html><B>Mot de passe requis</B><P> Saisissez le mot de passe permettant d'acc\u00e9der au fichier de stockage des cl\u00e9s d'authentification des clients :</html>" },
        { "clientauth.password.dialog.error.caption", "Erreur - Stockage des cl\u00e9s d'authentification client" },
        { "clientauth.password.dialog.error.text", "<html><b>Erreur d'acc\u00e8s au stockage des cl\u00e9s</b></html>Le stockage des cl\u00e9s a \u00e9t\u00e9 falsifi\u00e9, ou le mot de passe \u00e9tait incorrect." },
	{ "clientauth.certlist.dialog.buttonOK", "OK" },
	{ "clientauth.certlist.dialog.buttonOK.acceleratorKey", new Integer(KeyEvent.VK_O)},
	{ "clientauth.certlist.dialog.buttonCancel", "Annuler" },
	{ "clientauth.certlist.dialog.buttonCancel.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "clientauth.certlist.dialog.buttonDetails", "D\u00e9tails" },
	{ "clientauth.certlist.dialog.buttonDetails.acceleratorKey", new Integer(KeyEvent.VK_D)},
	{ "clientauth.certlist.dialog.caption", "Authentification du client" },
	{ "clientauth.certlist.dialog.text", "<html><B>Certificat client requis</B><P> S\u00e9lectionnez le certificat \u00e0 utiliser pour la connexion :</html>" },
	{ "dialogfactory.confirmDialogTitle", "Confirmation requise - Java" },
	{ "dialogfactory.inputDialogTitle", "Informations requises - Java" },
	{ "dialogfactory.messageDialogTitle", "Message - Java" },
	{ "dialogfactory.exceptionDialogTitle", "Erreur - Java" },
	{ "dialogfactory.optionDialogTitle", "Option - Java" },
	{ "dialogfactory.aboutDialogTitle", "A propos de - Java" },
	{ "dialogfactory.confirm.yes", "Oui" },
        { "dialogfactory.confirm.yes.acceleratorKey", new Integer(KeyEvent.VK_O)},
        { "dialogfactory.confirm.no", "Non" },
        { "dialogfactory.confirm.no.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "dialogfactory.moreInfo", "Plus de d\u00e9tails" },
        { "dialogfactory.moreInfo.acceleratorKey", new Integer(KeyEvent.VK_P)},
        { "dialogfactory.lessInfo", "Moins de d\u00e9tails" },
        { "dialogfactory.lessInfo.acceleratorKey", new Integer(KeyEvent.VK_M)},
	{ "dialogfactory.java.home.link", "http://www.java.com" },
	{ "dialogfactory.general_error", "<html><b>Exception g\u00e9n\u00e9rale</b></html>" },
	{ "dialogfactory.net_error", "<html><b>Exception de gestion de r\u00e9seau</b></html>" },
	{ "dialogfactory.security_error", "<html><b>Exception de s\u00e9curit\u00e9</b></html>" },
	{ "dialogfactory.ext_error", "<html><b>Exception de package facultatif</b></html>" },
	{ "dialogfactory.user.selected", "Utilisateur s\u00e9lectionn\u00e9 : {0}" },
	{ "dialogfactory.user.typed", "Utilisateur indiqu\u00e9 : {0}" },
	{ "deploycertstore.cert.loading", "Chargement des certificats JPI depuis {0}" },
	{ "deploycertstore.cert.loaded", "Certificats JPI charg\u00e9s depuis {0}" },
	{ "deploycertstore.cert.saving", "Enregistrement des certificats JPI dans {0}" },
	{ "deploycertstore.cert.saved", "Certificats JPI enregistr\u00e9s dans {0}" },
	{ "deploycertstore.cert.adding", "Ajout du certificat dans le magasin de certificats permanent JPI" },
	{ "deploycertstore.cert.added", "Certificat ajout\u00e9 comme alias {0} dans le magasin de certificats permanent JPI" },
	{ "deploycertstore.cert.removing", "Suppression du certificat du magasin de certificats permanent JPI" },
	{ "deploycertstore.cert.removed", "Certificat supprim\u00e9 comme alias {0} dans le magasin de certificats permanent JPI" },
	{ "deploycertstore.cert.instore", "Recherche du certificat dans le magasin de certificats permanent JPI" },
	{ "deploycertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l''aide des certificats du magasin de certificats permanent JPI" },
	{ "deploycertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans le magasin de certificats permanent JPI" },
	{ "deploycertstore.cert.getkeystore", "Obtenir l''objet de stockage des cl\u00e9s du magasin de certificats JPI" },
	{ "httpscertstore.cert.loading", "Chargement des certificats Https JPI depuis {0}" },
	{ "httpscertstore.cert.loaded", "Certificats Https JPI charg\u00e9s depuis {0}" },
	{ "httpscertstore.cert.saving", "Enregistrement des certificats Https JPI dans {0}" },
	{ "httpscertstore.cert.saved", "Certificats Https JPI enregistr\u00e9s dans {0}" },
	{ "httpscertstore.cert.adding", "Ajout du certificat Https dans le magasin de certificats permanent JPI" },
	{ "httpscertstore.cert.added", "Certificat Https ajout\u00e9 comme alias {0} dans le magasin de certificats permanent JPI" },
	{ "httpscertstore.cert.removing", "Suppression du certificat Https du magasin de certificats permanent JPI" },
	{ "httpscertstore.cert.removed", "Certificat Https supprim\u00e9 comme alias {0} dans le magasin de certificats permanent JPI" },
	{ "httpscertstore.cert.instore", "Recherche du certificat Https dans le magasin de certificats permanent JPI" },
	{ "httpscertstore.cert.canverify", "D\u00e9terminer si le certificat Https peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l''aide des certificats du magasin de certificats permanent JPI" },
	{ "httpscertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat Https dans le magasin de certificats permanent JPI" },
	{ "httpscertstore.cert.getkeystore", "Obtenir l''objet de stockage des cl\u00e9s du magasin de certificats Https" },
	{ "rootcertstore.cert.loading", "Chargement des certificats AC racine depuis {0}" },
	{ "rootcertstore.cert.loaded", "Certificats AC racine charg\u00e9s depuis {0}" },
	{ "rootcertstore.cert.noload", "Fichier de certificats AC racine introuvable : {0}" },
	{ "rootcertstore.cert.saving", "Enregistrement des certificats AC racine dans {0}" },
	{ "rootcertstore.cert.saved", "Certificats AC racine enregistr\u00e9s dans {0}" },
	{ "rootcertstore.cert.adding", "Ajout du certificat dans la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.added", "Certificat ajout\u00e9 comme alias {0} dans la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.removing", "Suppression du certificat de la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.removed", "Certificat supprim\u00e9 comme alias {0} dans la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.instore", "Recherche du certificat dans la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l''aide des certificats de la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.getkeystore", "Obtenir l''objet de stockage des cl\u00e9s de la zone de stockage des certificats AC racine" },
	{ "rootcertstore.cert.verify.ok", "La v\u00e9rification du certificat \u00e0 l''aide des certificats AC racine a r\u00e9ussi" },
	{ "rootcertstore.cert.verify.fail", "La v\u00e9rification du certificat \u00e0 l''aide des certificats AC racine a \u00e9chou\u00e9" },
	{ "rootcertstore.cert.tobeverified", "Certificat \u00e0 v\u00e9rifier :\n{0}" },
	{ "rootcertstore.cert.tobecompared", "Comparaison entre le certificat et le certificat AC racine :\n{0}" },
	{ "roothttpscertstore.cert.loading", "Chargement des certificats Https AC racine depuis {0}" },
	{ "roothttpscertstore.cert.loaded", "Certificats Https AC racine charg\u00e9s depuis {0}" },
	{ "roothttpscertstore.cert.noload", "Fichier de certificats SSL AC racine introuvable : {0}" },
	{ "roothttpscertstore.cert.saving", "Enregistrement des certificats Https AC racine dans {0}" },
	{ "roothttpscertstore.cert.saved", "Certificats SSL AC racine enregistr\u00e9s dans {0}" },
	{ "roothttpscertstore.cert.adding", "Ajout du certificat dans la zone de stockage des certificats Https AC racine" },
	{ "roothttpscertstore.cert.added", "Certificat ajout\u00e9 dans la zone de stockage des certificats SSL AC racine en tant qu''alias {0}" },
	{ "roothttpscertstore.cert.removing", "Suppression du certificat de la zone de stockage des certificats Https AC racine" },
	{ "roothttpscertstore.cert.removed", "Certificat supprim\u00e9 de la zone de stockage des certificats SSL AC racine en tant qu''alias {0}" },
	{ "roothttpscertstore.cert.instore", "Recherche du certificat dans la zone de stockage des certificats Https AC racine" },
	{ "roothttpscertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l''aide des certificats de la zone de stockage des certificats Https AC racine" },
	{ "roothttpscertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats Https AC racine" },
	{ "roothttpscertstore.cert.getkeystore", "Obtenir l''objet de stockage des cl\u00e9s de la zone des certificats Https AC racine" },
	{ "roothttpscertstore.cert.verify.ok", "La v\u00e9rification du certificat \u00e0 l''aide des certificats SSL AC racine a r\u00e9ussi" },
	{ "roothttpscertstore.cert.verify.fail", "La v\u00e9rification du certificat \u00e0 l''aide des certificats Https AC racine a \u00e9chou\u00e9" },
	{ "roothttpscertstore.cert.tobeverified", "Certificat \u00e0 v\u00e9rifier :\n{0}" },
	{ "roothttpscertstore.cert.tobecompared", "Comparaison entre le certificat et le certificat Https AC racine :\n{0}" },
	{ "sessioncertstore.cert.loading", "Chargement des certificats depuis la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.loaded", "Certificats charg\u00e9s depuis la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.saving", "Enregistrement des certificats dans la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.saved", "Certificats enregistr\u00e9s dans la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.adding", "Ajout du certificat dans la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.added", "Certificat ajout\u00e9 dans la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.removing", "Suppression du certificat de la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.removed", "Certificat supprim\u00e9 de la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.instore", "Recherche du certificat dans la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l''aide des certificats de la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats de session JPI" },
	{ "sessioncertstore.cert.getkeystore", "Obtenir l''objet de stockage des cl\u00e9s de la zone de stockage des certificats de session JPI" },
        { "iexplorer.cert.loading", "Chargement des certificats \u00e0 partir de la zone de stockage des certificats {0} d''Internet Explorer" },
        { "iexplorer.cert.loaded", "Certificats charg\u00e9s \u00e0 partir de la zone de stockage des certificats {0} d''Internet Explorer" },
        { "iexplorer.cert.instore", "Recherche du certificat dans la zone de stockage des certificats {0} d''Internet Explorer" },
        { "iexplorer.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l''aide des certificats de la zone de stockage des certificats {0} d''Internet Explorer" },
        { "iexplorer.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats {0} d''Internet Explorer" },
        { "iexplorer.cert.verify.ok", "La v\u00e9rification du certificat \u00e0 l''aide des certificats {0} d''Internet Explorer a r\u00e9ussi" },
        { "iexplorer.cert.verify.fail", "La v\u00e9rification du certificat \u00e0 l''aide des certificats {0} d''Internet Explorer a \u00e9chou\u00e9" },
        { "iexplorer.cert.tobeverified", "Certificat \u00e0 v\u00e9rifier :\n{0}" },
        { "iexplorer.cert.tobecompared", "Comparaison entre le certificat et le certificat {0} d''Internet Explorer :\n{1}" },

        { "mozilla.cert.loading", "Chargement des certificats depuis la zone de stockage des certificats Mozilla {0}" },
        { "mozilla.cert.loaded", "Certificats charg\u00e9s depuis la zone de stockage des certificats Mozilla {0}" },
        { "mozilla.cert.instore", "Recherche du certificat dans la zone de stockage des certificats Mozilla {0}" },
        { "mozilla.cert.canverify", "D\u00e9terminer si le certificat peut \u00eatre v\u00e9rifi\u00e9 \u00e0 l''aide des certificats de la zone de stockage des certificats Mozilla {0}" },
        { "mozilla.cert.iterator", "Obtenir le caract\u00e8re it\u00e9ratif du certificat dans la zone de stockage des certificats Mozilla {0}" },
        { "mozilla.cert.verify.ok", "La v\u00e9rification du certificat \u00e0 l''aide des certificats Mozilla {0} a r\u00e9ussi" },
        { "mozilla.cert.verify.fail", "La v\u00e9rification du certificat \u00e0 l''aide des certificats Mozilla {0} a \u00e9chou\u00e9" },
        { "mozilla.cert.tobeverified", "Certificat \u00e0 v\u00e9rifier :\n{0}" },
        { "mozilla.cert.tobecompared", "Comparaison entre le certificat et le certificat Mozilla {0} :\n{1}" },

        { "browserkeystore.jss.no", "Le package JSS est introuvable" },
        { "browserkeystore.jss.yes", "Le package JSS est charg\u00e9" },
        { "browserkeystore.jss.notconfig", "JSS n''est pas configur\u00e9" },
        { "browserkeystore.jss.config", "JSS est configur\u00e9" },
        { "browserkeystore.mozilla.dir", "Acc\u00e8s aux cl\u00e9s et au certificat dans le profil utilisateur Mozilla : {0}" },
        { "browserkeystore.password.dialog.buttonOK", "OK" },
        { "browserkeystore.password.dialog.buttonOK.acceleratorKey", new Integer(KeyEvent.VK_O)},
        { "browserkeystore.password.dialog.buttonCancel", "Annuler" },
        { "browserkeystore.password.dialog.buttonCancel.acceleratorKey", new Integer(KeyEvent.VK_A)},
        { "browserkeystore.password.dialog.caption", "Mot de passe requis" },
        { "browserkeystore.password.dialog.text", "Entrez le mot de passe du certificat {0} :\n" },
        { "mozillamykeystore.priv.notfound", "cl\u00e9 priv\u00e9e introuvable pour le cert. : {0}" },
	{ "hostnameverifier.automation.ignoremismatch", "Automatisation : Ignorer la non-concordance de nom d''h\u00f4te" },
	{ "trustdecider.check.basicconstraints", "La v\u00e9rification des contraintes de base dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.leafkeyusage", "La v\u00e9rification de la syntaxe de la cl\u00e9 du noeud terminal dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.signerkeyusage", "La v\u00e9rification de la syntaxe de la cl\u00e9 du signataire dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.extensions", "La v\u00e9rification des extensions critiques dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.signature", "La v\u00e9rification de la signature dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.basicconstraints.certtypebit", "La v\u00e9rification du bit du type de netscape dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.basicconstraints.extensionvalue", "La v\u00e9rification de la valeur de l''extension de netscape dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.basicconstraints.bitvalue", "La v\u00e9rification des bits 5, 6 et 7 de netscape dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.basicconstraints.enduser", "La v\u00e9rification des actions de l''utilisateur final en tant qu''AC dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.basicconstraints.pathlength", "La v\u00e9rification des contraintes li\u00e9es \u00e0 la longueur du chemin d''acc\u00e8s dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.leafkeyusage.length", "La v\u00e9rification de la longueur de la syntaxe de la cl\u00e9 dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.leafkeyusage.digitalsignature", "La v\u00e9rification de la signature num\u00e9rique dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.leafkeyusage.extkeyusageinfo", "La v\u00e9rification des informations relatives \u00e0 la syntaxe de la cl\u00e9 d''extension dans le certificat a \u00e9chou\u00e9" },
        { "trustdecider.check.leafkeyusage.tsaextkeyusageinfo", "La v\u00e9rification des informations relatives \u00e0 la syntaxe de la cl\u00e9 d''extension TSA dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.leafkeyusage.certtypebit", "La v\u00e9rification du bit du type de netscape dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.signerkeyusage.lengthandbit", "La v\u00e9rification de la longueur et du bit dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.signerkeyusage.keyusage", "La v\u00e9rification de la syntaxe de la cl\u00e9 dans le certificat a \u00e9chou\u00e9" },
	{ "trustdecider.check.canonicalize.updatecert", "Mettre \u00e0 jour le certificat root avec le certificat du fichier de certificats AC" },
	{ "trustdecider.check.canonicalize.missing", "Ajouter le certificat root manquant" },
	{ "trustdecider.check.gettrustedcert.find", "Rechercher l''AC racine valide dans le fichier de certificats AC" },
	{ "trustdecider.check.gettrustedissuercert.find", "Rechercher l''AC racine valide manquant dans le fichier de certificats AC" },
        { "trustdecider.check.timestamping.no", "Aucune information d''horodatage disponible" },
        { "trustdecider.check.timestamping.yes", "Des informations d''horodatage sont disponibles" },
        { "trustdecider.check.timestamping.tsapath", "Commencer la v\u00e9rification du chemin d''acc\u00e8s du certificat TSA" },
        { "trustdecider.check.timestamping.inca", "M\u00eame si le certificat a expir\u00e9, mais il a \u00e9t\u00e9 horodat\u00e9 dans une p\u00e9riode valide et a une TSA valide" },
        { "trustdecider.check.timestamping.notinca", "Le certificat a expir\u00e9, mais la TSA n''est pas valide" },
        { "trustdecider.check.timestamping.valid", "Le certificat a expir\u00e9, et il est horodat\u00e9 dans une p\u00e9riode valide"},
        { "trustdecider.check.timestamping.invalid", "Le certificat a expir\u00e9, et il est horodat\u00e9 dans une p\u00e9riode non valide" },
        { "trustdecider.check.timestamping.need", "Le certificat a expir\u00e9 ; v\u00e9rification des informations d''horodatage requise" },
        { "trustdecider.check.timestamping.noneed", "Le certificat n''a pas expir\u00e9 ; aucune v\u00e9rification des informations d''horodatage requise" },
        { "trustdecider.check.timestamping.notfound", "La nouvelle API d''horodatage est introuvable" },
	{ "trustdecider.user.grant.session", "L''utilisateur a accord\u00e9 les droits d''acc\u00e8s au code pour cette session seulement" },
	{ "trustdecider.user.grant.forever", "L''utilisateur a accord\u00e9 les droits d''acc\u00e8s au code de mani\u00e8re permanente" },
	{ "trustdecider.user.deny", "L''utilisateur a refus\u00e9 les droits d''acc\u00e8s au code" },
	{ "trustdecider.automation.trustcert", "Automatisation : Autoriser le certificat RSA pour la signature" },
	{ "trustdecider.code.type.applet", "applet" },
	{ "trustdecider.code.type.application", "application" },
	{ "trustdecider.code.type.extension", "extension" },
	{ "trustdecider.code.type.installer", "programme d'installation" },
	{ "trustdecider.user.cannot.grant.any", "Votre configuration de s\u00e9curit\u00e9 ne vous permet pas d'autoriser de nouveaux certificats" },
	{ "trustdecider.user.cannot.grant.notinca", "Votre configuration de s\u00e9curit\u00e9 ne vous permet pas d'autoriser des certificats autosign\u00e9s" },
	{ "x509trustmgr.automation.ignoreclientcert", "Automatisation : Ignorer le certificat de client non autoris\u00e9" },
	{ "x509trustmgr.automation.ignoreservercert", "Automatisation : Ignorer le certificat de serveur non autoris\u00e9" },
	{ "net.proxy.text", "Proxy : " },
	{ "net.proxy.override.text", "Remplacement du proxy : " },
	{ "net.proxy.configuration.text", "Configuration du proxy : " },
	{ "net.proxy.type.browser", "Configuration du proxy du navigateur" },
	{ "net.proxy.type.auto", "Configuration automatique du proxy" },
	{ "net.proxy.type.manual", "Configuration manuelle" },
	{ "net.proxy.type.none", "Aucun proxy" },
	{ "net.proxy.type.user", "L'utilisateur a \u00e9cras\u00e9 les param\u00e8tres proxy du navigateur." },
	{ "net.proxy.loading.ie", "Chargement de la configuration du proxy \u00e0 partir d''Internet Explorer ..."},
	{ "net.proxy.loading.ns", "Chargement de la configuration du proxy \u00e0 partir de Netscape Navigator ..."},
	{ "net.proxy.loading.userdef", "Chargement de la configuration du proxy d\u00e9finie par l''utilisateur ..."},
	{ "net.proxy.loading.direct", "Chargement de la configuration directe du proxy ..."},
	{ "net.proxy.loading.manual", "Chargement de la configuration manuelle du proxy ..."},
	{ "net.proxy.loading.auto",   "Chargement de la configuration auto du proxy ..."},
	{ "net.proxy.loading.browser",   "Chargement de la configuration proxy du navigateur ..."},
	{ "net.proxy.loading.manual.error", "Impossible d''utiliser la configuration manuelle du proxy - basculement sur DIRECTE"},
	{ "net.proxy.loading.auto.error", "Impossible d''utiliser la configuration auto du proxy - basculement sur MANUELLE"},
	{ "net.proxy.loading.done", "Termin\u00e9."},
	{ "net.proxy.browser.pref.read", "Lecture du fichier de pr\u00e9f\u00e9rences utilisateur \u00e0 partir de {0}"},
	{ "net.proxy.browser.proxyEnable", "    Activation proxy : {0}"},
	{ "net.proxy.browser.proxyList",     "    Liste proxy : {0}"},
	{ "net.proxy.browser.proxyOverride", "    Priorit\u00e9 proxy : {0}"},
	{ "net.proxy.browser.autoConfigURL", "    URL config. auto : {0}"},
	{ "net.proxy.browser.smartConfig", "Ex\u00e9cutez une commande Ping sur le serveur proxy {0} utilisant le port"},
        { "net.proxy.browser.connectionException", "Le serveur proxy {0} utilisant le port {1} est inaccessible"},
	{ "net.proxy.ns6.regs.exception", "Erreur lors de la lecture du fichier de registre : {0}"},
	{ "net.proxy.pattern.convert", "Convertir la liste de contournement de proxy en expression r\u00e9guli\u00e8re : "},
	{ "net.proxy.pattern.convert.error", "Impossible de convertir la liste de contournement de proxy en expression r\u00e9guli\u00e8re - ignorer"},
	{ "net.proxy.auto.download.ins", "T\u00e9l\u00e9chargement du fichier INS \u00e0 partir de {0}" },
	{ "net.proxy.auto.download.js", "T\u00e9l\u00e9chargement du fichier de proxy auto \u00e0 partir de {0}" },
	{ "net.proxy.auto.result.error", "Impossible de d\u00e9terminer la configuration du proxy \u00e0 partir de l''\u00e9valuation - basculement sur DIRECTE"},
        { "net.proxy.service.not_available", "Service proxy non disponible pour {0} - basculement par d\u00e9faut sur DIRECTE" },
	{ "net.proxy.error.caption", "Erreur - Configuration du proxy" },
	{ "net.proxy.nsprefs.error", "<html><b>Impossible de r\u00e9cup\u00e9rer les param\u00e8tres du proxy</b></html>Basculement vers une autre configuration du proxy.\n" },
	{ "net.proxy.connect", "Connexion de {0} avec proxy={1}" },
	{ "net.authenticate.caption", "Mot de passe requis - Gestion de r\u00e9seau"},
	{ "net.authenticate.label", "<html><b>Saisissez vos nom d'utilisateur et mot de passe :</b></html>"},
	{ "net.authenticate.resource", "Ressource :" },
	{ "net.authenticate.username", "Nom d'utilisateur :" },
        { "net.authenticate.username.mnemonic", "VK_N" },
	{ "net.authenticate.password", "Mot de passe :" },
        { "net.authenticate.password.mnemonic", "VK_M" },
	{ "net.authenticate.firewall", "Serveur :" },
	{ "net.authenticate.domain", "Domaine :"},
        { "net.authenticate.domain.mnemonic", "VK_D" },
	{ "net.authenticate.realm", "Domaine principal :" },
	{ "net.authenticate.scheme", "Plan :" },
	{ "net.authenticate.unknownSite", "Site inconnu" },
	{ "net.cookie.cache", "Cache de cookies : " },
	{ "net.cookie.server", "Serveur {0} demandant de d\u00e9finir un cookie avec \"{1}\"" },
	{ "net.cookie.connect", "Connexion {0} avec cookie \"{1}\"" },
	{ "net.cookie.ignore.setcookie", "Service de traitement des cookies non disponible - ignorer la fonction de \"d\u00e9finition d'un cookie\"" },
	{ "net.cookie.noservice", "Service de traitement des cookies non disponible - utilisez le cache pour d\u00e9terminer le \"cookie\"" },
	{"about.java.version", "Version {0} (build {1})"},
	{"about.prompt.info", "Pour de plus amples informations sur la technologie Java et d\u00e9couvrir les applications Java, consultez le site"},
	{"about.home.link", "http://www.java.com"},
	{"about.option.close", "Fermer"},
	{"about.option.close.acceleratorKey", new Integer(KeyEvent.VK_F)},
        {"about.copyright", "Copyright 2004 Sun Microsystems, Inc."},
        { "about.legal.note" ,"Tous droits r\u00e9serv\u00e9s. Son utilisation est soumise aux termes de la licence." },
	{ "cert.remove_button", "Supprimer" },
        { "cert.remove_button.mnemonic", "VK_S" },
        { "cert.import_button", "Importer" },
        { "cert.import_button.mnemonic", "VK_I" },
        { "cert.export_button", "Exporter" },
        { "cert.export_button.mnemonic", "VK_E" },
        { "cert.details_button", "D\u00e9tails" },
        { "cert.details_button.mnemonic", "VK_D" },
        { "cert.viewcert_button", "Afficher le certificat" },
        { "cert.viewcert_button.mnemonic", "VK_A" },
        { "cert.close_button", "Fermer" },
        { "cert.close_button.mnemonic", "VK_F" },
        { "cert.type.trusted_certs", "Certificats approuv\u00e9s" },
        { "cert.type.secure_site", "Site s\u00e9curis\u00e9" },
        { "cert.type.client_auth", "Authentification du client" },
        { "cert.type.signer_ca", "AC du signataire" },
        { "cert.type.secure_site_ca", "AC de site s\u00e9curis\u00e9" },
        { "cert.rbutton.user", "Utilisateur" },
        { "cert.rbutton.system", "Syst\u00e8me" },
        { "cert.settings", "Certificats" },
        { "cert.dialog.import.error.caption", "Erreur - Importer le certificat" },
        { "cert.dialog.export.error.caption", "Erreur - Exporter le certificat" },
        { "cert.dialog.import.format.text", "<html><b>Format de fichier non reconnu</b></html>Aucun certificat ne sera import\u00e9." },
        { "cert.dialog.export.password.text", "<html><b>Mot de passe non valide</b></html>Le mot de passe que vous avez saisi est incorrect." },
        { "cert.dialog.import.file.text", "<html><b>Fichier introuvable</b></html>Aucun certificat ne sera import\u00e9." },
        { "cert.dialog.import.password.text", "<html><b>Mot de passe non valide</b></html>Le mot de passe que vous avez saisi est incorrect." },
        { "cert.dialog.password.caption", "Mot de passe" },
        { "cert.dialog.password.import.caption", "Mot de passe - Importer" },
        { "cert.dialog.password.export.caption", "Mot de passe - Exporter" },
        { "cert.dialog.password.text", "<html><b>Saisissez un mot de passe afin d'acc\u00e9der au fichier :<b></html>" },
        { "cert.dialog.exportpassword.text", "<html><b>Saisissez un mot de passe afin d'acc\u00e9der \u00e0 la cl\u00e9 priv\u00e9e contenue dans le fichier de stockage des cl\u00e9s d'authentification client :<b></html>" },
        { "cert.dialog.savepassword.text", "<html><b>Saisissez un mot de passe afin d'enregistrer ce fichier de cl\u00e9s :<b></html>" },
        { "cert.dialog.password.okButton", "OK" },
        { "cert.dialog.password.cancelButton", "Annuler" },
        { "cert.dialog.export.error.caption", "Erreur - Exporter le certificat" },
        { "cert.dialog.export.text", "<html><b>Impossible d'exporter</b></html>Aucun certificat n'a \u00e9t\u00e9 export\u00e9." },
        { "cert.dialog.remove.text", "Voulez-vous vraiment supprimer le(s) certificat(s) ?" },
	{ "cert.dialog.remove.caption", "Supprimer le certificat" },
	{ "cert.dialog.issued.to", "D\u00e9livr\u00e9 \u00e0 " },
	{ "cert.dialog.issued.by", "D\u00e9livr\u00e9 par " },
	{ "cert.dialog.user.level", "Utilisateur" },
	{ "cert.dialog.system.level", "Syst\u00e8me" },
	{ "cert.dialog.certtype", "Type de certificat : "},
	{ "controlpanel.jre.platformTableColumnTitle","Plate-forme"},
	{ "controlpanel.jre.productTableColumnTitle","Produit" },
	{ "controlpanel.jre.locationTableColumnTitle","Emplacement" },
	{ "controlpanel.jre.pathTableColumnTitle","Chemin" },
	{ "controlpanel.jre.enabledTableColumnTitle", "Activ\u00e9" },
	{ "jnlp.jre.title", "Param\u00e8tres d'ex\u00e9cution Java JNLP" },
	{ "jnlp.jre.versions", "Versions de Java Runtime Environment" },
	{ "jnlp.jre.choose.button", "Choisir" },
	{ "jnlp.jre.find.button", "Rechercher" },
	{ "jnlp.jre.add.button", "Ajouter" },
	{ "jnlp.jre.remove.button", "Supprimer" },
	{ "jnlp.jre.ok.button", "OK" },
	{ "jnlp.jre.cancel.button", "Annuler" },
	{ "jnlp.jre.choose.button.mnemonic", "VK_H" },
	{ "jnlp.jre.find.button.mnemonic", "VK_R" },
	{ "jnlp.jre.add.button.mnemonic", "VK_J" },
	{ "jnlp.jre.remove.button.mnemonic", "VK_S" },
	{ "jnlp.jre.ok.button.mnemonic", "VK_O" },
	{ "jnlp.jre.cancel.button.mnemonic", "VK_A" },
	{ "find.dialog.title", "S\u00e9lecteur JRE"},
	{ "find.title", "Java Runtime Environment"},
	{ "find.cancelButton", "Annuler"},
	{ "find.prevButton", "Pr\u00e9c\u00e9dent"},
	{ "find.nextButton", "Suivant"},
	{ "find.cancelButtonMnemonic", "VK_A"},
	{ "find.prevButtonMnemonic", "VK_P"},
	{ "find.nextButtonMnemonic", "VK_S"},
	{ "find.intro", "Pour lancer des applications, Java Web Start doit conna\u00eetre l'emplacement des installations de Java Runtime Environment.\n\nVous pouvez s\u00e9lectionner une version de JRE connue ou choisir un r\u00e9pertoire du syst\u00e8me de fichiers comme emplacement de recherche des copies de JRE." },
	{ "find.searching.title", "Recherche des copies de JRE disponibles : cette op\u00e9ration peut prendre quelques minutes." },
	{ "find.searching.prefix", "v\u00e9rification : " },
	{ "find.foundJREs.title", "Les copies suivantes de JRE ont \u00e9t\u00e9 trouv\u00e9es ; cliquez sur Suivant pour les ajouter" },
	{ "find.noJREs.title", "Impossible de localiser une version de JRE ; cliquez sur Pr\u00e9c\u00e9dent pour s\u00e9lectionner un autre r\u00e9pertoire de recherche" },
	// Each line in the property_file_header must start with "#"
        { "config.property_file_header" ,"# Propri\u00e9t\u00e9s du d\u00e9ploiement Java(tm)\n# NE MODIFIEZ PAS CE FICHIER. Il est g\u00e9n\u00e9r\u00e9 automatiquement.\n# Utilisez le panneau de configuration Java pour modifier les propri\u00e9t\u00e9s." },
        { "config.unknownSubject", "Sujet inconnu" },
        { "config.unknownIssuer", "Utilisateur inconnu" },
        { "config.certShowName", "{0} ({1})" },
        { "config.certShowOOU", "{0} {1}" },
        { "config.proxy.autourl.invalid.text", "<html><b>Adresse URL incorrecte</b></html>L'URL de configuration automatique du proxy n'est pas valide." },
        { "config.proxy.autourl.invalid.caption", "Erreur - Proxy" },
	// Java Web Start Properties
	 { "APIImpl.clipboard.message.read", "Cette application a demand\u00e9 un acc\u00e8s en lecture seule au presse-papiers du syst\u00e8me. L'application pourrait acc\u00e9der \u00e0 des informations confidentielles stock\u00e9es dans le presse-papiers. Voulez-vous autoriser cette action ?" },
        { "APIImpl.clipboard.message.write", "Cette application a demand\u00e9 un acc\u00e8s en \u00e9criture au presse-papiers du syst\u00e8me. L'application pourrait \u00e9craser des informations stock\u00e9es dans le presse-papiers. Voulez-vous autoriser cette action ?" },
        { "APIImpl.file.open.message", "Cette application a demand\u00e9 un acc\u00e8s au syst\u00e8me de fichiers en mode de lecture. L'application pourrait acc\u00e9der \u00e0 des informations confidentielles stock\u00e9es dans le syst\u00e8me de fichiers. Voulez-vous autoriser cette action ?" },
        { "APIImpl.file.save.fileExist", "{0} existe d\u00e9j\u00e0.\n Voulez-vous le remplacer ?" },
        { "APIImpl.file.save.fileExistTitle", "Fichier existant" },
        { "APIImpl.file.save.message", "Cette application a demand\u00e9 un acc\u00e8s en lecture/\u00e9criture \u00e0 un fichier situ\u00e9 dans le syst\u00e8me de fichiers local. Si vous autorisez cette action, l'application ne pourra acc\u00e9der qu'aux fichiers s\u00e9lectionn\u00e9s dans la bo\u00eete de dialogue suivante. Voulez-vous autoriser cette action ?" },
        { "APIImpl.persistence.accessdenied", "Acc\u00e8s \u00e0 l''espace de stockage r\u00e9manent refus\u00e9 pour l''URL {0}" },
        { "APIImpl.persistence.filesizemessage", "Longueur de fichier maximale d\u00e9pass\u00e9e" },
        { "APIImpl.persistence.message", "Cette application a demand\u00e9 de l''espace disque local suppl\u00e9mentaire. Actuellement, l''espace maximum de stockage allou\u00e9 est de {1} octets. L''application demande que cet espace soit port\u00e9 \u00e0 {0} octets. Voulez-vous autoriser cette action ?" },
        { "APIImpl.print.message", "Cette application a demand\u00e9 un acc\u00e8s \u00e0 l'imprimante par d\u00e9faut. Si vous autorisez cette action, l'application pourra acc\u00e9der \u00e0 l'imprimante en mode d'\u00e9criture. Voulez-vous autoriser cette action ?" },
	{ "APIImpl.extended.fileOpen.message1", "Cette application a demand\u00e9 un acc\u00e8s en lecture/\u00e9criture aux fichiers du syst\u00e8me de fichiers local suivants :"},
	{ "APIImpl.extended.fileOpen.message2", "Si vous autorisez cette action, l'application ne pourra acc\u00e9der qu'aux fichiers r\u00e9pertori\u00e9s ci-dessus. Voulez-vous autoriser cette action ?"},
        { "APIImpl.securityDialog.no", "Non" },
        { "APIImpl.securityDialog.remember", "Ne plus afficher cet avis" },
        { "APIImpl.securityDialog.title", "Avis de s\u00e9curit\u00e9" },
        { "APIImpl.securityDialog.yes", "Oui" },
        { "Launch.error.installfailed", "Echec de l'installation" },
        { "aboutBox.closeButton", "Fermer" },
        { "aboutBox.versionLabel", "Version {0} (build {1})" },
        { "applet.failedToStart", "Impossible de lancer l''applet : {0}" },
        { "applet.initializing", "Initialisation de l'applet" },
        { "applet.initializingFailed", "Impossible d''initialiser l''applet : {0}" },
        { "applet.running", "Ex\u00e9cution..." },
        { "java48.image", "image/java48.png" },
        { "java32.image", "image/java32.png" },
        { "extensionInstall.rebootMessage", "Pour que les modifications soient prises en compte, red\u00e9marrez Windows.\n\nVoulez-vous red\u00e9marrer Windows maintenant ?" },
        { "extensionInstall.rebootTitle", "Red\u00e9marrer Windows" },
        { "install.configButton", "Configurer ..." },
        { "install.configMnemonic", "VK_C" },
        { "install.errorInstalling", "Erreur inattendue lors de l'installation de Java Runtime Environment ; recommencez." },
        { "install.errorRestarting", "Erreur inattendue lors du d\u00e9marrage ; recommencez." },
        { "install.title" ,"{0} - Cr\u00e9er des raccourcis" },
        { "install.windows.both.message" ,"Voulez-vous cr\u00e9er des raccourcis sur le Bureau et dans le menu D\u00e9marrer pour\n{0} ?" },
        { "install.gnome.both.message" ,"Voulez-vous cr\u00e9er des raccourcis sur le Bureau et dans le menu de l''application pour\n{0} ?" },
        { "install.desktop.message" ,"Voulez-vous cr\u00e9er des raccourcis sur le Bureau pour\n{0} ?" },
        { "install.windows.menu.message" ,"Voulez-vous cr\u00e9er des raccourcis dans le menu D\u00e9marrer pour\n{0} ?" },
        { "install.gnome.menu.message" ,"Voulez-vous cr\u00e9er des raccourcis dans le menu de l''application pour\n{0} ?" },
        { "install.noButton", "Non" },
        { "install.noMnemonic", "VK_N" },
        { "install.yesButton", "Oui" },
        { "install.yesMnemonic", "VK_O" },
        { "launch.cancel", "Annuler" },
        { "launch.downloadingJRE", "Demande de JRE {0} \u00e0 partir de {1}" },
        { "launch.error.badfield", "Le champ {0} contient une valeur incorrecte : {1}" },
        { "launch.error.badfield-signedjnlp", "Le champ {0} contient une valeur incorrecte dans le fichier de lancement sign\u00e9 : {1}" },
        { "launch.error.badfield.download.https", "Impossible de t\u00e9l\u00e9charger via HTTPS" },
        { "launch.error.badfield.https", "Java 1.4+ est requis pour la prise en charge de HTTPS" },
        { "launch.error.badjarfile", "Fichier JAR endommag\u00e9 dans {0}" },
        { "launch.error.badjnlversion", "Version non compatible de JNLP dans le fichier de lancement : {0}. Seules les versions 1.0 et 1.5 sont compatibles avec cette version. Signalez ce probl\u00e8me au fournisseur de l''application." },
        { "launch.error.badmimetyperesponse", "Type MIME incorrect retourn\u00e9 par le serveur pendant l''acc\u00e8s \u00e0 la ressource : {0} - {1}" },
        { "launch.error.badsignedjnlp", "Impossible de valider la signature du fichier de lancement. La version sign\u00e9e ne correspond pas \u00e0 la version t\u00e9l\u00e9charg\u00e9e." },
        { "launch.error.badversionresponse", "Version incorrecte dans la r\u00e9ponse envoy\u00e9e par la serveur pendant l''acc\u00e8s \u00e0 la ressource : {0} - {1}" },
        { "launch.error.canceledloadingresource", "Le chargement de la ressource {0} a \u00e9t\u00e9 annul\u00e9 par l''utilisateur" },
        { "launch.error.category.arguments", "Erreur - argument incorrect" },
        { "launch.error.category.download", "Erreur de t\u00e9l\u00e9chargement" },
        { "launch.error.category.launchdesc", "Erreur dans le fichier de lancement" },
        { "launch.error.category.memory", "Erreur - m\u00e9moire satur\u00e9e" },
        { "launch.error.category.security", "Erreur de s\u00e9curit\u00e9" },
        { "launch.error.category.config", "Configuration syst\u00e8me" },
        { "launch.error.category.unexpected", "Erreur inattendue" },
        { "launch.error.couldnotloadarg", "Impossible de charger le fichier/l''URL sp\u00e9cifi\u00e9 : {0}" },
        { "launch.error.errorcoderesponse-known", "Code d''erreur {1} ({2}) retourn\u00e9 par le serveur pendant l''acc\u00e8s \u00e0 la ressource : {0}" },
        { "launch.error.errorcoderesponse-unknown", "Code d''erreur 99 (erreur inconnue) retourn\u00e9 par le serveur pendant l''acc\u00e8s \u00e0 la ressource : {0}" },
        { "launch.error.failedexec", "Impossible de lancer la version {0} de Java Runtime Environment" },
        { "launch.error.failedloadingresource", "Impossible de charger la ressource : {0}" },
        { "launch.error.invalidjardiff", "Impossible d''appliquer une mise \u00e0 jour incr\u00e9mentielle pour la ressource : {0}" },
        { "launch.error.jarsigning-badsigning", "Impossible de v\u00e9rifier une signature dans la ressource : {0}" },
        { "launch.error.jarsigning-missingentry", "Entr\u00e9e sign\u00e9e manquante dans la ressource : {0}" },
        { "launch.error.jarsigning-missingentryname", "Entr\u00e9e sign\u00e9e manquante : {0}" },
        { "launch.error.jarsigning-multicerts", "Plusieurs certificats utilis\u00e9s pour signer la ressource : {0}" },
        { "launch.error.jarsigning-multisigners", "Plusieurs signatures dans une entr\u00e9e de la ressource : {0}" },
        { "launch.error.jarsigning-unsignedfile", "D\u00e9tection d''une entr\u00e9e non sign\u00e9e dans la ressource : {0}" },
        { "launch.error.missingfield", "Il manque le champ obligatoire suivant dans le fichier de lancement : {0}" },
        { "launch.error.missingfield-signedjnlp", "Il manque le champ obligatoire suivant dans le fichier de lancement sign\u00e9 : {0}" },
        { "launch.error.missingjreversion", "Aucune version de JRE n'a \u00e9t\u00e9 trouv\u00e9e dans le fichier de lancement de ce syst\u00e8me" },
        { "launch.error.missingversionresponse", "Il manque le champ de version dans la r\u00e9ponse envoy\u00e9e par le serveur pendant l''acc\u00e8s \u00e0 la ressource : {0}" },
        { "launch.error.multiplehostsreferences", "H\u00f4tes multiples r\u00e9f\u00e9renc\u00e9s dans les ressources" },
        { "launch.error.nativelibviolation", "L'utilisation de biblioth\u00e8ques natives exige un acc\u00e8s sans restriction au syst\u00e8me" },
        { "launch.error.noJre", "L'application a demand\u00e9 une version de la plate-forme JRE qui n'est pas install\u00e9e localement pour l'instant. Java Web Start n'a pas pu t\u00e9l\u00e9charger et installer automatiquement la version requise. Vous devez installer cette version de JRE manuellement.\n\n" },
        { "launch.error.wont.download.jre", "L''application a demand\u00e9 une version de la plate-forme JRE (version {0}) qui n''est pas install\u00e9e localement pour l''instant. Java Web Start n''a pas \u00e9t\u00e9 autoris\u00e9 \u00e0 t\u00e9l\u00e9charger et \u00e0 installer automatiquement la version requise. Vous devez installer cette version de JRE manuellement." },
        { "launch.error.cant.download.jre", "L''application a demand\u00e9 une version de la plate-forme JRE (version {0}) qui n''est pas install\u00e9e localement pour l''instant. Java Web Start n''a pas pu t\u00e9l\u00e9charger et installer automatiquement la version requise. Vous devez installer cette version de JRE manuellement." },
        { "launch.error.cant.access.system.cache", "L'utilisateur courant n'a pas d'acc\u00e8s en \u00e9criture au cache du syst\u00e8me." },
	{ "launch.error.cant.access.user.cache", "L'utilisateur courant n'a pas d'acc\u00e8s en \u00e9criture au cache." },
        { "launch.error.noappresources", "Aucune ressource d'application n'est sp\u00e9cifi\u00e9e pour cette plate-forme. Contactez le fournisseur de l'application pour vous assurer de la compatibilit\u00e9 de la plate-forme." },
        { "launch.error.nomainclass", "Impossible de trouver la classe principale {0} dans {1}" },
        { "launch.error.nomainclassspec", "Aucune classe principale n'a \u00e9t\u00e9 sp\u00e9cifi\u00e9e pour l'application" },
        { "launch.error.nomainjar", "Aucun fichier JAR principal n'a \u00e9t\u00e9 sp\u00e9cifi\u00e9." },
        { "launch.error.nonstaticmainmethod", "La m\u00e9thode main() doit \u00eatre statique" },
        { "launch.error.offlinemissingresource", "Impossible d'ex\u00e9cuter l'application hors ligne, car certaines ressources requises n'ont pas \u00e9t\u00e9 t\u00e9l\u00e9charg\u00e9es et install\u00e9es localement" },
        { "launch.error.parse" , "Impossible d'analyser le fichier de lancement. Erreur \u00e0 la ligne {0, number }" },
        { "launch.error.parse-signedjnlp" , "Impossible d'analyser le fichier de lancement sign\u00e9. Erreur \u00e0 la ligne {0, number }" },
        { "launch.error.resourceID", "{0}" },
        { "launch.error.resourceID-version", "({0}, {1})" },
        { "launch.error.singlecertviolation", "Les ressources JAR d\u00e9finies dans le fichier JNLP n'ont pas \u00e9t\u00e9 sign\u00e9es \u00e0 l'aide du m\u00eame certificat" },
        { "launch.error.toomanyargs", "Trop d''arguments fournis : {0}" },
        { "launch.error.unsignedAccessViolation", "Une application non sign\u00e9e demande un acc\u00e8s illimit\u00e9 au syst\u00e8me" },
        { "launch.error.unsignedResource", "Ressource non sign\u00e9e : {0}" },
        { "launch.estimatedTimeLeft", "Temps restant estim\u00e9 : {0,number,00}:{1,number,00}:{2,number,00}" },
        { "launch.extensiondownload", "T\u00e9l\u00e9chargement du descripteur d''extension ({0} restants)" },
        { "launch.extensiondownload-name", "T\u00e9l\u00e9chargement du descripteur {0} ({1} restants)" },
        { "launch.initializing", "Initialisation..." },
        { "launch.launchApplication", "Lancement de l'application..." },
        { "launch.launchInstaller", "Lancement du programme d'installation..." },
        { "launch.launchingExtensionInstaller", "Ex\u00e9cution du programme d'installation. Veuillez patienter..." },
        { "launch.loadingNetProgress", "Lecture de {0}" },
        { "launch.loadingNetProgressPercent", "Lecture de {0} sur {1} ({2}%)" },
        { "launch.loadingNetStatus", "Chargement de {0} \u00e0 partir de {1}" },
        { "launch.loadingResourceFailed", "Echec du chargement de la ressource" },
        { "launch.loadingResourceFailedSts", "{0} requis" },
        { "launch.patchingStatus", "Correction de {0} \u00e0 partir de {1}" },
        { "launch.progressScreen", "Recherche de la derni\u00e8re version..." },
        { "launch.stalledDownload", "Attente des donn\u00e9es..." },
        { "launch.validatingProgress", "Balayage des entr\u00e9es ({0}% termin\u00e9)" },
        { "launch.validatingStatus", "Validation de {0} \u00e0 partir de {1}" },
        { "launcherrordialog.abort", "Abandonner" },
        { "launcherrordialog.abortMnemonic", "VK_A" },
        { "launcherrordialog.brief.continue", "Impossible de poursuivre l'ex\u00e9cution" },
        { "launcherrordialog.brief.details", "D\u00e9tails" },
        { "launcherrordialog.brief.message", "Impossible de lancer l'application sp\u00e9cifi\u00e9e." },
        { "launcherrordialog.import.brief.message", "Impossible d'importer l'application sp\u00e9cifi\u00e9e." },
        { "launcherrordialog.brief.messageKnown", "Impossible de lancer {0}." },
        { "launcherrordialog.import.brief.messageKnown", "Impossible d''importer {0}." },
        { "launcherrordialog.brief.ok", "OK" },
        { "launcherrordialog.brief.title", "Java Web Start - {0}" },
        { "launcherrordialog.consoleTab", "Console" },
        { "launcherrordialog.errorcategory", "Cat\u00e9gorie : {0}\n\n" },
        { "launcherrordialog.errorintro", "Une erreur est survenue au cours du lancement ou de l'ex\u00e9cution de l'application.\n\n" },
        { "launcherrordialog.import.errorintro", "Une erreur est survenue au cours de l'importation de l'application.\n\n" },
        { "launcherrordialog.errormsg", "{0}" },
        { "launcherrordialog.errortitle", "Titre : {0}\n" },
        { "launcherrordialog.errorvendor", "Fournisseur : {0}\n" },
        { "launcherrordialog.exceptionTab", "Exception" },
        { "launcherrordialog.generalTab", "G\u00e9n\u00e9ral" },
        { "launcherrordialog.genericerror", "Exception inattendue : {0}" },
        { "launcherrordialog.jnlpMainTab", "Fichier de lancement principal" },
        { "launcherrordialog.jnlpTab", "Fichier de lancement" },
        { "launcherrordialog.title", "Java Web Start - {0}" },
        { "launcherrordialog.wrappedExceptionTab", "Exception boucl\u00e9e" },
        { "uninstall.failedMessage", "Impossible de d\u00e9sinstaller enti\u00e8rement l'application." },
        { "uninstall.failedMessageTitle", "D\u00e9sinstaller" },
        { "install.alreadyInstalled", "Il existe d\u00e9j\u00e0 un raccourci vers {0}. Voulez-vous poursuivre l''op\u00e9ration ?" },
        { "install.alreadyInstalledTitle", "Cr\u00e9er un raccourci..." },
        { "install.desktopShortcutName", "{0}" },
        { "install.installFailed", "Impossible de cr\u00e9er un raccourci vers {0}." },
        { "install.installFailedTitle", "Cr\u00e9er un raccourci" },
        { "install.startMenuShortcutName", "{0}" },
	{ "install.startMenuUninstallShortcutName", "D\u00e9sinstaller {0}" },
        { "install.uninstallFailed", "Impossible de supprimer les raccourcis vers {0}. Recommencez." },
        { "install.uninstallFailedTitle", "Supprimer les raccourcis" },
	// Mandatory Enterprize configuration not available.
	{ "enterprize.cfg.mandatory" ,"Vous ne pouvez pas ex\u00e9cuter ce programme, car le fichier deployment.config de votre syst\u00e8me indique qu''une version Enterprise du fichier de configuration est requise. Or, le fichier {0} requis n''est pas disponible." },
	// Jnlp Cache Viewer:
	{ "jnlp.viewer.title", "Visualiseur du cache de l'application Java" },
	{ "jnlp.viewer.all", "Tout" },
	{ "jnlp.viewer.type", "{0}" },
	{ "jnlp.viewer.totalSize",  "Taille de toutes les ressources : {0}" },
        { "jnlp.viewer.emptyCache", "Le cache {0} est vide"},
        { "jnlp.viewer.noCache", "Le cache syst\u00e8me n'est pas configur\u00e9"},

	{ "jnlp.viewer.remove.btn.mnemonic", "VK_S" },
	{ "jnlp.viewer.launch.offline.btn.mnemonic", "VK_H" },
	{ "jnlp.viewer.launch.online.btn.mnemonic", "VK_N" },
	{ "jnlp.viewer.file.menu.mnemonic", "VK_F" },
	{ "jnlp.viewer.edit.menu.mnemonic", "VK_E" },
	{ "jnlp.viewer.app.menu.mnemonic", "VK_A" },
	{ "jnlp.viewer.view.menu.mnemonic", "VK_H" },
	{ "jnlp.viewer.help.menu.mnemonic", "VK_D" },

	{ "jnlp.viewer.cpl.mi.mnemonic", "VK_C" },
	{ "jnlp.viewer.exit.mi.mnemonic", "VK_Q" },

	{ "jnlp.viewer.reinstall.mi.mnemonic", "VK_R" },
	{ "jnlp.viewer.preferences.mi.mnemonic", "VK_P" },

	{ "jnlp.viewer.launch.offline.mi.mnemonic", "VK_H" },
	{ "jnlp.viewer.launch.online.mi.mnemonic", "VK_N" },
	{ "jnlp.viewer.install.mi.mnemonic", "VK_I" },
	{ "jnlp.viewer.uninstall.mi.mnemonic", "VK_D" },
	{ "jnlp.viewer.remove.mi.mnemonic", "VK_S" },
	{ "jnlp.viewer.show.mi.mnemonic", "VK_F" },
	{ "jnlp.viewer.browse.mi.mnemonic", "VK_W" },

	{ "jnlp.viewer.view.0.mi.mnemonic", "VK_T" },
	{ "jnlp.viewer.view.1.mi.mnemonic", "VK_A" },
	{ "jnlp.viewer.view.2.mi.mnemonic", "VK_P" },
	{ "jnlp.viewer.view.3.mi.mnemonic", "VK_B" },
	{ "jnlp.viewer.view.4.mi.mnemonic", "VK_I" },

	{ "jnlp.viewer.about.mi.mnemonic", "VK_D" },
	{ "jnlp.viewer.help.java.mi.mnemonic", "VK_J" },
	{ "jnlp.viewer.help.jnlp.mi.mnemonic", "VK_N" },

	{ "jnlp.viewer.remove.btn", "Supprimer" },
	{ "jnlp.viewer.remove.1.btn", "Supprimer les {0} s\u00e9lectionn\u00e9s" },
	{ "jnlp.viewer.remove.2.btn", "Supprimer les entr\u00e9es s\u00e9lectionn\u00e9es" },
	{ "jnlp.viewer.uninstall.btn", "D\u00e9sinstaller" },
	{ "jnlp.viewer.launch.offline.btn", "Lancer hors ligne" },
	{ "jnlp.viewer.launch.online.btn", "Lancer en ligne" },

        { "jnlp.viewer.file.menu", "Fichier" },
        { "jnlp.viewer.edit.menu", "Edition" },
        { "jnlp.viewer.app.menu", "Application" },
        { "jnlp.viewer.view.menu", "Affichage" },
        { "jnlp.viewer.help.menu", "Aide" },

	{ "jnlp.viewer.cpl.mi", "Lancer le panneau de configuration Java" },
	{ "jnlp.viewer.exit.mi", "Quitter" },

	{ "jnlp.viewer.reinstall.mi", "R\u00e9installer ..." },
	{ "jnlp.viewer.preferences.mi", "Pr\u00e9f\u00e9rences ..." },

	{ "jnlp.viewer.launch.offline.mi", "Lancer hors ligne" },
	{ "jnlp.viewer.launch.online.mi", "Lancer en ligne" },
	{ "jnlp.viewer.install.mi", "Installer les raccourcis" },
	{ "jnlp.viewer.uninstall.mi", "D\u00e9sinstaller les raccourcis" },
        { "jnlp.viewer.remove.0.mi", "Supprimer" },
	{ "jnlp.viewer.remove.mi", "Supprimer {0}" },
	{ "jnlp.viewer.show.mi", "Afficher le descripteur JNLP" },
	{ "jnlp.viewer.browse.mi", "Parcourir la page Web" },

	{ "jnlp.viewer.view.0.mi", "Tous les types" },
	{ "jnlp.viewer.view.1.mi", "Applications" },
	{ "jnlp.viewer.view.2.mi", "Applets" },
	{ "jnlp.viewer.view.3.mi", "Biblioth\u00e8ques" },
	{ "jnlp.viewer.view.4.mi", "Programmes d'installation" },

        { "jnlp.viewer.view.0", "Tous les types" },
        { "jnlp.viewer.view.1", "Applications" },
        { "jnlp.viewer.view.2", "Applets" },
        { "jnlp.viewer.view.3", "Biblioth\u00e8que" },
        { "jnlp.viewer.view.4", "Programmes d'installation" },

	{ "jnlp.viewer.about.mi", "A propos de l'application" },
	{ "jnlp.viewer.help.java.mi", "Page d'accueil de J2SE" },
	{ "jnlp.viewer.help.jnlp.mi", "Page d'accueil de JNLP" },

        { "jnlp.viewer.app.column", "Application" },
        { "jnlp.viewer.vendor.column", "Fournisseur" },
        { "jnlp.viewer.type.column", "Type" },
        { "jnlp.viewer.size.column", "Taille" },
        { "jnlp.viewer.date.column", "Date" },
        { "jnlp.viewer.status.column", "Etat" },

        { "jnlp.viewer.app.column.tooltip", "Ic\u00f4ne et titre de cette application, applet ou extension" },
        { "jnlp.viewer.vendor.column.tooltip", "Soci\u00e9t\u00e9 d\u00e9ployant cet \u00e9l\u00e9ment" },
        { "jnlp.viewer.type.column.tooltip", "Type de cet \u00e9l\u00e9ment" },
        { "jnlp.viewer.size.column.tooltip", "Taille de cet \u00e9l\u00e9ment et de toutes ses ressources" },
        { "jnlp.viewer.date.column.tooltip", "Date de la derni\u00e8re ex\u00e9cution de cette application, de cette applet ou de ce programme d'installation" },
        { "jnlp.viewer.status.column.tooltip", "Ic\u00f4ne indiquant comment cet \u00e9l\u00e9ment peut \u00eatre lanc\u00e9, le cas \u00e9ch\u00e9ant" },

        { "jnlp.viewer.application", "Application" },
        { "jnlp.viewer.applet", "Applet" },
        { "jnlp.viewer.extension", "Biblioth\u00e8que" },
        { "jnlp.viewer.installer", "Programme d'installation" },
        { "jnlp.viewer.offline.tooltip",
                "Cet \u00e9l\u00e9ment {0} peut \u00eatre lanc\u00e9 en ligne ou hors ligne" },
        { "jnlp.viewer.online.tooltip", "Cet \u00e9l\u00e9ment {0} peut \u00eatre lanc\u00e9 en ligne" },
        { "jnlp.viewer.norun1.tooltip", 
                "Cet \u00e9l\u00e9ment {0} peut \u00eatre lanc\u00e9 uniquement \u00e0 partir d''un navigateur Web" },
        { "jnlp.viewer.norun2.tooltip", "Impossible \u00e0 lancer les extensions" },

	{ "jnlp.viewer.show.title", "Descripteur JNLP associ\u00e9 \u00e0 {0}" },

	{ "jnlp.viewer.removing", "Suppression ..." },
	{ "jnlp.viewer.launching", "Lancement ..." },
	{ "jnlp.viewer.browsing", "Lancement du navigateur ..." },
	{ "jnlp.viewer.sorting", "Tri des entr\u00e9es ..." },
	{ "jnlp.viewer.searching", "Recherche des entr\u00e9es ..." },
        { "jnlp.viewer.installing", "Installation..." },

        { "jnlp.viewer.reinstall.title", "R\u00e9installer les applications JNLP supprim\u00e9es" },
	{ "jnlp.viewer.reinstallBtn", "R\u00e9installer les applications s\u00e9lectionn\u00e9es" },
	{ "jnlp.viewer.reinstallBtn.mnemonic", "VK_R" },
        { "jnlp.viewer.closeBtn", "Fermer" },
        { "jnlp.viewer.closeBtn.mnemonic", "VK_F" },

	{ "jnlp.viewer.reinstall.column.title", "Titre :" },
	{ "jnlp.viewer.reinstall.column.location", "Emplacement :" },

	// cache size warning
	{ "jnlp.cache.warning.title", "Avertissement - taille du cache JNLP" },
        { "jnlp.cache.warning.message" ,"Avertissement : \n\nVous avez d\u00e9pass\u00e9 la quantit\u00e9 d''espace disque recommand\u00e9e pour\nles applications et ressources JNLP de votre cache.\n\nEspace disque utilis\u00e9 : {0}\nLimite recommand\u00e9e : {1}\n\nUtilisez le panneau de configuration Java pour supprimer certaines \napplications ou ressources, ou pour d\u00e9finir une limite sup\u00e9rieure." },

        // Control Panel
        { "control.panel.title", "Panneau de configuration Java" },
        { "control.panel.general", "G\u00e9n\u00e9ral" },
        { "control.panel.security", "S\u00e9curit\u00e9" },
        { "control.panel.java", "Java" },
        { "control.panel.update", "Mise \u00e0 jour" },
        { "control.panel.advanced", "Avanc\u00e9" },

        // Common Strings used in different panels.
        { "common.settings", "Param\u00e8tres" },
        { "common.ok_btn", "OK" },
        { "common.ok_btn.mnemonic", "VK_O" },
        { "common.cancel_btn", "Annuler" },
        { "common.cancel_btn.mnemonic", "VK_A" },
        { "common.apply_btn", "Appliquer" },
        { "common.apply_btn.mnemonic", "VK_P" },
        { "common.add_btn", "Ajouter" },
        { "common.add_btn.mnemonic", "VK_J" },
        { "common.remove_btn", "Supprimer" },
        { "common.remove_btn.mnemonic", "VK_S" },

        // Network Settings Dialog
        { "network.settings.dlg.title", "Param\u00e8tres r\u00e9seau" },
        { "network.settings.dlg.border_title", " Param\u00e8tres du proxy r\u00e9seau " },
        { "network.settings.dlg.browser_rbtn", "Utiliser les param\u00e8tres du navigateur" },
        { "browser_rbtn.mnemonic", "VK_N" },
        { "network.settings.dlg.manual_rbtn", "Utiliser le serveur proxy" },
        { "manual_rbtn.mnemonic", "VK_P" },
        { "network.settings.dlg.address_lbl", "Adresse:" },
        { "network.settings.dlg.port_lbl", "Port :" },
        { "network.settings.dlg.advanced_btn", "Param\u00e8tres avanc\u00e9s..." },
        { "network.settings.dlg.advanced_btn.mnemonic", "VK_M" },
        { "network.settings.dlg.bypass_text", "Ignorer le serveur proxy pour les adresses locales" },
        { "network.settings.dlg.bypass.mnemonic", "VK_I" },
        { "network.settings.dlg.autoconfig_rbtn", "Utiliser le script de configuration de proxy automatique" },
        { "autoconfig_rbtn.mnemonic", "VK_T" },
        { "network.settings.dlg.location_lbl", "Emplacement du script : " },
        { "network.settings.dlg.direct_rbtn", "Connexion directe" },
        { "direct_rbtn.mnemonic", "VK_D" },
        { "network.settings.dlg.browser_text", "La configuration automatique risque de remplacer les param\u00e8tres d\u00e9finis manuellement. Pour garantir l'utilisation de ces derniers, d\u00e9sactivez la configuration automatique." },
        { "network.settings.dlg.proxy_text", "Ecraser les param\u00e8tres proxy du navigateur" },
        { "network.settings.dlg.auto_text", "Utiliser le script de configuration de proxy automatique situ\u00e9 \u00e0 l'emplacement d\u00e9fini" },
        { "network.settings.dlg.none_text", "Utiliser la connexion directe" },

        // Advanced Network Settings Dialog
        { "advanced.network.dlg.title", "Param\u00e8tres r\u00e9seau avanc\u00e9s" },
        { "advanced.network.dlg.servers", " Serveurs " },
        { "advanced.network.dlg.type", "Type" },
        { "advanced.network.dlg.http", "HTTP :" },
        { "advanced.network.dlg.secure", "S\u00e9curis\u00e9 :" },
        { "advanced.network.dlg.ftp", "FTP :" },
        { "advanced.network.dlg.socks", "Socks :" },
        { "advanced.network.dlg.proxy_address", "Adresse du proxy" },
        { "advanced.network.dlg.port", "Port" },
        { "advanced.network.dlg.same_proxy", " Utiliser le m\u00eame serveur proxy pour tous les protocoles" },
        { "advanced.network.dlg.same_proxy.mnemonic", "VK_U" },
        { "advanced.network.dlg.exceptions", " Exceptions " },
        { "advanced.network.dlg.no_proxy", " Ne pas utiliser le serveur proxy pour les adresses commen\u00e7ant par" },
        { "advanced.network.dlg.no_proxy_note", " S\u00e9parer les entr\u00e9es par un point-virgule (;)" },

        // DeleteFilesDialog
        { "delete.files.dlg.title", "Supprimer les fichiers temporaires" },
        { "delete.files.dlg.temp_files", "Supprimer les fichiers temporaires suivants ?" },
        { "delete.files.dlg.applets", "Applets t\u00e9l\u00e9charg\u00e9s" },
        { "delete.files.dlg.applications", "Applications t\u00e9l\u00e9charg\u00e9es" },
        { "delete.files.dlg.other", "Autres fichiers" },

	// General
	{ "general.cache.border.text", " Fichiers Internet temporaires " },
	{ "general.cache.delete.text", "Supprimer les fichiers..." },
        { "general.cache.delete.text.mnemonic", "VK_S" },
	{ "general.cache.settings.text", "Param\u00e8tres..." },
        { "general.cache.settings.text.mnemonic", "VK_M" },
	{ "general.cache.desc.text", "Les fichiers utilis\u00e9s dans les applications Java sont stock\u00e9s dans un dossier particulier afin de faciliter leur ex\u00e9cution ult\u00e9rieure. Seuls les utilisateurs avanc\u00e9s doivent supprimer ces fichiers ou modifier ces param\u00e8tres." },
	{ "general.network.border.text", " Param\u00e8tres r\u00e9seau " },
	{ "general.network.settings.text", "Param\u00e8tres r\u00e9seau..." },
        { "general.network.settings.text.mnemonic", "VK_R" },
	{ "general.network.desc.text", "Les param\u00e8tres r\u00e9seau sont utilis\u00e9s lors de l'\u00e9tablissement de la connexion. Par d\u00e9faut, Java utilisera les param\u00e8tres r\u00e9seau de votre navigateur web. Seuls des utilisateurs avanc\u00e9s doivent modifier ces param\u00e8tres." },
        { "general.about.border", "A propos de" },
        { "general.about.text" ,"Afficher les informations relatives \u00e0 la version du panneau de configuration Java." },
	{ "general.about.btn", "A propos de..." },
	{ "general.about.btn.mnemonic", "VK_D" },

	// Security
	{ "security.certificates.border.text", " Certificats " },
	{ "security.certificates.button.text", "Certificats..." },
        { "security.certificates.button.mnemonic", "VK_E" },
	{ "security.certificates.desc.text", "Utilisez des certificats pour identifier sans erreur possible votre propre signature, des certifications, des autorit\u00e9s et des \u00e9diteurs." },
	{ "security.policies.border.text", " Politiques " },
	{ "security.policies.advanced.text", "Param\u00e8tres avanc\u00e9s..." },
        { "security.policies.advanced.mnemonic", "VK_V" },
	{ "security.policies.desc.text", "Utilisez des politiques de s\u00e9curit\u00e9 pour contr\u00f4ler les dispositifs de s\u00e9curit\u00e9 visant \u00e0 prot\u00e9ger les applications et les applets." },

	// Update
	{ "update.notify.border.text", " Notification de mise \u00e0 jour " }, // this one is not currently used.  See update panel!!!
	{ "update.updatenow.button.text", "Mettre \u00e0 jour maintenant" },
	{ "update.updatenow.button.mnemonic", "VK_M" },
	{ "update.advanced.button.text", "Param\u00e8tres avanc\u00e9s..." },
	{ "update.advanced.button.mnemonic", "VK_V" },
	{ "update.desc.text", "Gr\u00e2ce au m\u00e9canisme de mise \u00e0 jour Java Update, vous \u00eates assur\u00e9 de disposer de la derni\u00e8re version de la plate-forme Java. Les options ci-dessous vous permettent de g\u00e9rer les modes d'obtention et d'application des mises \u00e0 jour." },
        { "update.notify.text", "M'avertir :" },
        { "update.notify_install.text", "Avant l'installation" },
        { "update.notify_download.text", "Avant le t\u00e9l\u00e9chargement et l'installation" },
        { "update.autoupdate.text", "Automatiser la d\u00e9tection de mises \u00e0 jour" },
        { "update.advanced_title.text", "Param\u00e8tres avanc\u00e9s de mise \u00e0 jour automatique" },
        { "update.advanced_title1.text", "S\u00e9lectionnez la fr\u00e9quence et l'heure de d\u00e9tection des mises \u00e0 jour." },
        { "update.advanced_title2.text", "Fr\u00e9quence" },
        { "update.advanced_title3.text", "Heure" },
        { "update.advanced_desc1.text", "V\u00e9rifier chaque jour \u00e0 {0}" },
        { "update.advanced_desc2.text", "V\u00e9rifier chaque {0} \u00e0 {1}" },
        { "update.advanced_desc3.text", "V\u00e9rifier le {0} de chaque mois \u00e0 {1}" },
        { "update.check_daily.text", "Tous les jours" },
        { "update.check_weekly.text", "Toutes les semaines" },
        { "update.check_monthly.text", "Tous les mois" },
        { "update.check_date.text", "Jour :" },
        { "update.check_day.text", "Chaque :" },
        { "update.check_time.text", "A :" },
        { "update.lastrun.text", "Java Update a \u00e9t\u00e9 ex\u00e9cut\u00e9 pour la derni\u00e8re fois \u00e0 {0} le {1}." },
        { "update.desc_autooff.text", "Cliquez sur le bouton Mettre \u00e0 jour maintenant ci-dessous pour d\u00e9tecter les \u00e9ventuelles mises \u00e0 jour. Une ic\u00f4ne s'affiche sur la barre d'\u00e9tat syst\u00e8me lorsqu'une mise \u00e0 jour est disponible. Placez le curseur sur l'ic\u00f4ne pour afficher l'\u00e9tat de la mise \u00e0 jour." },
        { "update.desc_check_daily.text", "Java Update v\u00e9rifiera la pr\u00e9sence de mises \u00e0 jour tous les jours \u00e0 {0}. " },
        { "update.desc_check_weekly.text", "Java Update v\u00e9rifiera la pr\u00e9sence de mises \u00e0 jour chaque {0} \u00e0 {1}. " },
        { "update.desc_check_monthly.text", "Java Update v\u00e9rifiera la pr\u00e9sence de mises \u00e0 jour chaque {0} de chaque mois \u00e0 {1}. " },
        { "update.desc_systrayicon.text", "Une ic\u00f4ne s'affiche sur la barre d'\u00e9tat syst\u00e8me lorsqu'une mise \u00e0 jour est disponible. Placez le curseur sur l'ic\u00f4ne pour afficher l'\u00e9tat de la mise \u00e0 jour. " },
        { "update.desc_notify_install.text", "Vous serez inform\u00e9 avant toute installation de mise \u00e0 jour sur votre syst\u00e8me." },
        { "update.desc_notify_download.text", "Vous serez inform\u00e9 avant tout t\u00e9l\u00e9chargement et avant toute installation de mise \u00e0 jour sur votre syst\u00e8me." },
	{ "update.launchbrowser.error.text", "Impossible de lancer la fonction de recherche de mises \u00e0 jour Java Update Checker. Pour obtenir la derni\u00e8re version de Java Update, consultez le site http://java.sun.com/getjava/javaupdate" },
	{ "update.launchbrowser.error.caption", "Erreur - Mise \u00e0 jour" },

        // CacheSettingsDialog strings:
        { "cache.settings.dialog.delete_btn", "Supprimer les fichiers..." },
        { "cache.settings.dialog.delete_btn.mnemonic", "VK_S" },
        { "cache.settings.dialog.view_jws_btn", "Afficher les applications..." },
        { "cache.settings.dialog.view_jws_btn.mnemonic", "VK_F" },
        { "cache.settings.dialog.view_jpi_btn", "Afficher les applets..." },
        { "cache.settings.dialog.view_jpi_btn.mnemonic", "VK_C" },
        { "cache.settings.dialog.chooser_title", "Emplacement des fichiers temporaires" },
        { "cache.settings.dialog.select", "S\u00e9lectionner" },
        { "cache.settings.dialog.select_tooltip", "Utiliser l'emplacement s\u00e9lectionn\u00e9" },
        { "cache.settings.dialog.select_mnemonic", "S" },
        { "cache.settings.dialog.title", "Param\u00e8tres des fichiers temporaires" },
        { "cache.settings.dialog.cache_location", "Emplacement :" },
        { "cache.settings.dialog.change_btn", "Modifier..." },
        { "cache.settings.dialog.change_btn.mnemonic", "VK_M" },
        { "cache.settings.dialog.disk_space", "Espace disque \u00e0 utiliser :" },
        { "cache.settings.dialog.unlimited_btn", "Illimit\u00e9" },
        { "cache.settings.dialog.max_btn", "Maximum" },
        { "cache.settings.dialog.compression", "Compression Jar :" },
        { "cache.settings.dialog.none", "Aucune" },
        { "cache.settings.dialog.high", "Elev\u00e9e" },

	// JNLP File/MIME association dialog strings:
	{ "javaws.association.dialog.title", "Association JNLP/MIME" },
        { "javaws.association.dialog.exist.command", "existe d\u00e9j\u00e0 avec :\n{0}" },
	{ "javaws.association.dialog.exist", "existe d\u00e9j\u00e0." },
	{ "javaws.association.dialog.askReplace", "\nVoulez-vous vraiment utiliser {0} \u00e0 la place pour la traiter ?"},
	{ "javaws.association.dialog.ext", "Extensions de fichiers : {0}" },
        { "javaws.association.dialog.mime", "Type MIME : {0}" },
        { "javaws.association.dialog.ask", "Voulez-vous utiliser {0} pour traiter :" },
        { "javaws.association.dialog.existAsk", "ATTENTION ! Association avec :"},

        // Advanced panel strings:
        { "deployment.console.startup.mode", "Console Java" },
        { "deployment.console.startup.mode.SHOW", "Afficher la console" },
        { "deployment.console.startup.mode.SHOW.tooltip" ,"<html>D\u00e9marrer la console Java maximis\u00e9e</html>" },
        { "deployment.console.startup.mode.HIDE", "Masquer la console" },
        { "deployment.console.startup.mode.HIDE.tooltip" ,"<html>D\u00e9marrer la console Java minimis\u00e9e</html>" },
        { "deployment.console.startup.mode.DISABLE", "Ne pas lancer la console" },
        { "deployment.console.startup.mode.DISABLE.tooltip" ,"<html>La console Java ne d\u00e9marrera pas</html>" },
        { "deployment.trace", "Tra\u00e7age activ\u00e9" },
        { "deployment.trace.tooltip" ,"<html>Cr\u00e9er fichier de tra\u00e7age \u00e0 des fins de<br>d\u00e9bogage</html>" },
        { "deployment.log", "Consignation activ\u00e9e" },
	{ "deployment.log.tooltip" ,"<html>Cr\u00e9er fichier journal pour capturer<br>les erreurs</html>" },
        { "deployment.control.panel.log", "Consignation dans le panneau de configuration" },
        { "deployment.javapi.lifecycle.exception" ,"Afficher les exceptions du cycle de vie des applets" },
        { "deployment.javapi.lifecycle.exception.tooltip" ,"<html>Afficher la bo\u00eete de dialogue contenant les exceptions quand<br>des erreurs se produisent pendant le chargement d'applets<html>" },
        { "deployment.browser.vm.iexplorer", "Internet Explorer" },
        { "deployment.browser.vm.iexplorer.tooltip" ,"<html>Utiliser Sun Java avec balise APPLET<br>dans le navigateur Internet Explorer</html>" },
        { "deployment.browser.vm.mozilla",   "Mozilla et Netscape" },
        {"deployment.browser.vm.mozilla.tooltip" ,"<html>Utiliser Sun Java avec balise APPLET<br>dans le ou les navigateurs Mozilla ou Netscape</html>" },
        { "deployment.console.debugging", "D\u00e9bogage" },
	{ "deployment.browsers.applet.tag", "Prise en charge de la balise <APPLET>" },
        { "deployment.javaws.shortcut", "Cr\u00e9ation de raccourcis" },
        { "deployment.javaws.shortcut.ALWAYS", "Toujours autoriser" },
        { "deployment.javaws.shortcut.ALWAYS.tooltip" ,"<html>Toujours cr\u00e9er les raccourcis</html>" },
        { "deployment.javaws.shortcut.NEVER" , "Ne jamais autoriser" },
        { "deployment.javaws.shortcut.NEVER.tooltip", "<html>Ne pas cr\u00e9er de raccourcis</html>" },
        { "deployment.javaws.shortcut.ASK_USER", "Demander \u00e0 l'utilisateur" },
        { "deployment.javaws.shortcut.ASK_USER.tooltip", "<html>Demander \u00e0 l'utilisateur s'il faut, ou pas,<br>cr\u00e9er le raccourci</html>" },
        { "deployment.javaws.shortcut.ALWAYS_IF_HINTED", "Toujours autoriser si indiqu\u00e9" },
        { "deployment.javaws.shortcut.ALWAYS_IF_HINTED.tooltip", "<html>Toujours cr\u00e9er les raccourcis si l'application JNLP <br>est requise</html>" },
        { "deployment.javaws.shortcut.ASK_IF_HINTED", "Demander \u00e0 l'utilisateur si indiqu\u00e9" },
        { "deployment.javaws.shortcut.ASK_IF_HINTED.tooltip", "<html>Demander \u00e0 l'utilisateur s'il faut cr\u00e9er le raccourci si cela est<br>requis par l'application JNLP</html>" },
	{ "deployment.javaws.associations.NEVER", "Ne jamais autoriser" },
        { "deployment.javaws.associations.NEVER.tooltip", "<html>Ne jamais cr\u00e9er d'association<br>extension fichier/MIME</html>" },
        { "deployment.javaws.associations.ASK_USER", "Demander \u00e0 l'utilisateur" },
        { "deployment.javaws.associations.ASK_USER.tooltip", "<html>Demander \u00e0 l'utilisateur avant de cr\u00e9er une association<br>extension fichier/MIME</html>" },
        { "deployment.javaws.associations.REPLACE_ASK", "Demander \u00e0 l'utilisateur pour tout remplacement" },
        { "deployment.javaws.associations.REPLACE_ASK.tooltip", "<html>Demander \u00e0 l'utilisateur uniquement en cas de remplacement de <br>l'association extension de fichier/MIME existante</html>" },
        { "deployment.javaws.associations.NEW_ONLY", "Autoriser en cas de nouvelle association" },
        { "deployment.javaws.associations.NEW_ONLY.tooltip", "<html>Toujours cr\u00e9er uniquement en cas de nouvelle association<br>extension fichier/MIME</html>" },
        { "deployment.javaws.associations", "Association JNLP/MIME" },
        { "deployment.security.settings", "S\u00e9curit\u00e9" },
        { "deployment.security.askgrantdialog.show" ,"Permettre \u00e0 l'utilisateur d'octroyer des autorisations \u00e0 un contenu sign\u00e9" },
        { "deployment.security.askgrantdialog.notinca" ,"Permettre \u00e0 l'utilisateur d'octroyer des autorisations \u00e0 un contenu provenant d'une autorit\u00e9 non approuv\u00e9e" },
        { "deployment.security.browser.keystore.use" ,"Utiliser les certificats et les cl\u00e9s des param\u00e8tres du stockage des cl\u00e9s" },
        { "deployment.security.notinca.warning" ,"Avertir si l'autorit\u00e9 de certification ne peut pas \u00eatre v\u00e9rifi\u00e9e" },
        { "deployment.security.expired.warning" ,"Avertir si le certificat a expir\u00e9 ou n'est plus valide" },
        { "deployment.security.jsse.hostmismatch.warning" ,"Avertir en cas de non-concordance du certificat de site et du nom d'h\u00f4te" },
        { "deployment.security.sandbox.awtwarningwindow" ,"Afficher la banni\u00e8re d'avertissement de sandbox" },
        { "deployment.security.sandbox.jnlp.enhanced" ,"Autoriser l'utilisateur \u00e0 accepter les demandes de s\u00e9curit\u00e9 JNLP" },
        { "deploy.advanced.browse.title", "Choisir le fichier de lancement du navigateur par d\u00e9faut" },
        { "deploy.advanced.browse.select", "S\u00e9lectionner" },
        { "deploy.advanced.browse.select_tooltip", "Utiliser le fichier s\u00e9lectionn\u00e9 pour lancer le navigateur" },
        { "deploy.advanced.browse.select_mnemonic", "S" },
        { "deploy.advanced.browse.browse_btn", "Parcourir..." },
        { "deploy.advanced.browse.browse_btn.mnemonic", "VK_P" },
        { "deployment.browser.default", "Commande de lancement du navigateur par d\u00e9faut" },
        { "deployment.misc.label", "Divers" },
        { "deployment.system.tray.icon", "Placer l'ic\u00f4ne Java sur la barre d'\u00e9tat syst\u00e8me" },
        { "deployment.system.tray.icon.tooltip", "<html>S\u00e9lectionner cette option pour afficher l'ic\u00f4ne<br>de la tasse Java sur la barre d'\u00e9tat syst\u00e8me<br>quand Java est ex\u00e9cut\u00e9 dans le navigateur</html>" },

        //PluginJresDialog strings:
        { "jpi.jres.dialog.title", "Param\u00e8tres de Java Runtime" },
        { "jpi.jres.dialog.border", " Versions de Java Runtime " },
        { "jpi.jres.dialog.column1", "Nom du produit" },
        { "jpi.jres.dialog.column2", "Version" },
        { "jpi.jres.dialog.column3", "Emplacement" },
        { "jpi.jres.dialog.column4", "Param\u00e8tres d'ex\u00e9cution Java" },
        { "jpi.jdk.string", "JDK" },
        { "jpi.jre.string", "JRE" },
        { "jpi.jres.dialog.product.tooltip", "Choisissez JRE ou JDK comme nom de produit" },

        // AboutDialog strings:
        { "about.dialog.title", "A propos de Java" },

        // JavaPanel strings:
        { "java.panel.plugin.border" ," Param\u00e8tres de l'applet Java Runtime " },
        { "java.panel.plugin.text" ,"Les param\u00e8tres d'ex\u00e9cution sont utilis\u00e9s lors du lancement d'un applet dans le navigateur." },
        { "java.panel.jpi_view_btn", "Afficher..." },
        { "java.panel.javaws_view_btn", "Afficher..." },
        { "java.panel.jpi_view_btn.mnemonic", "VK_F" },
        { "java.panel.javaws_view_btn.mnemonic", "VK_C" },
        { "java.panel.javaws.border" ," Param\u00e8tres de l'application Java Runtime " },
        { "java.panel.javaws.text" ,"Les param\u00e8tres d'ex\u00e9cution sont utilis\u00e9s lors du lancement d'une application ou d'un applet Java en utilisant le protocole JNLP (Java Network Launching Protocol)." },

        // Strings in the confirmation dialogs for APPLET tag in browsers.
        { "browser.settings.alert.text", "<html><b>Une version plus r\u00e9cente de Java Runtime Environment existe d\u00e9j\u00e0.</b></html>Internet Explorer dispose d\u00e9j\u00e0 d'une version ult\u00e9rieure de Java Runtime Environment. Voulez-vous la remplacer ?\n" },
        { "browser.settings.success.caption", "Op\u00e9ration r\u00e9ussie - Navigateur" },
        { "browser.settings.success.text", "<html><b>Modification des param\u00e8tres du navigateur</b></html>Les modifications seront prises en compte apr\u00e8s le red\u00e9marrage des navigateurs.\n" },
        { "browser.settings.fail.caption", "Avertissement - Navigateur" },
        { "browser.settings.fail.moz.text" ,"<html><b>Impossible de modifier les param\u00e8tres du navigateur</b></html>V\u00e9rifiez si Mozilla ou Netscape est install\u00e9 correctement sur le syst\u00e8me et/ou assurez-vous de b\u00e9n\u00e9ficier des autorisations permettant de modifier les param\u00e8tres syst\u00e8me.\n" },
        { "browser.settings.fail.ie.text" ,"<html><b>Impossible de modifier les param\u00e8tres du navigateur</b></html>Assurez-vous de b\u00e9n\u00e9ficier des autorisations permettant de modifier les param\u00e8tres syst\u00e8me.\n" },


        // Tool tip strings.
        { "cpl.ok_btn.tooltip" ,"<html>Permet de fermer le panneau de configuration et d'enregistrer<br>toutes les modifications apport\u00e9es</html>" },
        { "cpl.apply_btn.tooltip" ,"<html>Permet d'enregistrer toutes les modifications apport\u00e9es<br>sans fermer le panneau de configuration Java</html>" },
        { "cpl.cancel_btn.tooltip" ,"<html>Permet de fermer le panneau de configuration Java<br>sans enregistrer les modifications apport\u00e9es</html>" },
        { "network.settings.btn.tooltip" ,"<html>Modifier les param\u00e8tres de connexion Internet</html>" },
        { "temp.files.settings.btn.tooltip" ,"<html>Modifier les param\u00e8tres pour les fichiers temporaires</html>" },
        { "temp.files.delete.btn.tooltip" ,"<html>Supprimer les fichiers Java temporaires</html>" },
        { "delete.files.dlg.applets.tooltip" ,"<html>Activez cette option pour supprimer tous les<br>fichiers temporaires cr\u00e9\u00e9s par les applets Java</html>" },
        { "delete.files.dlg.applications.tooltip" ,"<html>Activez cette option pour supprimer tous les<br>fichiers temporaires cr\u00e9\u00e9s par des applications<br>Java Web Start</html>" },
        { "delete.files.dlg.other.tooltip" ,"<html>Activez cette option pour supprimer tous les autres<br>fichiers temporaires cr\u00e9\u00e9s par Java</html>" },
        { "delete.files.dlg.temp_files.tooltip" ,"<html>Les applications Java stockent des fichiers temporaires<br>sur votre ordinateur ; ceux-ci peuvent \u00eatre supprim\u00e9s<br>sans probl\u00e8me.<br><p>Certaines applications Java mettent plus de temps<br>\u00e0 d\u00e9marrer la premi\u00e8re fois que vous les ex\u00e9cutez<br>apr\u00e8s la suppression des fichiers temporaires.</html>" },
        { "cache.settings.dialog.view_jws_btn.tooltip" ,"<html>Permet d'afficher les fichiers temporaires cr\u00e9\u00e9s par<br>des applications Java Web Start</html>" },
        { "cache.settings.dialog.view_jpi_btn.tooltip" ,"<html>Permet d'afficher les fichiers temporaires cr\u00e9\u00e9s par<br>des applets Java</html>" },
        { "cache.settings.dialog.change_btn.tooltip" ,"<html>Sp\u00e9cifiez le r\u00e9pertoire destin\u00e9 \u00e0 stocker<br>les fichiers temporaires</html>" },
        { "cache.settings.dialog.unlimited_btn.tooltip" ,"<html>Permet de ne pas limiter la quantit\u00e9 d'espace disque<br>allou\u00e9e au stockage des fichiers temporaires</html>" },
        { "cache.settings.dialog.max_btn.tooltip" ,"<html>Indiquez la quantit\u00e9 d'espace disque maximale<br>\u00e0 allouer au stockage des fichiers temporaires.</html>" },
        { "cache.settings.dialog.compression.tooltip" ,"<html>Indiquez le taux de compression \u00e0 appliquer<br>aux fichiers JAR stock\u00e9s par les programmes Java<br>dans le r\u00e9pertoire des fichiers temporaires de votre syst\u00e8me<br><p>L'option \"Aucun\" permet d'acc\u00e9l\u00e9rer le d\u00e9marrage des<br>programmes Java, mais augmente la quantit\u00e9 d'espace disque<br>requise pour le stockage des programmes. Les valeurs<br>sup\u00e9rieures r\u00e9duisent la quantit\u00e9 d'espace disque n\u00e9cessaire, <br>en augmentant l\u00e9g\u00e8rement la dur\u00e9e de lancement.</html>" },
        { "common.ok_btn.tooltip" ,"<html>Permet d'enregistrer les modifications et de fermer la bo\u00eete de dialogue</html>" },
        { "common.cancel_btn.tooltip" ,"<html>Permet d'annuler les modifications et de fermer la bo\u00eete de dialogue</html>" },
        { "network.settings.advanced_btn.tooltip" ,"<html>Permet d'afficher et de modifier les param\u00e8tres avanc\u00e9s du proxy</html>" },
        { "security.certs_btn.tooltip" ,"<html>Permet d'importer, d'exporter ou de supprimer des certificats</html>" },
        { "cert.import_btn.tooltip" ,"<html>Permet d'importer un certificat qui ne<br>figure pas dans la liste</html>" },
        { "cert.export_btn.tooltip" ,"<html>Permet d'exporter le certificat s\u00e9lectionn\u00e9</html>" },
        { "cert.remove_btn.tooltip" ,"<html>Permet de supprimer le certificat s\u00e9lectionn\u00e9<br>de la liste</html>" },
        { "cert.details_btn.tooltip" ,"<html>Permet d'afficher des informations d\u00e9taill\u00e9es concernant<br>le certificat s\u00e9lectionn\u00e9</html>" },
        { "java.panel.jpi_view_btn.tooltip" ,"<html>Permet de modifier les param\u00e8tres d'ex\u00e9cution Java pour les applets</html>" },
        { "java.panel.javaws_view_btn.tooltip" ,"<html>Permet de modifier les param\u00e8tres d'ex\u00e9cution Java pour les applications</html>" },
        { "general.about.btn.tooltip" ,"<html>Permet d'afficher des informations relatives \u00e0 cette version<br>de J2SE Runtime Environment</html>" },
        { "update.notify_combo.tooltip" ,"<html>Permet de s\u00e9lectionner \u00e0 quel moment<br>vous devez \u00eatre averti des nouvelles<br>mises \u00e0 jour de Java</html>" },
        { "update.advanced_btn.tooltip" ,"<html>Permet de modifier la politique de planification<br>de la mise \u00e0 jour automatique</html>" },
        { "update.now_btn.tooltip" ,"<html>Permet de lancer Java Update pour rechercher<br>les derni\u00e8res mises \u00e0 jour de Java disponibles</html>" },
        { "vm.options.add_btn.tooltip" ,"<html>Permet d'ajouter une nouvelle version de JRE \u00e0 la liste</html>" },
        { "vm.options.remove_btn.tooltip" ,"<html>Permet de supprimer l'entr\u00e9e s\u00e9lectionn\u00e9e de la liste</html>" },
        { "vm.optios.ok_btn.tooltip" ,"<html>Permet d'enregistrer toutes les entr\u00e9es contenant<br>des informations sur le nom, la version et<br>l'emplacement du produit</html>" },
        { "jnlp.jre.find_btn.tooltip" ,"<html>Permet de rechercher une version de Java Runtime Environment<br>install\u00e9e sur votre syst\u00e8me</html>" },
        { "jnlp.jre.add_btn.tooltip" ,"<html>Permet d'ajouter une nouvelle entr\u00e9e \u00e0 la liste</html>" },
        { "jnlp.jre.remove_btn.tooltip" ,"<html>Permet de supprimer l'entr\u00e9e s\u00e9lectionn\u00e9e de la<br>liste des utilisateurs</html>" },


        // JaWS Auto Download JRE Prompt
        { "download.jre.prompt.title", "Autoriser le t\u00e9l\u00e9chargement JRE" },
        { "download.jre.prompt.text1" ,"L''application \"{0}\" requiert une version de JRE (version {1}) qui n''est pas install\u00e9e sur votre syst\u00e8me." },
        { "download.jre.prompt.text2" ,"Voulez-vous que Java Web Start t\u00e9l\u00e9charge et installe automatiquement cette version de JRE ?" },
        { "download.jre.prompt.okButton", "T\u00e9l\u00e9charger" },
        { "download.jre.prompt.okButton.acceleratorKey", new Integer(KeyEvent.VK_T)},
        { "download.jre.prompt.cancelButton", "Annuler" },
        { "download.jre.prompt.cancelButton.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "autoupdatecheck.buttonYes", "Oui" },
	{ "autoupdatecheck.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_O)},
	{ "autoupdatecheck.buttonNo", "Non" },
	{ "autoupdatecheck.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
	{ "autoupdatecheck.buttonAskLater", "Me demander ult\u00e9rieurement" },
	{ "autoupdatecheck.buttonAskLater.acceleratorKey", new Integer(KeyEvent.VK_D)},
        { "autoupdatecheck.caption", "Automatiser la d\u00e9tection de mises \u00e0 jour" },
        { "autoupdatecheck.message", "Java Update peut automatiquement mettre \u00e0 jour votre logiciel Java lorsque de nouvelles versions sont disponibles. Voulez-vous activer ce service ?" },
    };
}

