/*
* "@(#)Deployment_sv.java	1.28 04/07/16
*
* Copyright 2004 Sun Microsystems, Inc. All rights reserved.
* SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
*/

package com.sun.deploy.resources;

import java.util.ListResourceBundle;
import java.awt.event.KeyEvent;


/**
 * Swedish version of Deployment strings.
 *
 * @author Stanley Man-Kit Ho
 */

public final class Deployment_sv extends ListResourceBundle {

    public Object[][] getContents() {
	return contents;
    }

    static final Object[][] contents = {
        { "product.javapi.name", "Java Plug-in {0}" },
        { "product.javaws.name", "Java Web Start {0}" },

	{ "console.version", "Version" },
	{ "console.default_vm_version", "Standardversion f\u00f6r virtuell maskin " },
	{ "console.using_jre_version", "Anv\u00e4nder JRE-version" },
	{ "console.user_home", "Anv\u00e4ndarens hemkatalog" },
        { "console.caption", "Java-konsol" },
        { "console.clear", "Rensa" },
        { "console.clear.acceleratorKey", new Integer(KeyEvent.VK_R)},
        { "console.close", "St\u00e4ng" },
        { "console.close.acceleratorKey", new Integer(KeyEvent.VK_S) },
        { "console.copy", "Kopiera" },
        { "console.copy.acceleratorKey", new Integer(KeyEvent.VK_K) },
	{ "console.menu.text.top", "----------------------------------------------------\n" },
	{ "console.menu.text.c", "c:   t\u00f6m systemf\u00f6nster\n" },
	{ "console.menu.text.f", "f:   slutf\u00f6r objekt i slutf\u00f6ringsk\u00f6\n" },
	{ "console.menu.text.g", "g:   skr\u00e4pinsamling\n" },
	{ "console.menu.text.h", "h:   visa det h\u00e4r hj\u00e4lpmeddelandet\n" },
	{ "console.menu.text.j", "j:   dumpa jcov-data\n"},
	{ "console.menu.text.l", "l:   dumpa classloader-lista\n" },
	{ "console.menu.text.m", "m:   skriv ut minnesf\u00f6rbrukning\n" },
	{ "console.menu.text.o", "o:   utl\u00f6sarloggning\n" },
	{ "console.menu.text.p", "p:   ladda proxykonfiguration p\u00e5 nytt\n" },
	{ "console.menu.text.q", "q:   d\u00f6lj konsol\n" },
	{ "console.menu.text.r", "r:   ladda policykonfiguration p\u00e5 nytt\n" },
	{ "console.menu.text.s", "s:   dumpa system- och distributionsegenskaper\n" },
	{ "console.menu.text.t", "t:   dumpa tr\u00e5dlista\n" },
	{ "console.menu.text.v", "v:   dumpa tr\u00e5dstack\n" },
	{ "console.menu.text.x", "x:   t\u00f6m classloader-cache\n" },
	{ "console.menu.text.0", "0-5: ange sp\u00e5rningsniv\u00e5n till <n>\n" },
	{ "console.menu.text.tail", "----------------------------------------------------\n" },
	{ "console.done", "Klar." },
	{ "console.trace.level.0", "Sp\u00e5rningsniv\u00e5n angiven till 0: ingen ... klar." },
	{ "console.trace.level.1", "Sp\u00e5rningsniv\u00e5n angiven till 1: basic ... klar." },
	{ "console.trace.level.2", "Sp\u00e5rningsniv\u00e5n angiven till 2: basic, net ... klar." },
	{ "console.trace.level.3", "Sp\u00e5rningsniv\u00e5n angiven till 3: basic, net, security ... klar." },
	{ "console.trace.level.4", "Sp\u00e5rningsniv\u00e5n angiven till 4: basic, net, security, ext ... klar." },
	{ "console.trace.level.5", "Sp\u00e5rningsniv\u00e5n angiven till 5: allt ... klart." },
	{ "console.log", "Loggningen angiven till: " },
	{ "console.completed", " ... klar." },
	{ "console.dump.thread", "Dumpa tr\u00e5dlista ...\n" },
	{ "console.dump.stack", "Dumpa tr\u00e5dstack ...\n" },
	{ "console.dump.system.properties", "Dumpa systemegenskaper ...\n" },
	{ "console.dump.deployment.properties", "Dumpa distributionsegenskaper ...\n" },
	{ "console.clear.classloader", "T\u00f6m classloader-cachen ... klar." },
	{ "console.reload.policy", "Ladda policykonfiguration p\u00e5 nytt" },
	{ "console.reload.proxy", "Ladda proxykonfiguration p\u00e5 nytt ..." },
	{ "console.gc", "Skr\u00e4pinsamling" },
	{ "console.finalize", "Slutf\u00f6r objekt i slutf\u00f6ringsk\u00f6" },
	{ "console.memory", "Minne: {0}K	Ledigt: {1}K	({2}%)" },
	{ "console.jcov.error", "Jcov-k\u00f6rningsfel: kontrollera om du angett r\u00e4tt jcov-alternativ\n"},
	{ "console.jcov.info", "Jcov-data dumpades\n"},

	{ "https.dialog.caption", "Varning - HTTPS" },
	{ "https.dialog.text", "<html><b>V\u00e4rdnamn st\u00e4mmer ej \u00f6verens</b></html>V\u00e4rdnamnet i certifikatet f\u00f6r servers\u00e4kerhet st\u00e4mmer inte \u00f6verens med serverns namn.\n\nV\u00e4rdnamn f\u00f6r webbadressen: {0}\nV\u00e4rdnamn fr\u00e5n certifikatet: {1}Vill du forts\u00e4tta?" },
	{ "https.dialog.unknown.host", "Ok\u00e4nd v\u00e4rddator" },

	{ "security.dialog.caption", "Varning - S\u00e4kerhet" },
	{ "security.dialog.text0", "Vill du installera och k\u00f6ra signerad applet distribuerat av \"{0}\"?\n\nUtgivaren har godk\u00e4nts av: \"{2}\"" },
        { "security.dialog.text0a" ,"Vill du till\u00e5ta den signerade {0} som distribuerats av \"{1}\"?\n\nUtgivarens \u00e4kthet kan inte kontrolleras." },
  	{ "security.dialog.timestamp.text1", "The {0} was signed on {1}." },
	{ "security.dialog_https.text0", "Accepterar du certifikatet fr\u00e5n webbadressen \"{0}\" i syfte att utbyta krypterad information?\n\nUtgivaren har godk\u00e4nts av: \"{1}\"" },
        { "security.dialog_https.text0a" ,"Accepterar du certifikatet fr\u00e5n webbadressen \"{0}\" i syfte att utbyta krypterad information?\n\nUtgivaren har inte godk\u00e4nts." },
	{ "security.dialog.text1", "Varning: \"{0}\" f\u00f6rs\u00e4krar att inneh\u00e5llet \u00e4r s\u00e4kert. Du b\u00f6r endast installera/visa inneh\u00e5llet om du litar p\u00e5 att \"{0}\" g\u00f6r denna f\u00f6rs\u00e4kran.\n\n" },
	{ "security.dialog.unknown.issuer", "Ok\u00e4nd utf\u00e4rdare" },
	{ "security.dialog.unknown.subject", "Ok\u00e4nt \u00e4mne" },
	{ "security.dialog.certShowName", "{0} ({1})" },
	{ "security.dialog.rootCANotValid", "S\u00e4kerhetscertifikatet har utf\u00e4rdats av ett f\u00f6retag som inte \u00e4r betrott." },
	{ "security.dialog.rootCAValid", "S\u00e4kerhetscertifikatet har utf\u00e4rdats av ett f\u00f6retag som \u00e4r betrott." },
	{ "security.dialog.timeNotValid", "S\u00e4kerhetscertifikatet har f\u00f6rfallit eller har \u00e4nnu inte b\u00f6rjat g\u00e4lla." },
	{ "security.dialog.timeValid", "S\u00e4kerhetscertifikatet har inte f\u00f6rfallit och \u00e4r fortfarande giltigt." },
	{ "security.dialog.timeValidTS", "The security certificate was valid when the {0} was signed." },
	{ "security.dialog.buttonAlways", "Alltid" },
        { "security.dialog.buttonAlways.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "security.dialog.buttonYes", "Ja" },
	{ "security.dialog.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_J)},
        { "security.dialog.buttonNo", "Nej" },
	{ "security.dialog.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "security.dialog.buttonViewCert", "Fler detaljer" },
        { "security.dialog.buttonViewCert.acceleratorKey", new Integer(KeyEvent.VK_F)},

        { "security.badcert.caption", "Varning - S\u00e4kerhet" },
        { "security.badcert.https.text", "Det g\u00e5r inte att validera HTTPS-certifikatet.\n{0} kommer inte att k\u00f6ras." },
        { "security.badcert.config.text", "S\u00e4kerhetskonfigurationen till\u00e5ter inte att det h\u00e4r certifikatet valideras. {0} kommer inte att k\u00f6ras." },
        { "security.badcert.text", "Det gick inte att validera certifikatet. {0} kommer inte att k\u00f6ras." },
        { "security.badcert.viewException", "Visa undantag" },
        { "security.badcert.viewException.acceleratorKey", new Integer(KeyEvent.VK_S)},
        { "security.badcert.viewCert", "Fler detaljer" },
        { "security.badcert.viewCert.acceleratorKey", new Integer(KeyEvent.VK_M)},

	{ "cert.dialog.caption", "Detaljer - Certifikat" },
	{ "cert.dialog.certpath", "Certifikatv\u00e4g" },
	{ "cert.dialog.field.Version", "Version" },
	{ "cert.dialog.field.SerialNumber", "Serienummer" },
	{ "cert.dialog.field.SignatureAlg", "Signaturalgoritm" },
	{ "cert.dialog.field.Issuer", "Utf\u00e4rdare" },
	{ "cert.dialog.field.EffectiveDate", "G\u00e4llande datum" },
	{ "cert.dialog.field.ExpirationDate", "Utg\u00e5ngsdatum" },
	{ "cert.dialog.field.Validity", "Giltighet" },
	{ "cert.dialog.field.Subject", "\u00c4mne" },
	{ "cert.dialog.field.Signature", "Signatur" },
	{ "cert.dialog.field", "F\u00e4lt" },
	{ "cert.dialog.value", "V\u00e4rde" },
        { "cert.dialog.close", "St\u00e4ng" },
	{ "cert.dialog.close.acceleratorKey", new Integer(KeyEvent.VK_S) },

	{ "clientauth.password.dialog.buttonOK", "OK" },
	{ "clientauth.password.dialog.buttonOK.acceleratorKey", new Integer(KeyEvent.VK_O)},
	{ "clientauth.password.dialog.buttonCancel", "Avbryt" },
	{ "clientauth.password.dialog.buttonCancel.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "clientauth.password.dialog.caption", "L\u00f6senord - nyckellager" },
	{ "clientauth.password.dialog.text", "<html><B>L\u00f6senord kr\u00e4vs</B><P> Ange l\u00f6senord om du vill ha \u00e5tkomst till nyckellagret f\u00f6r klientverifiering:</html>" },
        { "clientauth.password.dialog.error.caption", "Fel - Nyckellagret f\u00f6r klientverifiering" },
        { "clientauth.password.dialog.error.text", "<html><b>\u00c5tkomstfel f\u00f6r nyckellagret f\u00f6r klientverifiering</b></html>Nyckellagret har \u00e4ndrats eller s\u00e5 var l\u00f6senordet felaktigt." },

	{ "clientauth.certlist.dialog.buttonOK", "OK" },
	{ "clientauth.certlist.dialog.buttonOK.acceleratorKey", new Integer(KeyEvent.VK_O)},
	{ "clientauth.certlist.dialog.buttonCancel", "Avbryt" },
	{ "clientauth.certlist.dialog.buttonCancel.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "clientauth.certlist.dialog.buttonDetails", "Information" },
	{ "clientauth.certlist.dialog.buttonDetails.acceleratorKey", new Integer(KeyEvent.VK_N)},
	{ "clientauth.certlist.dialog.caption", "Klientverifiering" },
	{ "clientauth.certlist.dialog.text", "<html><B>Klientcertifikat kr\u00e4vs</B><P> Markera det certifikat som ska anv\u00e4ndas vid anslutning:<html>" },

	{ "dialogfactory.confirmDialogTitle", "Bekr\u00e4ftelse kr\u00e4vs - Java" },
	{ "dialogfactory.inputDialogTitle", "Information kr\u00e4vs - Java" },
	{ "dialogfactory.messageDialogTitle", "Meddelande - Java" },
	{ "dialogfactory.exceptionDialogTitle", "Fel - Java" },
	{ "dialogfactory.optionDialogTitle", "Option - Java" },
	{ "dialogfactory.aboutDialogTitle", "Om - Java" },
	{ "dialogfactory.confirm.yes", "Ja" },
        { "dialogfactory.confirm.yes.acceleratorKey", new Integer(KeyEvent.VK_J)},
        { "dialogfactory.confirm.no", "Nej" },
        { "dialogfactory.confirm.no.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "dialogfactory.moreInfo", "Fler detaljer" },
        { "dialogfactory.moreInfo.acceleratorKey", new Integer(KeyEvent.VK_F)},
        { "dialogfactory.lessInfo", "F\u00e4rre detaljer" },
        { "dialogfactory.lessInfo.acceleratorKey", new Integer(KeyEvent.VK_R)},
	{ "dialogfactory.java.home.link", "http://www.java.com" },
	{ "dialogfactory.general_error", "<html><b>Allm\u00e4nt undantag</b></html>" },
	{ "dialogfactory.net_error", "<html><b>N\u00e4tverksundantag</b></html>" },
	{ "dialogfactory.security_error", "<html><b>S\u00e4kerhetsundantag</b></html>" },
	{ "dialogfactory.ext_error", "<html><b>Valfritt paket-undantag</b></html>" },
	{ "dialogfactory.user.selected", "Anv\u00e4ndaren valde: {0}" },
	{ "dialogfactory.user.typed", "Anv\u00e4ndaren skrev: {0}" },

	{ "deploycertstore.cert.loading", "Laddar JPI-certifikat fr\u00e5n {0}" },
	{ "deploycertstore.cert.loaded", "Laddade JPI-certifikat fr\u00e5n {0}" },
	{ "deploycertstore.cert.saving", "Sparar JPI-certifikat i {0}" },
	{ "deploycertstore.cert.saved", "Sparade JPI-certifikat i {0}" },
	{ "deploycertstore.cert.adding", "L\u00e4gger till certifikat i JPI-permanent certifikatlager" },
	{ "deploycertstore.cert.added", "Lade till certifikat i JPI-permanent certifikatlager som alias {0}" },
	{ "deploycertstore.cert.removing", "Tar bort certifikat i JPI-permanent certifikatlager" },
	{ "deploycertstore.cert.removed", "Tog bort certifikat i JPI-permanent certifikatlager som alias {0}" },
	{ "deploycertstore.cert.instore", "Kontrollerar om certifikatet finns i JPI-permanent certifikatlager" },
	{ "deploycertstore.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i JPI-permanent certifikatlager" },
	{ "deploycertstore.cert.iterator", "H\u00e4mta certifikatupprepare i JPI-permanent certifikatlager" },
	{ "deploycertstore.cert.getkeystore", "H\u00e4mta nyckellagerobjekt f\u00f6r JPI-certifikatlager" },

	{ "httpscertstore.cert.loading", "Laddar JPI Https-certifikat fr\u00e5n {0}" },
	{ "httpscertstore.cert.loaded", "Laddade JPI Https-certifikat fr\u00e5n {0}" },
	{ "httpscertstore.cert.saving", "Sparar JPI Https-certifikat i {0}" },
	{ "httpscertstore.cert.saved", "Sparade JPI Https-certifikat i {0}" },
	{ "httpscertstore.cert.adding", "L\u00e4gger till Https-certifikat i JPI-permanent certifikatlager" },
	{ "httpscertstore.cert.added", "Lade till Https-certifikat i JPI-permanent certifikatlager som alias {0}" },
	{ "httpscertstore.cert.removing", "Tar bort Https-certifikat ut JPI-permanent certifikatlager" },
	{ "httpscertstore.cert.removed", "Tog bort Https-certifikat JPI-permanent certifikatlager som alias {0}" },
	{ "httpscertstore.cert.instore", "Kontrollerar om Https-certifikat finns i JPI-permanent certifikatlager" },
	{ "httpscertstore.cert.canverify", "Kontrollera om Https-certifikat kan bekr\u00e4ftas med certifikat i JPI-permanent certifikatlager" },
	{ "httpscertstore.cert.iterator", "H\u00e4mta Https-certifikatupprepare i JPI-permanent certifikatlager" },
	{ "httpscertstore.cert.getkeystore", "H\u00e4mta nyckellagerobjekt f\u00f6r Https-certifikatlager" },

	{ "rootcertstore.cert.loading", "Laddar Root CA-certifikat fr\u00e5n {0}" },
	{ "rootcertstore.cert.loaded", "Laddade Root CA-certifikat fr\u00e5n {0}" },
	{ "rootcertstore.cert.noload", "Root CA-certifikatfil hittades inte: {0}" },
	{ "rootcertstore.cert.saving", "Sparar Root CA-certifikat i {0}" },
	{ "rootcertstore.cert.saved", "Sparade Root CA-certifikat i {0}" },
	{ "rootcertstore.cert.adding", "L\u00e4gger till certifikat i Root CA-permanent certifikatlager" },
	{ "rootcertstore.cert.added", "Lade till certifikat i Root CA-certifikatlager som alias {0}" },
	{ "rootcertstore.cert.removing", "Tar bort certifikat i Root CA-certifikatlager" },
	{ "rootcertstore.cert.removed", "Tog bort certifikat i Root CA-certifikatlager som alias {0}" },
	{ "rootcertstore.cert.instore", "Kontrollerar om certifikatet finns i Root CA-certifikatlager" },
	{ "rootcertstore.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i Root CA-certifikatlager" },
	{ "rootcertstore.cert.iterator", "H\u00e4mta certifikatupprepare i Root CA-certifikatlager" },
	{ "rootcertstore.cert.getkeystore", "H\u00e4mta nyckellagerobjekt f\u00f6r Root CA-certifikatlager" },
	{ "rootcertstore.cert.verify.ok", "Certifikatet har bekr\u00e4ftats med Root CA-certifikat" },
	{ "rootcertstore.cert.verify.fail", "Bekr\u00e4ftelsen av certifikatet med Root CA-certifikat misslyckades" },
	{ "rootcertstore.cert.tobeverified", "Certifikat som ska verifieras:\n{0}" },
	{ "rootcertstore.cert.tobecompared", "J\u00e4mf\u00f6r certifikat med Root CA-certifikat:\n{0}" },

	{ "roothttpscertstore.cert.loading", "Laddar Root CA Https-certifikatfil fr\u00e5n {0}" },
	{ "roothttpscertstore.cert.loaded", "Laddade Root CA Https-certifikatfil fr\u00e5n {0}" },
	{ "roothttpscertstore.cert.noload", "SSL Root CA-certifikatfil hittades inte: {0}" },
	{ "roothttpscertstore.cert.saving", "Sparar Root CA Https-certifikat i {0}" },
	{ "roothttpscertstore.cert.saved", "Sparade SSL Root CA-certifikat i {0}" },
	{ "roothttpscertstore.cert.adding", "L\u00e4gger till certifikat i Https Root CA-permanent certifikatlager" },
	{ "roothttpscertstore.cert.added", "Lade till certifikat i SSL Root CA-certifikatlager som alias {0}" },
	{ "roothttpscertstore.cert.removing", "Tar bort certifikat i Root CA Https-certifikatlager" },
	{ "roothttpscertstore.cert.removed", "Tog bort certifikat i SSL Root CA-certifikatlager som alias {0}" },
	{ "roothttpscertstore.cert.instore", "Kontrollerar om certifikatet finns i Root CA Https-certifikatlager" },
	{ "roothttpscertstore.cert.canverify", "Kontrollera om certifikat kan bekr\u00e4ftas med certifikat i Root CA Http-certifikatlager" },
	{ "roothttpscertstore.cert.iterator", "H\u00e4mta certifikatupprepare i Root CA Https-certifikatlager" },
	{ "roothttpscertstore.cert.getkeystore", "H\u00e4mta nyckellagerobjekt f\u00f6r Https Root CA-certifikatlager" },
	{ "roothttpscertstore.cert.verify.ok", "Certifikatet har bekr\u00e4ftats med SSL Root CA-certifikat" },
	{ "roothttpscertstore.cert.verify.fail", "Bekr\u00e4ftelsen av certifikatet med Root CA Https-certifikat misslyckades" },
	{ "roothttpscertstore.cert.tobeverified", "Certifikat som ska verifieras:\n{0}" },
	{ "roothttpscertstore.cert.tobecompared", "J\u00e4mf\u00f6r certifikat med Root CA Https-certifikat:\n{0}" },

	{ "sessioncertstore.cert.loading", "Laddar certifikat fr\u00e5n JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.loaded", "Laddade certifikat fr\u00e5n JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.saving", "Sparar certifikat i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.saved", "Sparade certifikat i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.adding", "L\u00e4gger till certifikat i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.added", "Lade till certifikat i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.removing", "Ta bort certifikat i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.removed", "Tog bort certifikat i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.instore", "Kontrollerar om certifikatet finns i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.iterator", "H\u00e4mta certifikatupprepare i JPI-sessionscertifikatlager" },
	{ "sessioncertstore.cert.getkeystore", "H\u00e4mta nyckellagerobjekt f\u00f6r JPI-sessionscertifikatlager" },

        { "iexplorer.cert.loading", "Laddar certifikat fr\u00e5n certifikatlager f\u00f6r Internet Explorer {0}" },
        { "iexplorer.cert.loaded", "Laddade certifikat fr\u00e5n certifikatlager f\u00f6r Internet Explorer {0}" },
        { "iexplorer.cert.instore", "Kontrollerar om certifikatet finns i certifikatlager f\u00f6r Internet Explorer {0}" },
        { "iexplorer.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i certifikatlager f\u00f6r Internet Explorer {0}" },
        { "iexplorer.cert.iterator", "H\u00e4mta certifikatupprepare i certifikatlager f\u00f6r Internet Explorer {0}" },
        { "iexplorer.cert.verify.ok", "Certifikatet har verifierats med Internet Explorer-certifikat {0}" },
        { "iexplorer.cert.verify.fail", "Verifieringen av certifikatet med Internet Explorer {0}-certifikat misslyckades" },
        { "iexplorer.cert.tobeverified", "Certifikat som ska verifieras:\n{0}" },
        { "iexplorer.cert.tobecompared", "J\u00e4mf\u00f6r certifikat med Internet Explorer {0}-certifikat:\n{1}" },
        { "mozilla.cert.loading", "Laddar certifikat fr\u00e5n certifikatlager f\u00f6r Mozilla {0}" },
        { "mozilla.cert.loaded", "Laddade certifikat fr\u00e5n certifikatlager f\u00f6r Mozilla {0}" },
        { "mozilla.cert.instore", "Kontrollerar om certifikatet finns i certifikatlager f\u00f6r Mozilla {0}" },
        { "mozilla.cert.canverify", "Kontrollera om certifikatet kan bekr\u00e4ftas med certifikat i certifikatlager f\u00f6r Mozilla {0}" },
        { "mozilla.cert.iterator", "H\u00e4mta certifikatupprepare i certifikatlager f\u00f6r Mozilla {0}" },
        { "mozilla.cert.verify.ok", "Certifikatet har bekr\u00e4ftats med certifikat f\u00f6r Mozilla {0}" },
        { "mozilla.cert.verify.fail", "Bekr\u00e4ftelsen av certifikatet med certifikat f\u00f6r Mozilla {0} misslyckades" },
        { "mozilla.cert.tobeverified", "Certifikat som ska verifieras:\n{0}" },
        { "mozilla.cert.tobecompared", "J\u00e4mf\u00f6r certifikat med certifikat f\u00f6r Mozilla {0}:\n{1}" },

        { "browserkeystore.jss.no", "JSS-paket finns inte" },
        { "browserkeystore.jss.yes", "JSS-paket har \u00f6ppnats" },
        { "browserkeystore.jss.notconfig", "JSS har inte konfigurerats" },
        { "browserkeystore.jss.config", "JSS har konfigurerats" },
        { "browserkeystore.mozilla.dir", "\u00c5tkomst till nycklar och certifikat i anv\u00e4ndarprofilen f\u00f6r Mozilla: {0}" },
        { "browserkeystore.password.dialog.buttonOK", "OK" },
        { "browserkeystore.password.dialog.buttonOK.acceleratorKey", new Integer(KeyEvent.VK_O)},
        { "browserkeystore.password.dialog.buttonCancel", "Avbryt" },
        { "browserkeystore.password.dialog.buttonCancel.acceleratorKey", new Integer(KeyEvent.VK_A)},
        { "browserkeystore.password.dialog.caption", "L\u00f6senord kr\u00e4vs" },
        { "browserkeystore.password.dialog.text", "Ange l\u00f6senordet f\u00f6r {0}:\n" },
        { "mozillamykeystore.priv.notfound", "det gick inte att hitta privat nyckel f\u00f6r cert: {0}" },

	{ "hostnameverifier.automation.ignoremismatch", "Automatisering: Ignorera v\u00e4rddatornamn som inte st\u00e4mmer \u00f6verens" },

	{ "trustdecider.check.basicconstraints", "Det gick inte att kontrollera grundl\u00e4ggande begr\u00e4nsningar i certifikatet" },
	{ "trustdecider.check.leafkeyusage", "Det gick inte att kontrollera l\u00f6vnyckeln i certifikatet" },
	{ "trustdecider.check.signerkeyusage", "Det gick inte att kontrollera signaturnyckeln i certifikatet" },
	{ "trustdecider.check.extensions", "Det gick inte att kontrollera kritiska till\u00e4gg i certifikatet" },
	{ "trustdecider.check.signature", "Det gick inte att kontrollera signaturen i certifikatet" },
	{ "trustdecider.check.basicconstraints.certtypebit", "Det gick inte att kontrollera bit av netscape-typ i certifikatet" },
	{ "trustdecider.check.basicconstraints.extensionvalue", "Det gick inte att kontrollera netscape-till\u00e4ggsv\u00e4rdet i certifikatet" },
	{ "trustdecider.check.basicconstraints.bitvalue", "Det gick inte att kontrollera netscape-bitv\u00e4rdena 5,6,7 i certifikatet" },
	{ "trustdecider.check.basicconstraints.enduser", "Det gick inte att kontrollera slutanv\u00e4ndarens akt som CA i certifikatet" },
	{ "trustdecider.check.basicconstraints.pathlength", "Det gick inte att kontrollera begr\u00e4nsning f\u00f6r s\u00f6kv\u00e4gsl\u00e4ngd i certifikatet" },
	{ "trustdecider.check.leafkeyusage.length", "Det gick inte att kontrollera l\u00e4ngden p\u00e5 nyckelanv\u00e4ndning i certifikatet" },
	{ "trustdecider.check.leafkeyusage.digitalsignature", "Det gick inte att kontrollera digital signatur i certifikatet" },
	{ "trustdecider.check.leafkeyusage.extkeyusageinfo", "Det gick inte att kontrollera anv\u00e4ndningsinfo f\u00f6r till\u00e4ggsnyckel i certifikatet" },
        { "trustdecider.check.leafkeyusage.tsaextkeyusageinfo", "Det gick inte att kontrollera anv\u00e4ndningsinfo f\u00f6r TSA-till\u00e4ggsnyckel i certifikatet" },
	{ "trustdecider.check.leafkeyusage.certtypebit", "Det gick inte att kontrollera bit av netscape-typ i certifikatet" },
	{ "trustdecider.check.signerkeyusage.lengthandbit", "Det gick inte att kontrollera l\u00e4ngd och bit i certifikatet" },
	{ "trustdecider.check.signerkeyusage.keyusage", "Det gick inte att kontrollera nyckelanv\u00e4ndning i certifikatet" },
	{ "trustdecider.check.canonicalize.updatecert", "Uppdatera rotcertifikat med certifikat i cacerts-filen" },
	{ "trustdecider.check.canonicalize.missing", "L\u00e4gg till saknade rotcertifikat" },
	{ "trustdecider.check.gettrustedcert.find", "S\u00f6k efter den giltiga rotcertifikatutf\u00e4rdaren i cacerts-filen." },
	{ "trustdecider.check.gettrustedissuercert.find", "S\u00f6k efter den giltiga rotcertifikatutf\u00e4rdaren som saknas i cacerts-filen." },
        { "trustdecider.check.timestamping.no", "Det finns ingen tidsst\u00e4mpelinformation att tillg\u00e5" },
        { "trustdecider.check.timestamping.yes", "Tidsst\u00e4mpelinformation finns att tillg\u00e5" },

        { "trustdecider.check.timestamping.tsapath", "B\u00f6rja kontroll av s\u00f6kv\u00e4g till TSA-certifikat" },
        { "trustdecider.check.timestamping.inca", "\u00c4ven om certifikatet har f\u00f6rfallit \u00e4r det tidsst\u00e4mplat i en giltig period och har ett giltigt TSA" },
        { "trustdecider.check.timestamping.notinca", "Certifikatet har f\u00f6rfallit och har ogiltigt TSA" },
        { "trustdecider.check.timestamping.valid", "Certifikatet har f\u00f6rfallit och \u00e4r tidsst\u00e4mplat i en giltig period" },
        { "trustdecider.check.timestamping.invalid", "Certifikatet har f\u00f6rfallit och \u00e4r tidsst\u00e4mplat i en ogiltig period" },
        { "trustdecider.check.timestamping.need", "Certifikatet har f\u00f6rfallit. Kontrollera tidsst\u00e4mpelinformation" },
        { "trustdecider.check.timestamping.noneed", "Certifikatet har inte f\u00f6rfallit. Tidsst\u00e4mpelinformation beh\u00f6ver inte kontrolleras" },
        { "trustdecider.check.timestamping.notfound", "Det nya tidsst\u00e4mpel-API:t hittades inte" },
	{ "trustdecider.user.grant.session", "Anv\u00e4ndaren har gett beh\u00f6righet till koden endast i denna session" },
	{ "trustdecider.user.grant.forever", "Anv\u00e4ndaren har gett beh\u00f6righet till koden f\u00f6r alltid" },
	{ "trustdecider.user.deny", "Anv\u00e4ndaren har nekat beh\u00f6righet till koden" },
	{ "trustdecider.automation.trustcert", "Automatisering: Lita p\u00e5 RSA-certifikat vid signatur" },
	{ "trustdecider.code.type.applet", "till\u00e4ggsprogram" },
	{ "trustdecider.code.type.application", "Program" },
	{ "trustdecider.code.type.extension", "till\u00e4gg" },
	{ "trustdecider.code.type.installer", "installerare" },
	{ "trustdecider.user.cannot.grant.any", "S\u00e4kerhetskonfigurationen ger inte beh\u00f6righet f\u00f6r nya certifikat" },
	{ "trustdecider.user.cannot.grant.notinca", "S\u00e4kerhetskonfigurationen ger inte beh\u00f6righet f\u00f6r sj\u00e4lvsignerade certifikat" },
	{ "x509trustmgr.automation.ignoreclientcert", "Automatisering: Ignorera icke tillf\u00f6rlitliga klientcertifikat" },
	{ "x509trustmgr.automation.ignoreservercert", "Automatisering: Ignorera icke tillf\u00f6rlitliga servercertifikat" },

	{ "net.proxy.text", "Proxy: " },
	{ "net.proxy.override.text", "Proxy-ers\u00e4ttningar: " },
	{ "net.proxy.configuration.text", "Proxy-konfiguration: " },
	{ "net.proxy.type.browser", "Proxykonfiguration f\u00f6r webbl\u00e4sare" },
	{ "net.proxy.type.auto", "Automatisk proxy-konfiguration" },
	{ "net.proxy.type.manual", "Manuell konfiguration" },
	{ "net.proxy.type.none", "Ingen proxy" },
	{ "net.proxy.type.user", "Anv\u00e4ndaren har \u00e5sidosatt webbl\u00e4sarens proxyinst\u00e4llningar." },
	{ "net.proxy.loading.ie", "Laddar proxykonfiguration fr\u00e5n Internet Explorer ..."},
	{ "net.proxy.loading.ns", "Laddar proxykonfiguration fr\u00e5n Netscape Navigator ..."},
	{ "net.proxy.loading.userdef", "Laddar anv\u00e4ndardefinierad proxykonfiguration ..."},
	{ "net.proxy.loading.direct", "Laddar direkt proxykonfiguration ..."},
	{ "net.proxy.loading.manual", "Laddar manuell proxykonfiguration ..."},
	{ "net.proxy.loading.auto", "Laddar automatisk proxykonfiguration ..."},
	{ "net.proxy.loading.browser", "Laddar webbl\u00e4sarbaserad proxykonfiguration ..."},
	{ "net.proxy.loading.manual.error", "Det g\u00e5r inte att anv\u00e4nda manuell proxykonfiguration - \u00e5terv\u00e4nder till DIRECT"},
	{ "net.proxy.loading.auto.error", "Det g\u00e5r inte att anv\u00e4nda automatisk proxykonfiguration - \u00e5terv\u00e4nder till MANUAL"},
	{ "net.proxy.loading.done", "Klar."},
	{ "net.proxy.browser.pref.read", "L\u00e4ser fil med anv\u00e4ndarinst\u00e4llningar fr\u00e5n {0}"},
	{ "net.proxy.browser.proxyEnable", "    Aktivera proxy: {0}"},
	{ "net.proxy.browser.proxyList", "    Proxylista: {0}"},
	{ "net.proxy.browser.proxyOverride", "    Proxy-ers\u00e4ttningar: {0}"},
	{ "net.proxy.browser.autoConfigURL", "    URL f\u00f6r automatisk konfiguration: {0}"},
	{ "net.proxy.browser.smartConfig", "Pinga proxy-servern {0} p\u00e5 port {1}"},
        { "net.proxy.browser.connectionException", "Proxy-server {0} p\u00e5 port {1} kan inte n\u00e5s"},
	{ "net.proxy.ns6.regs.exception", "Fel vid l\u00e4sning av registerfil: {0}"},
	{ "net.proxy.pattern.convert", "Konvertera lista \u00f6ver proxy-ers\u00e4ttningar till regeluttryck: "},
	{ "net.proxy.pattern.convert.error", "Det g\u00e5r inte att konvertera lista \u00f6ver proxy-ers\u00e4ttningar till regeluttryck - ignorera"},
	{ "net.proxy.auto.download.ins", "H\u00e4mtar INS-fil fr\u00e5n {0}" },
	{ "net.proxy.auto.download.js", "H\u00e4mtar automatisk proxyfil fr\u00e5n {0}" },
	{ "net.proxy.auto.result.error", "Det g\u00e5r inte att fastst\u00e4lla proxy-inst\u00e4llning fr\u00e5n utv\u00e4rdering - \u00e5terv\u00e4nder till DIRECT"},
        { "net.proxy.service.not_available", "Proxy-service \u00e4r inte tillg\u00e4nglig f\u00f6r {0} - \u00e5terv\u00e4nder till DIRECT" },
	{ "net.proxy.error.caption", "Fel - Proxy-konfiguration" },
	{ "net.proxy.nsprefs.error", "<html><b>Kan inte \u00e5terfinna proxy-inst\u00e4llningar</b></html>G\u00e5r tillbaka till annan proxy-konfiguration.\n" },
	{ "net.proxy.connect", "Ansluter {0} med proxy {1}" },

	{ "net.authenticate.caption", "L\u00f6senord kr\u00e4vs - Networking"},
	{ "net.authenticate.label", "<html><b>Skriv in ditt anv\u00e4ndarnamn och l\u00f6senord:</b></html>"},
	{ "net.authenticate.resource", "Resurs:" },
	{ "net.authenticate.username", "Anv\u00e4ndarnamn:" },
        { "net.authenticate.username.mnemonic", "VK_U" },
	{ "net.authenticate.password", "L\u00f6senord:" },
        { "net.authenticate.password.mnemonic", "VK_P" },
	{ "net.authenticate.firewall", "Brandv\u00e4gg:" },
	{ "net.authenticate.domain", "Dom\u00e4n:"},
        { "net.authenticate.domain.mnemonic", "VK_D" },
	{ "net.authenticate.realm", "Omr\u00e5de:" },
	{ "net.authenticate.scheme", "Schema:" },
	{ "net.authenticate.unknownSite", "Ok\u00e4nd plats" },

	{ "net.cookie.cache", "Cookie-cache: " },
	{ "net.cookie.server", "Server {0} beg\u00e4r set-cookie med \"{1}\"" },
	{ "net.cookie.connect", "Ansluter {0} med cookie \"{1}\"" },
	{ "net.cookie.ignore.setcookie", "Cookie-service \u00e4r ej tillg\u00e4nglig - bortse fr\u00e5n \"Set-Cookie\"" },
	{ "net.cookie.noservice", "Cookie-service \u00e4r ej tillg\u00e4nglig - anv\u00e4nd cache f\u00f6r att best\u00e4mma \"Cookie\"" },

	{"about.java.version", "Version {0} (build {1})"},
	{"about.prompt.info", "Mer information finns p\u00e5"},
	{"about.home.link", "http://www.java.com"},
	{"about.option.close", "St\u00e4ng"},
	{"about.option.close.acceleratorKey", new Integer(KeyEvent.VK_S)},
        {"about.copyright", "Copyright 2004 Sun Microsystems, Inc."},
	{"about.legal.note", "Med ensamr\u00e4tt. Anv\u00e4ndning m\u00e5ste ske i enlighet med licensvillkoren." },


	{ "cert.remove_button", "Ta bort" },
        { "cert.remove_button.mnemonic", "VK_B" },
        { "cert.import_button", "Importera" },
        { "cert.import_button.mnemonic", "VK_I" },
        { "cert.export_button", "Exportera" },
        { "cert.export_button.mnemonic", "VK_E" },
        { "cert.details_button", "Information" },
        { "cert.details_button.mnemonic", "VK_N" },
        { "cert.viewcert_button", "Visa certifikat" },
        { "cert.viewcert_button.mnemonic", "VK_V" },
        { "cert.close_button", "St\u00e4ng" },
        { "cert.close_button.mnemonic", "VK_S" },
        { "cert.type.trusted_certs", "Betrodda certifikat" },
        { "cert.type.secure_site", "S\u00e4ker plats" },
        { "cert.type.client_auth", "Klientverifiering" },
        { "cert.type.signer_ca", "Signerarcertifikatutf\u00e4rdare" },
        { "cert.type.secure_site_ca", "Certifikatutf\u00e4rdare f\u00f6r s\u00e4ker plats" },
        { "cert.rbutton.user", "Anv\u00e4ndare" },
        { "cert.rbutton.system", "System" },
        { "cert.settings", "Certifikat" },
        { "cert.dialog.import.error.caption", "Fel - Importera certifikat" },
        { "cert.dialog.export.error.caption", "Fel - Exportera certifikat" },
        { "cert.dialog.import.format.text", "<html><b>Ok\u00e4nt filformat</b></html>Inga certifikat kommer att importeras." },
        { "cert.dialog.export.password.text", "<html><b>Ogiltigt l\u00f6senord</b></html>Det l\u00f6senord som angivits \u00e4r felaktigt." },
        { "cert.dialog.import.file.text", "<html><b>Filen finns inte</b></html>Inga certifikat kommer att importeras." },
        { "cert.dialog.import.password.text", "<html><b>Ogiltigt l\u00f6senord</b></html>Det l\u00f6senord som angivits \u00e4r felaktigt." },
        { "cert.dialog.password.caption", "L\u00f6senord" },
        { "cert.dialog.password.import.caption", "L\u00f6senord - Importera" },
        { "cert.dialog.password.export.caption", "L\u00f6senord - Exportera" },
        { "cert.dialog.password.text", "<html><b>Ange ett l\u00f6senord om du vill komma \u00e5t den h\u00e4r filen:<b></html>" },
        { "cert.dialog.exportpassword.text", "<html><b>Ange ett l\u00f6senord om du vill komma \u00e5t den h\u00e4r privata nyckeln i filen f\u00f6r nyckellager f\u00f6r klientverifiering:<b></html>" },
        { "cert.dialog.savepassword.text", "<html><b>Ange ett l\u00f6senord om du vill spara den h\u00e4r nyckelfilen:<b></html>" },
        { "cert.dialog.password.okButton", "OK" },
        { "cert.dialog.password.cancelButton", "Avbryt" },
        { "cert.dialog.export.error.caption", "Fel - Exportera certifikat" },
        { "cert.dialog.export.text", "<html><b>Kunde inte exportera</b></html>Inga certifikat exporteras." },
        { "cert.dialog.remove.text", "Vill du ta bort certifikaten?" },
	{ "cert.dialog.remove.caption", "Ta bort certifikat" },
	{ "cert.dialog.issued.to", "Utf\u00e4rdat till" },
	{ "cert.dialog.issued.by", "Utf\u00e4rdat av" },
	{ "cert.dialog.user.level", "Anv\u00e4ndare" },
	{ "cert.dialog.system.level", "System" },
	{ "cert.dialog.certtype", "Certifikattyp: "},

	{ "controlpanel.jre.platformTableColumnTitle","Plattform"},
	{ "controlpanel.jre.productTableColumnTitle","Produkt" },
	{ "controlpanel.jre.locationTableColumnTitle","Plats" },
	{ "controlpanel.jre.pathTableColumnTitle","S\u00f6kv\u00e4g" },
	{ "controlpanel.jre.enabledTableColumnTitle", "Aktiverad" },

	{ "jnlp.jre.title", "Inst\u00e4llningar f\u00f6r JNLP Java Runtime" },
	{ "jnlp.jre.versions", "Java Runtime-versioner" },
	{ "jnlp.jre.choose.button", "V\u00e4lj" },
	{ "jnlp.jre.find.button", "S\u00f6k" },
	{ "jnlp.jre.add.button", "L\u00e4gg till" },
	{ "jnlp.jre.remove.button", "Ta bort" },
	{ "jnlp.jre.ok.button", "OK" },
	{ "jnlp.jre.cancel.button", "Avbryt" },
	{ "jnlp.jre.choose.button.mnemonic", "VK_V" },
	{ "jnlp.jre.find.button.mnemonic", "VK_S" },
	{ "jnlp.jre.add.button.mnemonic", "VK_L" },
	{ "jnlp.jre.remove.button.mnemonic", "VK_B" },
	{ "jnlp.jre.ok.button.mnemonic", "VK_O" },
	{ "jnlp.jre.cancel.button.mnemonic", "VK_A" },

	{ "find.dialog.title", "JRE Finder"},
	{ "find.title", "Java Runtime Environments"},
	{ "find.cancelButton", "Avbryt"},
	{ "find.prevButton", "F\u00f6reg\u00e5ende"},
	{ "find.nextButton", "N\u00e4sta "},
	{ "find.cancelButtonMnemonic", "VK_A"},
	{ "find.prevButtonMnemonic", "VK_F"},
	{ "find.nextButtonMnemonic", "VK_N"},
	{ "find.intro", "Java Web Start m\u00e5ste veta var de olika Java Runtime Environments \u00e4r installerade f\u00f6r att kunna ladda programmen.\n\nDu kan antingen markera en k\u00e4nd JRE eller markera en katalog i filsystemet som JRE:erna ska s\u00f6kas i." },

	{ "find.searching.title", "S\u00f6ker efter tillg\u00e4ngliga JRE:er. Det kan ta flera minuter." },
	{ "find.searching.prefix", "kontrollerar: " },
	{ "find.foundJREs.title", "F\u00f6ljande JRE:er hittades. Klicka p\u00e5 N\u00e4sta om du vill l\u00e4gga till dem." },
	{ "find.noJREs.title", "Det g\u00e5r inte att hitta en JRE. Klicka p\u00e5 F\u00f6reg\u00e5ende om du vill s\u00f6ka fr\u00e5n en annan plats" },

	// Each line in the property_file_header must start with "#"
        { "config.property_file_header", "# Java(tm) Deployment Properties\n# REDIGERA INTE DEN H\u00c4R FILEN.  Den genereras automatiskt.\n# Redigera egenskaperna med Java-kontrollpanelen." },
        { "config.unknownSubject", "Ok\u00e4nt f\u00f6rem\u00e5l" },
        { "config.unknownIssuer", "Ok\u00e4nd utf\u00e4rdare" },
        { "config.certShowName", "{0} ({1})" },
        { "config.certShowOOU", "{0} {1}" },
        { "config.proxy.autourl.invalid.text", "<html><b>Felaktig URL</b></html>Den automatiska URL:en f\u00f6r proxykonfiguration \u00e4r ogiltig." },
        { "config.proxy.autourl.invalid.caption", "Fel - Proxyer" },
	// Java Web Start Properties
	{ "APIImpl.clipboard.message.read", "Programmet beg\u00e4r skrivskydds\u00e5tkomst till systemets urklipp. Programmet kan f\u00e5 \u00e5tkomst till konfidentiell information som lagras i urklippet. Vill du till\u00e5ta den h\u00e4r \u00e5tg\u00e4rden?" },
        { "APIImpl.clipboard.message.write", "Programmet beg\u00e4r skriv\u00e5tkomst till systemets urklipp. Programmet kan komma att skriva \u00f6ver information som lagras i urklippet. Vill du till\u00e5ta den h\u00e4r \u00e5tg\u00e4rden?" },
        { "APIImpl.file.open.message", "Programmet beg\u00e4r l\u00e4s\u00e5tkomst till filsystemet. Programmet kan f\u00e5 \u00e5tkomst till konfidentiell information som lagras i filsystemet. Vill du till\u00e5ta den h\u00e4r \u00e5tg\u00e4rden?" },
        { "APIImpl.file.save.fileExist", "{0} finns redan.\n Vill du ers\u00e4tta den?" },
        { "APIImpl.file.save.fileExistTitle", "Filen finns redan" },
        { "APIImpl.file.save.message", "Programmet beg\u00e4r l\u00e4s/skriv\u00e5tkomst till en fil p\u00e5 det lokala filsystemet. Den h\u00e4r \u00e5tg\u00e4rden ger bara programmet tillg\u00e5ng till filerna som markerats i f\u00f6ljande dialogruta. Vill du till\u00e5ta den h\u00e4r \u00e5tg\u00e4rden?" },
        { "APIImpl.persistence.accessdenied", "\u00c5tkomst f\u00f6r permanent lagring nekades f\u00f6r webbadressen {0}" },
        { "APIImpl.persistence.filesizemessage", "Den maximala fill\u00e4ngden har \u00f6verskridits" },
        { "APIImpl.persistence.message", "Programmet beg\u00e4r ytterligare lagringsutrymme p\u00e5 den lokala disken. F\u00f6r n\u00e4rvarande \u00e4r den st\u00f6rsta till\u00e5tna lagringen {1} byte. Programmet beg\u00e4r att detta \u00f6kas till {0} byte. Vill du till\u00e5ta den h\u00e4r \u00e5tg\u00e4rden?" },
        { "APIImpl.print.message", "Programmet beg\u00e4r \u00e5tkomst till standardskrivaren. Om du till\u00e5ter den h\u00e4r \u00e5tg\u00e4rden f\u00e5r programmet skriv\u00e5tkomst till skrivaren. Vill du till\u00e5ta den h\u00e4r \u00e5tg\u00e4rden?" },
	{ "APIImpl.extended.fileOpen.message1", "Programmet beg\u00e4r l\u00e4s/skriv\u00e5tkomst till f\u00f6ljande filer p\u00e5 det lokala filsystemet."},
	{ "APIImpl.extended.fileOpen.message2", "Den h\u00e4r \u00e5tg\u00e4rden ger bara programmet tillg\u00e5ng till filerna i ovanst\u00e5ende lista. Vill du till\u00e5ta den h\u00e4r \u00e5tg\u00e4rden?"},
        { "APIImpl.securityDialog.no", "Nej" },
        { "APIImpl.securityDialog.remember", "Visa inte r\u00e5den igen" },
        { "APIImpl.securityDialog.title", "S\u00e4kerhetsr\u00e5d" },
        { "APIImpl.securityDialog.yes", "Ja" },
        { "Launch.error.installfailed", "Installationen misslyckades." },
        { "aboutBox.closeButton", "St\u00e4ng" },
        { "aboutBox.versionLabel", "Version {0} (build {1})" },
        { "applet.failedToStart", "Det gick inte att starta miniprogrammet: {0}" },
        { "applet.initializing", "Initierar miniprogram" },
        { "applet.initializingFailed", "Det gick inte att initiera miniprogrammet: {0}" },
        { "applet.running", "K\u00f6r..." },
        { "java48.image", "image/java48.png" },
        { "java32.image", "image/java32.png" },
        { "extensionInstall.rebootMessage", "Windows m\u00e5ste startas om innan \u00e4ndringarna b\u00f6rjar g\u00e4lla.\n\nVill du starta om Windows nu?" },
        { "extensionInstall.rebootTitle", "Starta om Windows" },
        { "install.configButton", "Konfigurera..." },
        { "install.configMnemonic", "VK_K" },
        { "install.errorInstalling", "Ett ov\u00e4ntat fel uppstod vid ett f\u00f6rs\u00f6k att installera Java Runtime Environment. F\u00f6rs\u00f6k igen." },
        { "install.errorRestarting", "Ett ov\u00e4ntat fel intr\u00e4ffade n\u00e4r programmet startades. F\u00f6rs\u00f6k igen." },
        { "install.title" ,"{0} - Skapa genv\u00e4g(ar)" },
        { "install.windows.both.message" ,"Vill du skapa genv\u00e4gar p\u00e5 skrivbordet och startmenyn f\u00f6r\n{0}?" },
        { "install.gnome.both.message" ,"Vill du skapa genv\u00e4gar p\u00e5 skrivbordet och programmenyn f\u00f6r\n{0}?" },
        { "install.desktop.message" ,"Vill du skapa genv\u00e4gar p\u00e5 skrivbordet f\u00f6r\n{0}?" },
        { "install.windows.menu.message" ,"Vill du skapa genv\u00e4gar p\u00e5 startmenyn f\u00f6r\n{0}?" },
        { "install.gnome.menu.message" ,"Vill du skapa genv\u00e4gar p\u00e5 programmenyn f\u00f6r\n{0}?" },
        { "install.noButton", "Nej" },
        { "install.noMnemonic", "VK_N" },
        { "install.yesButton", "Ja" },
        { "install.yesMnemonic", "VK_J" },
        { "launch.cancel", "Avbryt" },
        { "launch.downloadingJRE", "Beg\u00e4r JRE {0} fr\u00e5n {1}" },
        { "launch.error.badfield", "F\u00e4ltet {0} har ett ogiltigt v\u00e4rde: {1}" },
        { "launch.error.badfield-signedjnlp", "F\u00e4ltet {0} har ett ogiltigt v\u00e4rde i den signerade startfilen: {1}" },
        { "launch.error.badfield.download.https", "Kunde inte ladda ner via HTTPS" },
        { "launch.error.badfield.https", "Java 1.4+ kr\u00e4vs f\u00f6r HTTPS-st\u00f6d" },
        { "launch.error.badjarfile", "Skadad JAR-fil vid {0}" },
        { "launch.error.badjnlversion", "JNLP-versionen i startfilen st\u00f6ds inte: {0}. I den h\u00e4r versionen st\u00f6ds endast versionerna 1.0 och 1.5. Rapportera det h\u00e4r problemet till leverant\u00f6ren." },
        { "launch.error.badmimetyperesponse", "Felaktig MIME-typ returnerades fr\u00e5n servern vid \u00e5tkomst till resursen: {0} - {1}" },
        { "launch.error.badsignedjnlp", "Det gick inte att validera signering av startfilen. Den signerade versionen \u00e4r inte samma version som den som h\u00e4mtats." },
        { "launch.error.badversionresponse", "Felaktig version returnerades som svar fr\u00e5n servern vid \u00e5tkomst till resursen: {0} - {1}" },
        { "launch.error.canceledloadingresource", "Laddning av resurs {0} avbr\u00f6ts av anv\u00e4ndaren" },
        { "launch.error.category.arguments", "Fel - ogiltigt argument" },
        { "launch.error.category.download", "H\u00e4mtningsfel" },
        { "launch.error.category.launchdesc", "Fel p\u00e5 startfilen" },
        { "launch.error.category.memory", "Fel, slut p\u00e5 minne" },
        { "launch.error.category.security", "S\u00e4kerhetsfel" },
        { "launch.error.category.config", "Systemkonfiguration" },
        { "launch.error.category.unexpected", "Ov\u00e4ntat fel" },
        { "launch.error.couldnotloadarg", "Kunde inte ladda angiven fil/URL: {0}" },
        { "launch.error.errorcoderesponse-known", "Felkod {1} ({2}) returnerades fr\u00e5n servern vid \u00e5tkomst till resursen: {0}" },
        { "launch.error.errorcoderesponse-unknown", "Felkod 99 (ok\u00e4nt fel) returnerades fr\u00e5n servern vid \u00e5tkomst till resursen: {0}" },
        { "launch.error.failedexec", "Det gick inte att starta Java Runtime Environment version {0}" },
        { "launch.error.failedloadingresource", "Det gick inte att ladda resursen: {0}" },
        { "launch.error.invalidjardiff", "Det gick inte att anv\u00e4nda stegvis uppdatering f\u00f6r resursen: {0}" },
        { "launch.error.jarsigning-badsigning", "Det gick inte att kontrollera signaturen i resursen: {0}" },
        { "launch.error.jarsigning-missingentry", "Resursen saknar en signerad post: {0}" },
        { "launch.error.jarsigning-missingentryname", "Signerad post saknas: {0}" },
        { "launch.error.jarsigning-multicerts", "Mer \u00e4n ett certifikat anv\u00e4ndes f\u00f6r att signera resursen: {0}" },
        { "launch.error.jarsigning-multisigners", "Mer \u00e4n en signatur i en post i resursen: {0}" },
        { "launch.error.jarsigning-unsignedfile", "En osignerad post har hittats i resursen: {0}" },
        { "launch.error.missingfield", "F\u00f6ljande obligatoriska f\u00e4lt saknas i startfilen: {0}" },
        { "launch.error.missingfield-signedjnlp", "F\u00f6ljande obligatoriska f\u00e4lt saknas i den signerade startfilen: {0}" },
        { "launch.error.missingjreversion", "Ingen JRE-version har hittats i systemets startfil" },
        { "launch.error.missingversionresponse", "Felaktigt versionsf\u00e4lt returnerades som svar fr\u00e5n servern vid \u00e5tkomst till resursen: {0}" },
        { "launch.error.multiplehostsreferences", "Referenser till flera v\u00e4rdar i resurserna" },
        { "launch.error.nativelibviolation", "Anv\u00e4ndning av bibliotek i ursprungsformat kr\u00e4ver obegr\u00e4nsad \u00e5tkomst till systemet" },
        { "launch.error.noJre", "Programmet har beg\u00e4rt en version av plattformen JRE som inte har installerats p\u00e5 den lokala disken. Java Web Start kunde inte h\u00e4mta och installera den beg\u00e4rda versionen automatiskt. JRE-versionen m\u00e5ste installeras manuellt.\n\n" },
        { "launch.error.wont.download.jre", "Programmet har beg\u00e4rt en version av plattformen JRE (versionen {0}) som inte har installerats p\u00e5 den lokala disken. Java Web Start fick inte h\u00e4mta och installera den beg\u00e4rda versionen automatiskt. JRE-versionen m\u00e5ste installeras manuellt." },
        { "launch.error.cant.download.jre", "Programmet har beg\u00e4rt en version av plattformen JRE (versionen {0}) som inte har installerats p\u00e5 den lokala disken. Java Web Start kan inte h\u00e4mta och installera den beg\u00e4rda versionen automatiskt. JRE-versionen m\u00e5ste installeras manuellt." },
        { "launch.error.cant.access.system.cache", "Den aktuella anv\u00e4ndaren har inte skriv\u00e5tkomst till systemets cacheminne." },
        { "launch.error.cant.access.user.cache", "Den aktuella anv\u00e4ndaren har inte skriv\u00e5tkomst till cacheminnet." },
        { "launch.error.noappresources", "Inga programresurser anges f\u00f6r denna plattform. Kontakta leverant\u00f6ren av programmet och ta reda p\u00e5 om den h\u00e4r plattformen st\u00f6ds." },
        { "launch.error.nomainclass", "Det g\u00e5r inte att hitta huvudklassen {0} i {1}" },
        { "launch.error.nomainclassspec", "Ingen huvudklass har angetts f\u00f6r programmet" },
        { "launch.error.nomainjar", "Ingen huvud-JAR-fil har angetts." },
        { "launch.error.nonstaticmainmethod", "Huvudversionen () m\u00e5ste vara statisk" },
        { "launch.error.offlinemissingresource", "Det g\u00e5r inte att k\u00f6ra programmet offline eftersom inte alla resurser som kr\u00e4vs har h\u00e4mtats till den lokala disken." },
        { "launch.error.parse", "Det gick inte att analysera startfilen. Fel vid rad {0, nummer}." },
        { "launch.error.parse-signedjnlp", "Det gick inte att analysera den signerade startfilen. Fel vid rad {0, nummer}." },
        { "launch.error.resourceID", "{0}" },
        { "launch.error.resourceID-version", "({0}, {1})" },
        { "launch.error.singlecertviolation", "JAR-resurserna i filen JNLP har inte signerats av samma certifikat" },
        { "launch.error.toomanyargs", "F\u00f6r m\u00e5nga argument: {0}" },
        { "launch.error.unsignedAccessViolation", "Ett osignerat program beg\u00e4r obegr\u00e4nsad \u00e5tkomst till systemet" },
        { "launch.error.unsignedResource", "Osignerad resurs: {0}" },
        { "launch.estimatedTimeLeft", "Ungef\u00e4rlig \u00e5terst\u00e5ende tid: {0,nummer,00}:{1,nummer,00}:{2,nummer,00}" },
        { "launch.extensiondownload", "H\u00e4mtar filtill\u00e4ggsbeskrivning ({0} \u00e5terst\u00e5r)" },
        { "launch.extensiondownload-name", "H\u00e4mtar {0} filbeskrivning ({1} \u00e5terst\u00e5r)" },
        { "launch.initializing", "Initierar..." },
        { "launch.launchApplication", "Startar programmet..." },
        { "launch.launchInstaller", "Startar installationsprogrammet..." },
        { "launch.launchingExtensionInstaller", "Installationsprogrammet k\u00f6rs. V\u00e4nta..." },
        { "launch.loadingNetProgress", "{0} har l\u00e4sts" },
        { "launch.loadingNetProgressPercent", "{0} av {1} ({2}%) har l\u00e4sts" },
        { "launch.loadingNetStatus", "Laddar {0} fr\u00e5n {1}" },
        { "launch.loadingResourceFailed", "Det gick inte att ladda resursen" },
        { "launch.loadingResourceFailedSts", "{0} har beg\u00e4rts" },
        { "launch.patchingStatus", "Korrigerar {0} fr\u00e5n {1}" },
        { "launch.progressScreen", "S\u00f6ker efter den senaste versionen..." },
        { "launch.stalledDownload", "V\u00e4ntar p\u00e5 data..." },
        { "launch.validatingProgress", "Avl\u00e4ser poster ({0}% klart)" },
        { "launch.validatingStatus", "Validerar {0} fr\u00e5n {1}" },
        { "launcherrordialog.abort", "Avbryt" },
        { "launcherrordialog.abortMnemonic", "VK_A" },
        { "launcherrordialog.brief.continue", "Det gick inte att forts\u00e4tta k\u00f6ra" },
        { "launcherrordialog.brief.details", "Information" },
        { "launcherrordialog.brief.message", "Det g\u00e5r inte att starta det angivna programmet." },
	{ "launcherrordialog.import.brief.message", "Det g\u00e5r inte att importera det angivna programmet." },
        { "launcherrordialog.brief.messageKnown", "Det g\u00e5r inte att starta {0}." },
	{ "launcherrordialog.import.brief.messageKnown", "Det g\u00e5r inte att importera {0}." },
        { "launcherrordialog.brief.ok", "OK" },
        { "launcherrordialog.brief.title", "Java Web Start - {0}" },
        { "launcherrordialog.consoleTab", "Systemf\u00f6nster" },
        { "launcherrordialog.errorcategory", "Kategori: {0}\n\n" },
        { "launcherrordialog.errorintro", "Ett fel intr\u00e4ffade n\u00e4r programmet startades/k\u00f6rdes.\n\n" },
	{ "launcherrordialog.import.errorintro", "Ett fel intr\u00e4ffade n\u00e4r programmet importerades.\n\n" },
        { "launcherrordialog.errormsg", "{0}" },
        { "launcherrordialog.errortitle", "Titel: {0}\n" },
        { "launcherrordialog.errorvendor", "\u00c5terf\u00f6rs\u00e4ljare: {0}\n" },
        { "launcherrordialog.exceptionTab", "Undantag" },
        { "launcherrordialog.generalTab", "Allm\u00e4nt" },
        { "launcherrordialog.genericerror", "Ov\u00e4ntat undantag: {0}" },
        { "launcherrordialog.jnlpMainTab", "Huvudstartfil" },
        { "launcherrordialog.jnlpTab", "Startfil" },
        { "launcherrordialog.title", "Java Web Start - {0}" },
        { "launcherrordialog.wrappedExceptionTab", "Inslaget undantag" },

        { "uninstall.failedMessage", "Det gick inte att avinstallera programmet helt och h\u00e5llet." },
        { "uninstall.failedMessageTitle", "Avinstallera" },
        { "install.alreadyInstalled", "Det finns redan en genv\u00e4g f\u00f6r {0}. Vill du skapa en genv\u00e4g \u00e4nd\u00e5?" },
        { "install.alreadyInstalledTitle", "Skapa genv\u00e4g..." },
        { "install.desktopShortcutName", "{0}" },
        { "install.installFailed", "Kunde inte skapa en genv\u00e4g f\u00f6r {0}." },
        { "install.installFailedTitle", "Skapa genv\u00e4g" },
        { "install.startMenuShortcutName", "{0}" },
        { "install.startMenuUninstallShortcutName", "Avinstallera {0}" },
        { "install.uninstallFailed", "Kunde inte ta bort genv\u00e4garna f\u00f6r {0}. F\u00f6rs\u00f6k igen." },
        { "install.uninstallFailedTitle", "Ta bort genv\u00e4gar" },

	// Mandatory Enterprize configuration not available.
	{ "enterprize.cfg.mandatory", "Du kan inte k\u00f6ra det h\u00e4r programmet eftersom det i systemfilen deployment.config anges att en enterprise-konfigurationsfil \u00e4r obligatorisk och den fil som kr\u00e4vs: {0} \u00e4r inte tillg\u00e4nglig." },

	// Jnlp Cache Viewer:
	{ "jnlp.viewer.title", "Java Application Cache Viewer" },
	{ "jnlp.viewer.all", "Alla" },
	{ "jnlp.viewer.type", "{0}" },
	{ "jnlp.viewer.totalSize", "Total resursstorlek:  {0}" },
        { "jnlp.viewer.emptyCache", "{0}-cachen \u00e4r tom"},
        { "jnlp.viewer.noCache", "Systemcachen har inte konfigurerats"},

	{ "jnlp.viewer.remove.btn.mnemonic", "VK_B" },
	{ "jnlp.viewer.launch.offline.btn.mnemonic", "VK_L" },
	{ "jnlp.viewer.launch.online.btn.mnemonic", "VK_N" },

	{ "jnlp.viewer.file.menu.mnemonic", "VK_A" },
	{ "jnlp.viewer.edit.menu.mnemonic", "VK_R" },
	{ "jnlp.viewer.app.menu.mnemonic", "VK_P" },
	{ "jnlp.viewer.view.menu.mnemonic", "VK_V" },
	{ "jnlp.viewer.help.menu.mnemonic", "VK_H" },

	{ "jnlp.viewer.cpl.mi.mnemonic", "VK_C" },
	{ "jnlp.viewer.exit.mi.mnemonic", "VK_A" },

	{ "jnlp.viewer.reinstall.mi.mnemonic", "VK_I" },
	{ "jnlp.viewer.preferences.mi.mnemonic", "VK_E" },

	{ "jnlp.viewer.launch.offline.mi.mnemonic", "VK_L" },
	{ "jnlp.viewer.launch.online.mi.mnemonic", "VK_N" },
	{ "jnlp.viewer.install.mi.mnemonic", "VK_I" },
	{ "jnlp.viewer.uninstall.mi.mnemonic", "VK_U" },
	{ "jnlp.viewer.remove.mi.mnemonic", "VK_B" },
	{ "jnlp.viewer.show.mi.mnemonic", "VK_S" },
	{ "jnlp.viewer.browse.mi.mnemonic", "VK_H" },

	{ "jnlp.viewer.view.0.mi.mnemonic", "VK_T" },
	{ "jnlp.viewer.view.1.mi.mnemonic", "VK_A" },
	{ "jnlp.viewer.view.2.mi.mnemonic", "VK_P" },
	{ "jnlp.viewer.view.3.mi.mnemonic", "VK_L" },
	{ "jnlp.viewer.view.4.mi.mnemonic", "VK_I" },

	{ "jnlp.viewer.about.mi.mnemonic", "VK_M" },
	{ "jnlp.viewer.help.java.mi.mnemonic", "VK_J" },
	{ "jnlp.viewer.help.jnlp.mi.mnemonic", "VK_H" },

	{ "jnlp.viewer.remove.btn", "Ta bort" },
	{ "jnlp.viewer.remove.1.btn", "Ta bort de valda {0}" },
	{ "jnlp.viewer.remove.2.btn", "Ta bort de valda posterna" },
	{ "jnlp.viewer.uninstall.btn", "Avinstallera" },
	{ "jnlp.viewer.launch.offline.btn", "Starta offline" },
	{ "jnlp.viewer.launch.online.btn", "Starta online" },

        { "jnlp.viewer.file.menu", "Arkiv" },
        { "jnlp.viewer.edit.menu", "Redigera" },
        { "jnlp.viewer.app.menu", "Program" },
        { "jnlp.viewer.view.menu", "Vy" },
        { "jnlp.viewer.help.menu", "Hj\u00e4lp" },

	{ "jnlp.viewer.cpl.mi", "Starta Java-kontrollpanelen" },
	{ "jnlp.viewer.exit.mi", "Avsluta" },

	{ "jnlp.viewer.reinstall.mi", "Installera om ..." },
	{ "jnlp.viewer.preferences.mi", "Egenskaper ..." },

	{ "jnlp.viewer.launch.offline.mi", "Starta offline" },
	{ "jnlp.viewer.launch.online.mi", "Starta online" },
	{ "jnlp.viewer.install.mi", "Installera genv\u00e4gar" },
	{ "jnlp.viewer.uninstall.mi", "Avinstallera genv\u00e4gar" },
        { "jnlp.viewer.remove.0.mi", "Ta bort" },
	{ "jnlp.viewer.remove.mi", "Ta bort {0}" },
	{ "jnlp.viewer.show.mi", "Visa JNLP-beskrivning" },
	{ "jnlp.viewer.browse.mi", "G\u00e5 till hemsidan" },

	{ "jnlp.viewer.view.0.mi", "Alla typer" },
	{ "jnlp.viewer.view.1.mi", "Program" },
	{ "jnlp.viewer.view.2.mi", "Till\u00e4ggsprogram" },
	{ "jnlp.viewer.view.3.mi", "Bibliotek" },
	{ "jnlp.viewer.view.4.mi", "Installerare" },

        { "jnlp.viewer.view.0", "Alla typer" },
        { "jnlp.viewer.view.1", "Program" },
        { "jnlp.viewer.view.2", "Appletprogram" },
        { "jnlp.viewer.view.3", "Bibliotek" },
        { "jnlp.viewer.view.4", "Installerare" },

	{ "jnlp.viewer.about.mi", "Om" },
	{ "jnlp.viewer.help.java.mi", "Hemsidan f\u00f6r J2SE" },
	{ "jnlp.viewer.help.jnlp.mi", "Hemsidan f\u00f6r JNLP" },

        { "jnlp.viewer.app.column", "Program" },
        { "jnlp.viewer.vendor.column", "Leverant\u00f6r" },
        { "jnlp.viewer.type.column", "Typ" },
        { "jnlp.viewer.size.column", "Storlek" },
        { "jnlp.viewer.date.column", "Datum" },
        { "jnlp.viewer.status.column", "Status" },

        { "jnlp.viewer.app.column.tooltip", "Ikon och titel f\u00f6r det h\u00e4r programmet, appletprogrammet eller till\u00e4gget" },
        { "jnlp.viewer.vendor.column.tooltip", "F\u00f6retag som anv\u00e4nder det h\u00e4r objektet" },
        { "jnlp.viewer.type.column.tooltip", "Objektets typ" },
        { "jnlp.viewer.size.column.tooltip", "Objektets storlek och alla dess resurser" },
        { "jnlp.viewer.date.column.tooltip", "Datum d\u00e5 programmet, appletprogrammet eller installeraren senast k\u00f6rdes" },
        { "jnlp.viewer.status.column.tooltip", "Ikon som visar hur och om det h\u00e4r objektet kan startas" },

        { "jnlp.viewer.application", "Program" },
        { "jnlp.viewer.applet", "Till\u00e4ggsprogram" },
        { "jnlp.viewer.extension", "Bibliotek" },
        { "jnlp.viewer.installer", "Installerare" },

        { "jnlp.viewer.offline.tooltip",
                "Det h\u00e4r {0} kan startas b\u00e5de online och offline" },
        { "jnlp.viewer.online.tooltip", "Det h\u00e4r {0} kan startas online" },
        { "jnlp.viewer.norun1.tooltip", 
                "Det h\u00e4r {0} kan bara startas via en webbl\u00e4sare" },
        { "jnlp.viewer.norun2.tooltip", "Till\u00e4ggen kan inte startas" },

	{ "jnlp.viewer.show.title", "JNLP-beskrivning f\u00f6r: {0}" },

	{ "jnlp.viewer.removing", "Tar bort ..." },
	{ "jnlp.viewer.launching", "Startar ..." },
	{ "jnlp.viewer.browsing", "Startar webbl\u00e4sare ..." },
	{ "jnlp.viewer.sorting", "Sorterar poster ..." },
	{ "jnlp.viewer.searching", "S\u00f6ker efter poster ..." },
        { "jnlp.viewer.installing", "Installerar ..." },

        { "jnlp.viewer.reinstall.title", "Installera om borttagna JNLP-program" },
	{ "jnlp.viewer.reinstallBtn", "Installera om valda program" },
	{ "jnlp.viewer.reinstallBtn.mnemonic", "VK_R" },
        { "jnlp.viewer.closeBtn", "St\u00e4ng" },
        { "jnlp.viewer.closeBtn.mnemonic", "VK_S" },

	{ "jnlp.viewer.reinstall.column.title", "Titel:" },
	{ "jnlp.viewer.reinstall.column.location", "Plats:" },

	// cache size warning
	{ "jnlp.cache.warning.title", "Varning g\u00e4llande JNLP-cacheminnets storlek" },
	{ "jnlp.cache.warning.message", "Varning: \n\nDet rekommenderade diskutrymmet f\u00f6r JNLP-program\n och -resurser i cacheminnet har \u00f6verstigits.\n\nF\u00f6r n\u00e4rvarande anv\u00e4nds: {0}\nDen rekommenderade gr\u00e4nsen \u00e4r: {1}\n\nTa bort n\u00e5gra program eller resurser genom att anv\u00e4nda \nJava-kontrollpanelen eller ange en h\u00f6gre gr\u00e4ns." },

        // Control Panel
        { "control.panel.title", "Java-kontrollpanelen" },
        { "control.panel.general", "Allm\u00e4nt" },
        { "control.panel.security", "S\u00e4kerhet" },
        { "control.panel.java", "Java" },
        { "control.panel.update", "Uppdatera" },
        { "control.panel.advanced", "Avancerat" },

        // Common Strings used in different panels.
        { "common.settings", "Inst\u00e4llningar" },
        { "common.ok_btn", "OK" },
        { "common.ok_btn.mnemonic", "VK_O" },
        { "common.cancel_btn", "Avbryt" },
        { "common.cancel_btn.mnemonic", "VK_A" },
        { "common.apply_btn", "Till\u00e4mpa" },
        { "common.apply_btn.mnemonic", "VK_P" },
        { "common.add_btn", "L\u00e4gg till" },
        { "common.add_btn.mnemonic", "VK_L" },
        { "common.remove_btn", "Ta bort" },
        { "common.remove_btn.mnemonic", "VK_B" },

        // Network Settings Dialog
        { "network.settings.dlg.title", "N\u00e4tverksinst\u00e4llningar" },
        { "network.settings.dlg.border_title", " Inst\u00e4llningar f\u00f6r n\u00e4tverksproxy " },
        { "network.settings.dlg.browser_rbtn", "Anv\u00e4nd webbl\u00e4sarinst\u00e4llningar" },
        { "browser_rbtn.mnemonic", "VK_B" },
        { "network.settings.dlg.manual_rbtn", "Anv\u00e4nd proxyserver" },
        { "manual_rbtn.mnemonic", "VK_P" },
        { "network.settings.dlg.address_lbl", "Adress:" },
        { "network.settings.dlg.port_lbl", "Port:" },
        { "network.settings.dlg.advanced_btn", "Avancerat..." },
        { "network.settings.dlg.advanced_btn.mnemonic", "VK_V" },
        { "network.settings.dlg.bypass_text", "Hoppa \u00f6ver proxyservern f\u00f6r lokala adresser" },
        { "network.settings.dlg.bypass.mnemonic", "VK_Y" },
        { "network.settings.dlg.autoconfig_rbtn", "Anv\u00e4nd automatiska proxykonfigurationsskript" },
        { "autoconfig_rbtn.mnemonic", "VK_T" },
        { "network.settings.dlg.location_lbl", "Skriptplats: " },
        { "network.settings.dlg.direct_rbtn", "Direktanslutning" },
        { "direct_rbtn.mnemonic", "VK_D" },
        { "network.settings.dlg.browser_text", "Automatisk konfiguration kan \u00e5sidos\u00e4tta manuella inst\u00e4llningar. Om du vill f\u00f6rs\u00e4kra dig om att de manuella inst\u00e4llningarna anv\u00e4nds b\u00f6r du inaktivera den automatiska konfigurationen." },
        { "network.settings.dlg.proxy_text", "Skriv \u00f6ver proxyinst\u00e4llningar f\u00f6r webbl\u00e4saren." },
        { "network.settings.dlg.auto_text", "Anv\u00e4nd automatiskt proxykonfigurationsskript vid den angivna platsen." },
        { "network.settings.dlg.none_text", "Anv\u00e4nd direktanslutning." },

        // Advanced Network Settings Dialog
        { "advanced.network.dlg.title", "Avancerade n\u00e4tverksinst\u00e4llningar" },
        { "advanced.network.dlg.servers", " Servrar " },
        { "advanced.network.dlg.type", "Typ" },
        { "advanced.network.dlg.http", "HTTP:" },
        { "advanced.network.dlg.secure", "S\u00e4ker:" },
        { "advanced.network.dlg.ftp", "FTP:" },
        { "advanced.network.dlg.socks", "Socks:" },
        { "advanced.network.dlg.proxy_address", "Proxyadress" },
        { "advanced.network.dlg.port", "Port" },
        { "advanced.network.dlg.same_proxy", " Anv\u00e4nd samma proxyserver f\u00f6r alla protokoll" },
        { "advanced.network.dlg.same_proxy.mnemonic", "VK_N" },
        { "advanced.network.dlg.exceptions", " Undantag " },
        { "advanced.network.dlg.no_proxy", " Anv\u00e4nd inte proxyserver f\u00f6r adresser som b\u00f6rjar med" },
        { "advanced.network.dlg.no_proxy_note", " Separera poster med semikolon (;)." },

        // DeleteFilesDialog
        { "delete.files.dlg.title", "Ta bort tempor\u00e4ra filer" },
        { "delete.files.dlg.temp_files", "Vill du ta bort de h\u00e4r tempor\u00e4ra filerna?" },
        { "delete.files.dlg.applets", "H\u00e4mtade till\u00e4ggsprogram" },
        { "delete.files.dlg.applications", "H\u00e4mtade program" },
        { "delete.files.dlg.other", "Andra filer" },

	// General
	{ "general.cache.border.text", " Tempor\u00e4ra Internet-filer " },
	{ "general.cache.delete.text", "Ta bort filer ..." },
        { "general.cache.delete.text.mnemonic", "VK_B" },
	{ "general.cache.settings.text", "Inst\u00e4llningar..." },
        { "general.cache.settings.text.mnemonic", "VK_S" },
	{ "general.cache.desc.text", "Filer som du anv\u00e4nder i Java-program lagras i en speciell mapp f\u00f6r att de snabbt ska kunna k\u00f6ras. Endast avancerade anv\u00e4ndare f\u00e5r ta bort filer eller \u00e4ndra de h\u00e4r inst\u00e4llningarna." },
	{ "general.network.border.text", " N\u00e4tverksinst\u00e4llningar " },
	{ "general.network.settings.text", "N\u00e4tverksinst\u00e4llningar..." },
        { "general.network.settings.text.mnemonic", "VK_N" },
	{ "general.network.desc.text", "N\u00e4tverksinst\u00e4llningarna anv\u00e4nds n\u00e4r Internet-anslutningar g\u00f6rs. Som standard anv\u00e4nder Java n\u00e4tverksinst\u00e4llningarna i webbl\u00e4saren. Endast avancerade anv\u00e4ndare f\u00e5r \u00e4ndra de h\u00e4r inst\u00e4llningarna." },
        { "general.about.border", "Om" },
        { "general.about.text" ,"Visa versionsinformation f\u00f6r Java-kontrollpanelen." },
	{ "general.about.btn", "Om..." },
	{ "general.about.btn.mnemonic", "VK_M" },

	// Security
	{ "security.certificates.border.text", " Certifikat " },
	{ "security.certificates.button.text", "Certifikat..." },
        { "security.certificates.button.mnemonic", "VK_E" },
	{ "security.certificates.desc.text", "Du anv\u00e4nder certifikat f\u00f6r att identifiera dig, certifikationer, utf\u00e4rdare och publicerare." },
	{ "security.policies.border.text", " Principer " },
	{ "security.policies.advanced.text", "Avancerat..." },
        { "security.policies.advanced.mnemonic", "VK_V" },
	{ "security.policies.desc.text", "Du anv\u00e4nder s\u00e4kerhetsprinciper f\u00f6r att kontrollera s\u00e4kerhetsskyddet runt program och till\u00e4ggsprogram." },

	// Update
	{ "update.notify.border.text", " Uppdateringsmeddelande " }, // this one is not currently used. See update panel!!!
	{ "update.updatenow.button.text", "Uppdatera nu" },
	{ "update.updatenow.button.mnemonic", "VK_U" },
	{ "update.advanced.button.text", "Avancerat..." },
	{ "update.advanced.button.mnemonic", "VK_V" },
	{ "update.desc.text", "Med hj\u00e4lp av uppdateringsfunktionen f\u00f6r Java ser du till att alltid ha den senaste uppdaterade versionen av Java-plattformen. Genom att anv\u00e4nda nedanst\u00e5ende alternativ kan du kontrollera hur uppdateringarna h\u00e4mtas och anv\u00e4nds." },
        { "update.notify.text", "Meddela mig:" },
        { "update.notify_install.text", "F\u00f6re installation" },
        { "update.notify_download.text", "F\u00f6re h\u00e4mtning och installation" },
        { "update.autoupdate.text", "S\u00f6k efter uppdateringar automatiskt" },
        { "update.advanced_title.text", "Avancerade inst\u00e4llningar f\u00f6r automatisk uppdatering" },
        { "update.advanced_title1.text", "V\u00e4lj hur ofta och n\u00e4r du vill att s\u00f6kningen ska ske." },
        { "update.advanced_title2.text", "Hur ofta" },
        { "update.advanced_title3.text", "N\u00e4r" },
        { "update.advanced_desc1.text", "Genomf\u00f6r en s\u00f6kning varje dag klockan {0}" },
        { "update.advanced_desc2.text", "Genomf\u00f6r en s\u00f6kning var {0} klockan {1}" },
        { "update.advanced_desc3.text", "Genomf\u00f6r en s\u00f6kning dag {0} i varje m\u00e5nad klockan {1}" },
        { "update.check_daily.text", "Dagligen" },
        { "update.check_weekly.text", "Varje vecka" },
        { "update.check_monthly.text", "Varje m\u00e5nad" },
        { "update.check_date.text", "Dag:" },
        { "update.check_day.text", "Var:" },
        { "update.check_time.text", "Klockan:" },
        { "update.lastrun.text", "Java Update k\u00f6rdes senast klockan {0} den {1}." },
        { "update.desc_autooff.text", "Om du vill s\u00f6ka efter uppdateringar klickar du p\u00e5 knappen \"Uppdatera nu\" h\u00e4r nedanf\u00f6r. Om en uppdatering \u00e4r tillg\u00e4nglig visas en ikon i systemf\u00e4ltet. Flytta mark\u00f6ren ovanf\u00f6r ikonen om du vill visa status f\u00f6r uppdateringen." },
        { "update.desc_check_daily.text", "Java Update s\u00f6ker efter uppdateringar varje dag klockan {0}. " },
        { "update.desc_check_weekly.text", "Java Update s\u00f6ker efter uppdateringar var {0} klockan {1}. " },
        { "update.desc_check_monthly.text", "Java Update s\u00f6ker efter uppdateringar dag {0} i varje m\u00e5nad klockan {1}. " },
        { "update.desc_systrayicon.text", "Om en uppdatering \u00e4r tillg\u00e4nglig visas en ikon i systemf\u00e4ltet. Flytta mark\u00f6ren ovanf\u00f6r ikonen om du vill visa status f\u00f6r uppdateringen. " },
        { "update.desc_notify_install.text", "Du meddelas innan uppdateringen installeras." },
        { "update.desc_notify_download.text", "Du meddelas innan uppdateringen h\u00e4mtas och innan den installeras." },
	{ "update.launchbrowser.error.text", "Det gick inte att starta Java Update Checker. Den senaste versionen av Java Update finns p\u00e5 http://java.sun.com/getjava/javaupdate" },
	{ "update.launchbrowser.error.caption", "Fel - Uppdatering" },

        // CacheSettingsDialog strings:
        { "cache.settings.dialog.delete_btn", "Ta bort filer ..." },
        { "cache.settings.dialog.delete_btn.mnemonic", "VK_B" },
        { "cache.settings.dialog.view_jws_btn", "Visa program..." },
        { "cache.settings.dialog.view_jws_btn.mnemonic", "VK_P" },
        { "cache.settings.dialog.view_jpi_btn", "Visa till\u00e4ggsprogram..." },
        { "cache.settings.dialog.view_jpi_btn.mnemonic", "VK_T" },
        { "cache.settings.dialog.chooser_title", "Plats f\u00f6r tempor\u00e4ra filer" },
        { "cache.settings.dialog.select", "Markera" },
        { "cache.settings.dialog.select_tooltip", "Anv\u00e4nd den markerade platsen" },
        { "cache.settings.dialog.select_mnemonic", "S" },
        { "cache.settings.dialog.title", "Inst\u00e4llningar f\u00f6r tempor\u00e4ra filer" },
        { "cache.settings.dialog.cache_location", "Plats:" },
        { "cache.settings.dialog.change_btn", "\u00c4ndra..." },
        { "cache.settings.dialog.change_btn.mnemonic", "VK_N" },
        { "cache.settings.dialog.disk_space", "M\u00e4ngd diskutrymme som ska anv\u00e4ndas:" },
        { "cache.settings.dialog.unlimited_btn", "Obegr\u00e4nsad" },
        { "cache.settings.dialog.max_btn", "Maxantal" },
        { "cache.settings.dialog.compression", "Jar-komprimering:" },
        { "cache.settings.dialog.none", "Ingen" },
        { "cache.settings.dialog.high", "H\u00f6g" },

	// JNLP File/MIME association dialog strings:
	{ "javaws.association.dialog.title", "JNLP-fil/MIME-associering" },
	{ "javaws.association.dialog.exist.command", "finns redan med:\n{0}"},
	{ "javaws.association.dialog.exist", "finns redan." },
	{ "javaws.association.dialog.askReplace", "\nVill du verkligen hantera den med {0} i st\u00e4llet?" },
	{ "javaws.association.dialog.ext", "Filtypstill\u00e4gg: {0}" },
        { "javaws.association.dialog.mime", "MIME-typ: {0}" },
        { "javaws.association.dialog.ask", "Vill du anv\u00e4nda {0} n\u00e4r du hanterar:" },
        { "javaws.association.dialog.existAsk", "VARNING! Associera med:"},

        // Advanced panel strings:
        { "deployment.console.startup.mode", "Java-konsol" },
        { "deployment.console.startup.mode.SHOW", "Visa konsol" },
        { "deployment.console.startup.mode.SHOW.tooltip", "<html>Starta Java-konsolen maximerad</html>" },
        { "deployment.console.startup.mode.HIDE", "D\u00f6lj konsol" },
        { "deployment.console.startup.mode.HIDE.tooltip", "<html>Starta Java-konsolen minimerad</html>" },
        { "deployment.console.startup.mode.DISABLE", "Starta inte konsol" },
        { "deployment.console.startup.mode.DISABLE.tooltip" ,"<html>Det g\u00e5r inte att starta Java-konsolen</html>" },
        { "deployment.trace" ,"Aktivera sp\u00e5rning" },
        { "deployment.trace.tooltip" ,"<html>Skapa sp\u00e5rfil f\u00f6r fels\u00f6kning</html>" },
        { "deployment.log" ,"Aktivera loggning" },
        { "deployment.log.tooltip" ,"<html>Skapa loggfil f\u00f6r att samla in information om<br>fel</html>" },
        { "deployment.control.panel.log", "Loggning i kontrollpanelen" },
        { "deployment.javapi.lifecycle.exception", "Visa livscykelundantag f\u00f6r miniprogram" },
        { "deployment.javapi.lifecycle.exception.tooltip", "<html>Visa dialogrutan med undantag n\u00e4r<br>fel intr\u00e4ffar d\u00e5 miniprogrammet laddas<html>" },
        { "deployment.browser.vm.iexplorer", "Internet Explorer" },
        { "deployment.browser.vm.iexplorer.tooltip", "<html>Anv\u00e4nd Sun Java med APPLET-kod<br>i webbl\u00e4saren Internet Explorer</html>" },
        { "deployment.browser.vm.mozilla", "Mozilla och Netscape" },
        { "deployment.browser.vm.mozilla.tooltip", "<html>Anv\u00e4nd Sun Java med APPLET-kod i<br>webbl\u00e4sarna Mozilla och Netscape</html>" },
        { "deployment.console.debugging", "Fels\u00f6kning" },
	{ "deployment.browsers.applet.tag", "st\u00f6d f\u00f6r <APPLET>-kod" },
        { "deployment.javaws.shortcut", "Skapa genv\u00e4gar" },
        { "deployment.javaws.shortcut.ALWAYS", "Till\u00e5t alltid" },
        { "deployment.javaws.shortcut.ALWAYS.tooltip", "<html>Skapa alltid genv\u00e4gar</html>" },
        { "deployment.javaws.shortcut.NEVER" , "Till\u00e5t aldrig" },
        { "deployment.javaws.shortcut.NEVER.tooltip", "<html>Skapa inte genv\u00e4gar</html>" },
        { "deployment.javaws.shortcut.ASK_USER", "Fr\u00e5ga anv\u00e4ndaren" },
        { "deployment.javaws.shortcut.ASK_USER.tooltip", "<html>Fr\u00e5ga anv\u00e4ndaren om en genv\u00e4g<br>ska skapas</html>" },
        { "deployment.javaws.shortcut.ALWAYS_IF_HINTED", "Till\u00e5t alltid vid tips" },
        { "deployment.javaws.shortcut.ALWAYS_IF_HINTED.tooltip", "<html>Skapa alltid genv\u00e4gar om<br>JNLP-programmet beg\u00e4r det</html>" },
        { "deployment.javaws.shortcut.ASK_IF_HINTED", "Fr\u00e5ga anv\u00e4ndaren vid tips" },
        { "deployment.javaws.shortcut.ASK_IF_HINTED.tooltip", "<html>Fr\u00e5ga anv\u00e4ndaren om en genv\u00e4g<br>ska skapas om det beg\u00e4rs av<br>JNLP-programmet</html>" },
	{ "deployment.javaws.associations.NEVER", "Till\u00e5t aldrig" },
        { "deployment.javaws.associations.NEVER.tooltip", "<html>Skapa aldrig filtypstill\u00e4gg/MIME<br>-associering</html>" },
        { "deployment.javaws.associations.ASK_USER", "Fr\u00e5ga anv\u00e4ndaren" },
        { "deployment.javaws.associations.ASK_USER.tooltip", "<html>Fr\u00e5ga anv\u00e4ndaren innan filtypstill\u00e4gg<br>/MIME-associering skapas</html>" },
        { "deployment.javaws.associations.REPLACE_ASK", "Uppmana anv\u00e4ndaren att ers\u00e4tta" },
        { "deployment.javaws.associations.REPLACE_ASK.tooltip", "<html>Fr\u00e5ga bara anv\u00e4ndaren om<br>befintligt filtypstill\u00e4gg/MIME<br>-associering ers\u00e4tts</html>" },
        { "deployment.javaws.associations.NEW_ONLY", "Till\u00e5t om associeringen \u00e4r ny" },
        { "deployment.javaws.associations.NEW_ONLY.tooltip", "<html>Skapa aldrig nytt filtypstill\u00e4gg/MIME<br>-associering</html>" },
        { "deployment.javaws.associations", "JNLP-fil/MIME-associering" },
        { "deployment.security.settings", "S\u00e4kerhet" },
        { "deployment.security.askgrantdialog.show" ,"Till\u00e5t att anv\u00e4ndaren beviljar \u00e5tkomst till signerat inneh\u00e5ll" },
        { "deployment.security.askgrantdialog.notinca" ,"Till\u00e5t att anv\u00e4ndaren beviljar \u00e5tkomst till inneh\u00e5ll fr\u00e5n en ej betrodd utf\u00e4rdare" },
        { "deployment.security.browser.keystore.use" ,"Anv\u00e4nd certifikat och nycklar i webbl\u00e4sarens keystore" },
        { "deployment.security.notinca.warning" ,"Varna om det inte g\u00e5r att verifiera certifikatutf\u00e4rdaren" },
        { "deployment.security.expired.warning" ,"Varna om certifikatet har upph\u00f6rt att g\u00e4lla eller inte \u00e4r giltigt \u00e4n" },
        { "deployment.security.jsse.hostmismatch.warning" ,"Varna om platscertifikatet inte matchar v\u00e4rdnamnet" },
        { "deployment.security.sandbox.awtwarningwindow" ,"Visa varningsbanderoll i begr\u00e4nsat l\u00e4ge (sandl\u00e5dan)" },
        { "deployment.security.sandbox.jnlp.enhanced" ,"Till\u00e5t att anv\u00e4ndaren accepterar s\u00e4kerhetsfr\u00e5gor f\u00f6r JNLP" },
        { "deploy.advanced.browse.title", "V\u00e4lj fil som ska starta standardwebbl\u00e4saren" },
        { "deploy.advanced.browse.select", "Markera" },
        { "deploy.advanced.browse.select_tooltip", "Starta webbl\u00e4saren med den valda filen" },
        { "deploy.advanced.browse.select_mnemonic", "S" },
        { "deploy.advanced.browse.browse_btn", "Bl\u00e4ddra..." },
        { "deploy.advanced.browse.browse_btn.mnemonic", "VK_B" },
        { "deployment.browser.default", "Kommando som startar standardwebbl\u00e4saren" },
        { "deployment.misc.label", "Diverse" },
        { "deployment.system.tray.icon", "Placera Java-ikonen i systemf\u00e4ltet" },
        { "deployment.system.tray.icon.tooltip", "<html>Markera det h\u00e4r alternativet om du vill visa Java<br>-ikonen i systemf\u00e4ltet n\u00e4r<br>Java k\u00f6rs i webbl\u00e4saren</html>" },

        //PluginJresDialog strings:
        { "jpi.jres.dialog.title", "Inst\u00e4llningar f\u00f6r Java Runtime" },
        { "jpi.jres.dialog.border", " Java Runtime-versioner " },
        { "jpi.jres.dialog.column1", "Produktnamn" },
        { "jpi.jres.dialog.column2", "Version" },
        { "jpi.jres.dialog.column3", "Plats" },
        { "jpi.jres.dialog.column4", "Parametrar f\u00f6r Java Runtime" },
        { "jpi.jdk.string", "JDK" },
        { "jpi.jre.string", "JRE" },
        { "jpi.jres.dialog.product.tooltip", "V\u00e4lj JRE eller JDK som produktnamn." },

        // AboutDialog strings:
        { "about.dialog.title", "Om Java" },

        // JavaPanel strings:
        { "java.panel.plugin.border", " Inst\u00e4llningar f\u00f6r Java Applet Runtime " },
        { "java.panel.plugin.text", "K\u00f6rtidsinst\u00e4llningarna anv\u00e4nds n\u00e4r ett till\u00e4ggsprogram k\u00f6rs i webbl\u00e4saren." },
        { "java.panel.jpi_view_btn", "Visa ..." },
        { "java.panel.javaws_view_btn", "Visa ..." },
        { "java.panel.jpi_view_btn.mnemonic", "VK_V" },
        { "java.panel.javaws_view_btn.mnemonic", "VK_I" },
        { "java.panel.javaws.border" ," Inst\u00e4llningar f\u00f6r Java Application Runtime " },
        { "java.panel.javaws.text" ,"K\u00f6rtidsinst\u00e4llningar anv\u00e4nds n\u00e4r ett Java-program eller miniprogram laddas med hj\u00e4lp av JNLP (Java Network Launching Protocol)." },

        // Strings in the confirmation dialogs for APPLET tag in browsers.
        { "browser.settings.alert.text", "<html><b>Nyare version av Java Runtime finns</b></html>Internet Explorer har redan en nyare version av Java Runtime. Vill du ers\u00e4tta den?\n" },
        { "browser.settings.success.caption", "Lyckades - Webbl\u00e4sare" },
        { "browser.settings.success.text", "<html><b>Webbl\u00e4sarinst\u00e4llningarna har \u00e4ndrats</b></html>\u00c4ndringarna b\u00f6rjar g\u00e4lla n\u00e4r webbl\u00e4saren startas om.\n" },
        { "browser.settings.fail.caption", "Varning - Webbl\u00e4sare" },
        { "browser.settings.fail.moz.text", "<html><b>Kunde inte \u00e4ndra webbl\u00e4sarinst\u00e4llningar</b></html>Kontrollera att Mozilla eller Netscape \u00e4r ordentligt installerad p\u00e5 datorn och att du har tillr\u00e4cklig beh\u00f6righet att \u00e4ndra systeminst\u00e4llningarna.\n" },
        { "browser.settings.fail.ie.text", "<html><b>Kunde inte \u00e4ndra webbl\u00e4sarinst\u00e4llningar</b></html>Kontrollera att du har tillr\u00e4cklig beh\u00f6righet att \u00e4ndra systeminst\u00e4llningarna.\n" },


        // Tool tip strings.
        { "cpl.ok_btn.tooltip" ,"<html>St\u00e4ng Java-kontrollpanelen och<br>spara \u00e4ndringarna du gjort</html>" },
        { "cpl.apply_btn.tooltip" ,"<html>Spara alla \u00e4ndringar du gjort<br>utan att st\u00e4nga Java-kontrollpanelen</html>" },
        { "cpl.cancel_btn.tooltip" ,"<html>St\u00e4nga Java-kontrollpanelen<br>utan att spara n\u00e5gra \u00e4ndringar</html>" },

        {"network.settings.btn.tooltip", "<html>\u00c4ndra inst\u00e4llningarna f\u00f6r Internet-anslutningen</html>" },

        {"temp.files.settings.btn.tooltip", "<html>\u00c4ndra inst\u00e4llningarna f\u00f6r tempor\u00e4ra filer</html>" },

        {"temp.files.delete.btn.tooltip", "<html>" +  // body bgcolor=\"#FFFFCC\">"+
                                          "Ta bort tempor\u00e4ra Java-filer" +
                                          "</html>"},

        {"delete.files.dlg.applets.tooltip", "<html>Markera det h\u00e4r alternativet om du vill ta bort alla<br>tempor\u00e4ra filer som skapats av Java-miniprogram</html>" },

        {"delete.files.dlg.applications.tooltip", "<html>Markera det h\u00e4r alternativet om du vill ta bort alla<br>tempor\u00e4ra filer som skapats av Java Web Start<br>-program</html>" },

        {"delete.files.dlg.other.tooltip", "<html>Markera det h\u00e4r alternativet om du vill ta bort alla<br>andra tempor\u00e4ra filer som skapats av Java</html>" },

        {"delete.files.dlg.temp_files.tooltip", "<html>Java-program kan lagra en del tempor\u00e4ra filer<br>p\u00e5 datorn. Du kan<br>ta bort de h\u00e4r filerna.<br><p>En del Java-program kanske startar<br>l\u00e5ngsammare f\u00f6rsta g\u00e5ngen du k\u00f6r dem<br>efter att du tagit bort de tempor\u00e4ra filerna.</html>" },

        {"cache.settings.dialog.view_jws_btn.tooltip", "<html>Visa tempor\u00e4ra filer som skapats av<br>Java Web Start-program</html>" },
        {"cache.settings.dialog.view_jpi_btn.tooltip", "<html>Visa tempor\u00e4ra filer som skapats av<br>Java-miniprogram</html>" },
        {"cache.settings.dialog.change_btn.tooltip", "<html>Ange i vilken katalog som de tempor\u00e4ra<br>filerna lagras</html>" },
        {"cache.settings.dialog.unlimited_btn.tooltip", "<html>Begr\u00e4nsa inte m\u00e4ngden diskutrymme som<br>anv\u00e4nds f\u00f6r att lagra tempor\u00e4ra filer</html>" },
        {"cache.settings.dialog.max_btn.tooltip", "<html>Ange det maximala diskutrymmet som<br>anv\u00e4nds f\u00f6r lagring av de tempor\u00e4ra filerna.</html>" },

        { "cache.settings.dialog.compression.tooltip" ,"<html>Ange komprimeringsgraden som ska anv\u00e4ndas<br>f\u00f6r JAR-filer som lagras av Java-program<br>i katalogen f\u00f6r tempor\u00e4ra filer<br><p>\"Ingen\" g\u00f6r att Java-programmen startar<br>snabbare, men den m\u00e4ngd diskutrymme<br>som kr\u00e4vs f\u00f6r att lagra dem \u00f6kar.  H\u00f6gre<br>v\u00e4rden g\u00f6r att mindre diskutrymme kr\u00e4vs, medan<br>tiden det tar att starta programmen \u00f6kar n\u00e5got.</html>" },
        { "common.ok_btn.tooltip" ,"<html>Spara \u00e4ndringarna och st\u00e4ng dialogrutan</html>" },
        { "common.cancel_btn.tooltip" ,"<html>Avbryt \u00e4ndringarna och st\u00e4ng dialogrutan</html>" },
        { "network.settings.advanced_btn.tooltip" ,"<html>Visa och \u00e4ndra avancerade proxyinst\u00e4llningar</html>" },
        { "security.certs_btn.tooltip" ,"<html>Importera, exportera eller ta bort certifikat</html>" },
        { "cert.import_btn.tooltip" ,"<html>Importera ett certifikat som inte finns<br>p\u00e5 listan</html>" },
        { "cert.export_btn.tooltip" ,"<html>Exportera det markerade certifikatet</html>" },
        { "cert.remove_btn.tooltip" ,"<html>Ta bort det markerade certifikatet<br>fr\u00e5n listan</html>" },
        { "cert.details_btn.tooltip" ,"<html>Visa detaljerad information om<br>det markerade certifikatet</html>" },
        { "java.panel.jpi_view_btn.tooltip" ,"<html>\u00c4ndra Java Runtime-inst\u00e4llningar f\u00f6r till\u00e4ggsprogram</html>" },
        { "java.panel.javaws_view_btn.tooltip" ,"<html>\u00c4ndra Java Runtime-inst\u00e4llningar f\u00f6r program</html>" },
        { "general.about.btn.tooltip" ,"<html>Visa information om den h\u00e4r versionen<br>av J2SE Runtime Environment</html>" },
        { "update.notify_combo.tooltip" ,"<html>Markera n\u00e4r du vill meddelas <br>om nya Java-uppdateringar</html>" },
        { "update.advanced_btn.tooltip" ,"<html>\u00c4ndra schemal\u00e4ggningspolicy<br>f\u00f6r automatiska uppdateringar</html>" },
        { "update.now_btn.tooltip" ,"<html>Starta Java Update om du vill s\u00f6ka efter<br>de senaste Java-uppdateringarna som \u00e4r tillg\u00e4ngliga</html>" },
        { "vm.options.add_btn.tooltip" ,"<html>L\u00e4gga till en ny JRE i listan</html>" },
        { "vm.options.remove_btn.tooltip" ,"<html>Ta bort den markerade posten fr\u00e5n listan</html>" },
        { "vm.optios.ok_btn.tooltip" ,"<html>Spara alla poster som inneh\u00e5ller<br>produktnamn, version och<br>platsinformation</html>" },
        { "jnlp.jre.find_btn.tooltip" ,"<html>S\u00f6k efter en installerad Java Runtime<br>Environment</html>" },
        { "jnlp.jre.add_btn.tooltip" ,"<html>L\u00e4gga till en ny post i listan</html>" },
        { "jnlp.jre.remove_btn.tooltip" ,"<html>Ta bort den markerade posten fr\u00e5n<br>anv\u00e4ndarlistan</html>" },

        // JaWS Auto Download JRE Prompt
        { "download.jre.prompt.title", "Till\u00e5t JRE-h\u00e4mtning" },
        { "download.jre.prompt.text1", "Programmet \"{0}\" kr\u00e4ver en version av JRE (versionen {1}) som inte finns installerad p\u00e5 datorn." },
        { "download.jre.prompt.text2", "Vill du att Java Web Start ska h\u00e4mta och installera den h\u00e4r JRE-versionen automatiskt?" },
        { "download.jre.prompt.okButton", "H\u00e4mta" },
        { "download.jre.prompt.okButton.acceleratorKey", new Integer(KeyEvent.VK_H)},
        { "download.jre.prompt.cancelButton", "Avbryt" },
        { "download.jre.prompt.cancelButton.acceleratorKey", new Integer(KeyEvent.VK_A)},
	{ "autoupdatecheck.buttonYes", "Ja" },
	{ "autoupdatecheck.buttonYes.acceleratorKey", new Integer(KeyEvent.VK_J)},
	{ "autoupdatecheck.buttonNo", "Nej" },
	{ "autoupdatecheck.buttonNo.acceleratorKey", new Integer(KeyEvent.VK_N)},
        { "autoupdatecheck.buttonAskLater", "Fr\u00e5ga senare" },
        { "autoupdatecheck.buttonAskLater.acceleratorKey", new Integer(KeyEvent.VK_F)},
        { "autoupdatecheck.caption", "S\u00f6k efter uppdateringar automatiskt" },
        { "autoupdatecheck.message", "Med Java Update kan du uppdatera Java automatiskt vartefter nya versioner blir tillg\u00e4ngliga. Vill du aktivera den h\u00e4r tj\u00e4nsten?" },
    };
}

