#
# @(#)Makefile	1.5 10/03/23
#
# Copyright (c) 2006, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#

DEMO_NAME=heapTracker
USES_AGENT_UTIL=true
USES_CRW=true

# Source files
FILES_c = $(CTARGDIR)heapTracker.c

# Class files needed 
FILES_classes = HeapTracker.class

# Include basic demo template makefile
include ../Demo.gmk

