#
# Copyright (c) 2007, Oracle and/or its affiliates. All rights reserved.
# ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#  
#

Variant=compiler1
!include local.make

!include $(HOTSPOTWORKSPACE)/make/windows/projectfiles/common/Makefile
